from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1]
old=(R/'references/charger-preview.js').read_text();draw=old[old.index('function drawModel'):old.index('root.WildcraftChargerPreview=')]
draw=draw.replace('energy,yaw=-25,pitch=18,present=true,state=2','state=0,yaw=-25,pitch=18').replace('canvas.width=640;canvas.height=450;','const W=canvas.width,H=canvas.height;').replace('_batteryGl','_fabricatorGl').replace('alpha:false,antialias:true','alpha:false,antialias:false').replace('gl.viewport(0,0,640,450)','gl.viewport(0,0,W,H)').replace('makeFaces(geo,energy,present,state)','makeFaces(geo,state)').replace('-p[0]*22/320','-p[0]*Math.min(W,H)*.038/(W/2)').replace('-p[1]*22/225','-p[1]*Math.min(W,H)*.038/(H/2)')
start=draw.index('return {energy,');end=draw.index(';',start);draw=draw[:start]+"return {state,visibleFaces:faces.length,yaw,pitch,modelCuboids:geo.parts.length,materialBadges:geo.badges.length,depthTest:true,nearestTexture:true,width:W,height:H}"+draw[end:]
make='''function makeFaces(geo,state=0){const faces=[],normals={north:[0,0,-1],south:[0,0,1],west:[-1,0,0],east:[1,0,0],up:[0,1,0],down:[0,-1,0]};
for(const p of geo.parts){const [x0,y0,z0]=p.from,[x1,y1,z1]=p.to;const v={south:[[x1,y1,z1],[x0,y1,z1],[x0,y0,z1],[x1,y0,z1]],north:[[x0,y1,z0],[x1,y1,z0],[x1,y0,z0],[x0,y0,z0]],west:[[x0,y1,z1],[x0,y1,z0],[x0,y0,z0],[x0,y0,z1]],east:[[x1,y1,z0],[x1,y1,z1],[x1,y0,z1],[x1,y0,z0]],up:[[x0,y1,z1],[x1,y1,z1],[x1,y1,z0],[x0,y1,z0]],down:[[x0,y0,z0],[x1,y0,z0],[x1,y0,z1],[x0,y0,z1]]};for(const [dir,points] of Object.entries(v))faces.push({name:p.name,vertices:points,normal:normals[dir],uv:p.faces[dir].uv});}
for(const q of [...geo.badges,{...geo.statusPanel,name:'status/'+state,uv:geo.statusPanel.tiles[state]}]){const [x0,y0,z]=q.from,[x1,y1]=q.to;faces.push({name:q.name,vertices:[[x1,y1,z],[x0,y1,z],[x0,y0,z],[x1,y0,z]],normal:[0,0,1],uv:q.uv});}return faces;}
'''
js='(function(root){\n'+make+draw+'root.WildcraftFabricatorPreview={makeFaces,drawModel};})(globalThis);\n';(R/'source/fabricator-preview.js').write_text(js)
images={n:'data:image/png;base64,'+base64.b64encode((R/'review'/n).read_bytes()).decode() for n in ['fabricator-state-'+str(i)+'.png' for i in range(3)]+['fabricator-front.png','fabricator-back.png','fabricator-side.png','fabricator-top.png','fabricator-input-closeup.png','fabricator-output-closeup.png']}
for n,p in [('atlas',R/'exports/fabricator-atlas-64.png'),('charger',R/'references/charger-charger-state-0.png')]:images[n]='data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · 古代装置制造机 v01</title><style>
*{box-sizing:border-box}body{margin:0;background:#14231b;color:#e2e9dc;font:15px system-ui,"PingFang SC",sans-serif}main{max-width:1240px;padding:28px 24px;margin:auto}h1{font-size:29px;margin:10px 0}p{color:#b2c1ae;line-height:1.75}.tag{color:#ddb675}.controls{display:flex;flex-wrap:wrap;gap:16px;background:#253729;border:1px solid #465c44;padding:16px;border-radius:6px}label{display:flex;align-items:center;gap:8px}select,input{accent-color:#ce9560;background:#19281f;color:#e2e9dc;padding:6px;border:1px solid #657760;border-radius:3px}button{cursor:pointer;background:#304732;color:#e2e9dc;border:1px solid #657760;border-radius:4px;padding:8px 12px}.row{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:18px 0}.panel{background:#253729;border:1px solid #465c44;border-radius:6px;padding:16px;min-width:0}.panel h2{font-size:17px;margin:0 0 12px}canvas.model{width:100%;height:auto;display:block}img{max-width:100%;height:auto;display:block}.pixel{image-rendering:pixelated}.small{font-size:13px;color:#a6b99e}.poses{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}.board{width:100%;height:auto}.inventory{display:flex;flex-wrap:wrap;gap:22px;align-items:flex-start}.inventory figure{margin:0}figcaption{margin-top:8px;color:#b2c1ae}.inventory canvas{width:128px;height:128px}.atlas{width:256px;height:256px}a{color:#d3dfbd}@media(max-width:900px){.row{grid-template-columns:1fr}main{padding:20px 14px}}
</style><main><span class="tag">F06-01 · v01 · 草稿待审 · 未接入游戏</span><h1>古代装置制造机 · 双材料，单出料</h1><p>封闭的加工箱体沿用钢、深绿金属和铜色；正面双材料标记、固定压头及下方出料凹槽形成三层结构。所有几何保持一格尺度，随机产物不在制作中提前显示。</p>
<div class="controls"><label>审稿状态<select id="state"><option value="0">空闲 · 中性方框</option><option value="1">工作 · 双箭头</option><option value="2">完成 · 勾号</option></select></label><label>朝向<input id="yaw" type="range" min="-180" max="180" value="-25"></label><label>俯仰<input id="pitch" type="range" min="-70" max="70" value="18"></label></div><div class="poses"><button data-yaw="0">正面</button><button data-yaw="-25">斜侧面</button><button data-yaw="180">背面</button><button data-yaw="90">侧面</button><button id="reset">重置</button></div>
<div class="row"><section class="panel"><h2>实际几何 · 可转动查看</h2><canvas class="model" id="model" width="640" height="450"></canvas><p id="reading"></p><p class="small">三态是美术审稿输入。游戏当前只向菜单同步状态；世界里的工作及完成提示还需接入。压头固定，无循环升降动画。</p></section><section class="panel"><h2>实际模型与 UV 渲染</h2><img id="render"><p class="small">同一模型、同一原生图集。出料凹槽始终保持空白，避免透露随机结果。</p></section></div>
<div class="row"><section class="panel"><h2>物品栏尺度 · 直接由模型绘制</h2><div class="inventory"><figure><canvas class="pixel" id="item32" width="32" height="32"></canvas><figcaption>32×32 模型派生参考</figcaption></figure><figure><canvas class="pixel" id="item16" width="16" height="16"></canvas><figcaption>16×16 模型派生参考</figcaption></figure></div><p class="small">这是方块模型在小画布上的显示检查，没有独立绘制或缩小概念图生成物品贴图。</p></section><section class="panel"><h2>原生 64×64 图集 · 四层源稿</h2><img class="pixel atlas" id="atlas"><p class="small">六块材质原样复用充电器。双材料标记与三态符号都放在同一图集；不需要额外 Shader、粒子或动态图集。</p></section></div>
<canvas class="board" id="board" width="1200" height="1830"></canvas><p>每批使用 4 铜锭与 2 红石，持续 100 个已加载世界刻。材料标记和出料凹槽是外观表达，交互仍通过现有菜单；没有增加外部输入口、电网接口或新的碰撞行为。制造机完整界面按 F06-02 另行制作。</p></main>
<script>__JS__</script><script>
const G=__G__,sources=__IMAGES__,assets={},C=WildcraftFabricatorPreview,names=['空闲','工作中','完成'];function get(id){return document.getElementById(id)}
function update(){const s=+get('state').value,info=C.drawModel(get('model'),assets.atlas,G,s,+get('yaw').value,+get('pitch').value);get('reading').textContent=names[s]+' · 43 个方盒 / 双材料标记 / 通用状态符号';get('render').src=sources['fabricator-state-'+s+'.png'];window.currentState={s,info};}
function text(c,s,x,y,size=18,color='#dde6d4',bold=false){c.fillStyle=color;c.font=(bold?'600 ':'')+size+'px system-ui,"PingFang SC",sans-serif';c.fillText(s,x,y)}
function panel(c,x,y,w,h){c.fillStyle='#263a2b';c.fillRect(x,y,w,h);c.strokeStyle='#445f43';c.strokeRect(x+.5,y+.5,w-1,h-1)}
function drawBoard(){const c=get('board').getContext('2d');c.fillStyle='#14251b';c.fillRect(0,0,1200,1830);text(c,'WILDCRAFT / ANCIENT DEVICE FABRICATOR',38,47,16,'#a6ba98',true);text(c,'古代装置制造机 · 双材料，单出料',38,94,32,'#e2ead9',true);text(c,'F06-01 v01 · 实际模型 / 原生64图集 · 草稿待审 · 未接入游戏',38,127,17,'#dfb778');
[['fabricator-state-0.png','封闭加工箱体 · 固定压头'],['fabricator-front.png','双材料标记 / 单出料凹槽']].forEach(([key,label],i)=>{const x=38+i*574;panel(c,x,153,550,554);text(c,label,x+16,182,18,'#c1d2b5',true);c.drawImage(assets[key],x+25,195,500,500);});
text(c,'43个方盒 + 2个材料标记 + 1个可替换状态面；所有外观保持一格尺度。',38,741,18,'#c1d2b5');text(c,'三种状态 · 形状与颜色共同提示',38,787,24,'#e2ead9',true);
for(let i=0;i<3;i++){const x=38+i*382;panel(c,x,809,360,306);text(c,names[i],x+14,839,18,'#c1d2b5',true);c.drawImage(assets['fabricator-state-'+i+'.png'],x+74,850,214,214);c.imageSmoothingEnabled=false;c.drawImage(assets.atlas,32+i*8,48,8,8,x+16,1070,32,32);c.imageSmoothingEnabled=true;text(c,['0/1：准备或材料不足','2：加工中','3/4：等待转移或待取'][i],x+60,1092,16);}
text(c,'材质统一与外形区分',38,1160,24,'#e2ead9',true);[['fabricator-back.png','背面维护板与侧面通风'],['fabricator-top.png','顶盖与铜色线路'],['charger','已采用充电器：开放单槽']].forEach(([key,label],i)=>{const x=38+i*382;panel(c,x,1181,360,375);text(c,label,x+12,1211,16,'#c1d2b5',true);c.drawImage(assets[key],x+15,1222,330,330);});
panel(c,38,1580,1124,172);c.imageSmoothingEnabled=false;c.drawImage(assets.atlas,54,1593,144,144);c.drawImage(get('item32'),228,1595,112,112);c.drawImage(get('item16'),370,1595,112,112);c.imageSmoothingEnabled=true;text(c,'原生64图集',53,1740,15);text(c,'32px 模型参考',220,1740,15);text(c,'16px 模型参考',366,1740,15);text(c,'复用6块材质；独立面板、双材料与三态符号',523,1625,18);text(c,'100个已加载世界刻；随机结果不提前显示',523,1662,18);text(c,'无独立物品贴图 / 无发光 / 无粒子 / 无升降动画',523,1699,16);text(c,'世界三态尚需同步接入；本次未制作制造机完整GUI。',38,1793,17,'#dfb778');}
window.ready=(async()=>{await Promise.all(Object.entries(sources).map(async([key,src])=>{const im=new Image();im.src=src;await im.decode();assets[key]=im;}));get('atlas').src=sources.atlas;get('state').onchange=update;get('yaw').oninput=get('pitch').oninput=update;document.querySelectorAll('[data-yaw]').forEach(b=>b.onclick=()=>{get('yaw').value=b.dataset.yaw;get('pitch').value=18;update()});get('reset').onclick=()=>{get('state').value=0;get('yaw').value=-25;get('pitch').value=18;update()};C.drawModel(get('item32'),assets.atlas,G,0,-25,18);C.drawModel(get('item16'),assets.atlas,G,0,-25,18);update();drawBoard();window.appReady=true;return true})();
</script></html>'''
html=html.replace('__JS__',js).replace('__G__',json.dumps(json.loads((R/'source/geometry-and-uv.json').read_text()))).replace('__IMAGES__',json.dumps(images));(R/'review/preview.html').write_text(html);print('Self-contained interactive review, geometry-derived 32/16 canvases and review board created',len(html))
