/* F03-02 art-review layout. No inventory mutation or server connection. */
const SLOT={size:18,item:[1,1,16,16],mark:[0,0,5,5],bar:[3,14,13,2],countY:10};
const glyphs={'0':['01110','10001','10011','10101','11001','10001','01110'],'1':['00100','01100','00100','00100','00100','00100','01110'],'2':['01110','10001','00001','00010','00100','01000','11111'],'3':['11110','00001','00001','01110','00001','00001','11110'],'4':['00010','00110','01010','10010','11111','00010','00010'],'5':['11111','10000','10000','11110','00001','00001','11110'],'6':['00110','01000','10000','11110','10001','10001','01110'],'7':['11111','00001','00010','00100','01000','01000','01000'],'8':['01110','10001','10001','01110','10001','10001','01110'],'9':['01110','10001','10001','01111','00001','00010','01100']};
const hostNames={zh:{sword:'钻石剑',axe:'钻石斧',shield:'盾牌',arrow:'箭'},en:{sword:'Diamond Sword',axe:'Diamond Axe',shield:'Shield',arrow:'Arrow'}},materialNames={zh:{stone:'石头',diamond:'钻石',feather:'羽毛'},en:{stone:'Stone',diamond:'Diamond',feather:'Feather'}};
let icons={},imageAtlas,ready=false;const el=id=>document.getElementById(id);let selected=0,lastRects=[],hostDurability=.7;
function view(state){const retained=['fused','inactive'].includes(state.phase);return {mark:retained,attached:retained&&state.phase!=='inactive',uses:retained||state.phase==='returned'?state.uses:null,low:retained&&state.phase!=='inactive'&&state.uses<=4,kind:state.phase==='inactive'?6:state.material==='stone'?1:0,available:state.phase!=='inactive',returned:state.phase==='returned'};}
function imageKey(state){const v=view(state);return v.returned?'material-'+state.material:state.host+'-'+state.material+'-'+(v.attached?'fused':'bare');}
function fixture(phase='fused',uses=32,host='sword',material='stone',extra={}){return {phase,uses,host,material,count:1,durability:host==='arrow'?null:.7,glint:false,...extra};}
function current(){return fixture(el('phase').value,+el('uses').value,el('host').value,el('material').value,{glint:el('glint').checked,durability:el('host').value==='arrow'?null:hostDurability});}
function slots(s){return [s,fixture('unfused',32,'sword'),fixture('fused',8,'axe','diamond'),fixture('fused',4,'shield','feather'),fixture('fused',1,'arrow','feather'),fixture('unfused',32,'arrow','feather',{count:64}),fixture('returned',8,'sword','stone'),fixture('inactive',8,'axe'),null,fixture('fused',1,'sword','diamond',{durability:.07}),fixture('spent',32,'sword'),fixture('fused',32,'shield','diamond',{glint:true}),...Array(15).fill(null)];}
function digits(c,s,x,y,color='#ffffff'){const width=s.length*6-1;for(const [fill,dx,dy]of [['#242424',1,1],[color,0,0]]){c.fillStyle=fill;[...s].forEach((a,j)=>glyphs[a].forEach((row,k)=>[...row].forEach((v,i)=>{if(v==='1')c.fillRect(x-width+j*6+i+dx,y+k+dy,1,1);})));}}
function txt(c,t,x,y,color='#e8e6da',size=9){c.fillStyle=color;c.font=size+'px -apple-system,"PingFang SC",sans-serif';c.textBaseline='top';c.fillText(t,x,y);}
function slot(c,s,x,y,hover=false){c.fillStyle='#373737';c.fillRect(x,y,18,18);c.fillStyle='#8b8b8b';c.fillRect(x+1,y+1,16,16);c.fillStyle='#c6c6c6';c.fillRect(x+1,y+17,17,1);c.fillRect(x+17,y+1,1,17);if(hover){c.fillStyle='#ffffff40';c.fillRect(x+1,y+1,16,16);}if(!s)return {mark:false,count:null};
 const v=view(s),im=icons[imageKey(s)];c.drawImage(im,x+1,y+1,16,16);
 if(s.glint){const cv=document.createElement('canvas');cv.width=cv.height=16;const a=cv.getContext('2d');a.drawImage(im,0,0);a.globalCompositeOperation='source-atop';a.strokeStyle='#ce8afa80';a.lineWidth=2;for(let d=-16;d<32;d+=7){a.beginPath();a.moveTo(d,16);a.lineTo(d+16,0);a.stroke();}c.drawImage(cv,x+1,y+1);}
 if(s.durability!==null&&!v.returned){c.fillStyle='#000000';c.fillRect(x+3,y+14,13,2);c.fillStyle=s.durability<.15?'#c84e32':'#59b736';c.fillRect(x+3,y+14,Math.max(1,Math.round(13*s.durability)),1);}
 if(s.count>1)digits(c,String(s.count),x+17,y+10);
 if(v.mark)c.drawImage(imageAtlas,48,0,5,5,x,y,5,5);
 return {mark:v.mark,count:s.count>1?s.count:null,uses:v.uses,bar:s.durability,phase:s.phase};
}
function wrap(c,t,max){const out=[];let line='';for(const ch of t){if(c.measureText(line+ch).width>max&&line){out.push(line);line=ch;}else line+=ch;}if(line)out.push(line);return out;}
function tooltip(c,s,x,y,width,language='zh'){if(!s)return {lines:[],height:0,mark:false};const v=view(s),name=v.returned?materialNames[language][s.material]:hostNames[language][s.host],lines=[];let header=null;
 if(v.mark){header=language==='zh'?(v.available?'已融合':'融合记录'):(v.available?'Fused':'Fusion record');const lang=LOCALES[language];let line=lang['fuse.wildcraft.tooltip'];const args=[s.phase==='inactive'?(language==='zh'?'不可用材料':'Unavailable material'):materialNames[language][s.material],String(s.uses)];line=line.replace(/%s/g,()=>args.shift());lines.push({text:line,color:v.low?'#ffc878':'#d7d7d7'});if(!v.available){lines.push({text:lang['fuse.wildcraft.kind.6'],color:'#e69786'});lines.push({text:'othermod:removed_material',color:'#aaa7a7'});}else{lines.push({text:lang['fuse.wildcraft.kind.'+v.kind],color:'#b1b1b1'});if(s.uses===1)lines.push({text:language==='zh'?'剩余最后1次；消耗后解除融合':'Final use; fusion clears when consumed',color:'#ffc878'});}lines.push({text:lang['fuse.wildcraft.controls'].replace('%s','V'),color:'#929292'});
 }else if(v.returned){lines.push({text:language==='zh'?'可再次融合 · 剩余 '+s.uses+' 次':'Reusable material · '+s.uses+' uses left',color:'#d7d7d7'});lines.push({text:language==='zh'?'拆分保留材料的剩余次数':'Splitting preserves remaining uses',color:'#aaa7a7'});}else{lines.push({text:LOCALES[language]['fuse.wildcraft.controls'].replace('%s','V'),color:'#929292'});}
 c.font='9px -apple-system,"PingFang SC",sans-serif';const wrapped=lines.flatMap(row=>wrap(c,row.text,width-16).map(text=>({...row,text})));const height=22+(header?22:0)+wrapped.length*12+6;
 c.fillStyle='#100010f5';c.fillRect(x,y,width,height);c.strokeStyle='#613096';c.strokeRect(x+.5,y+.5,width-1,height-1);txt(c,name,x+8,y+7,'#e8e6da');let yy=y+22;
 if(header){c.drawImage(imageAtlas,32,0,16,16,x+7,yy,16,16);txt(c,header,x+28,yy+3,v.available?'#ddbe84':'#aaa7a7');yy+=22;}
 for(const row of wrapped){txt(c,row.text,x+8,yy,row.color);yy+=12;}
 return {lines:wrapped.map(r=>r.text),height,mark:!!header,uses:v.uses,width,returned:v.returned};
}
function draw(c,s,language='zh',hit=0){c.imageSmoothingEnabled=false;c.clearRect(0,0,384,244);c.fillStyle='#17251d';c.fillRect(0,0,384,244);txt(c,language==='zh'?'物品栏':'Inventory',14,12,'#d3ddcb',11);txt(c,language==='zh'?'悬停说明':'Tooltip',198,4,'#d3ddcb',10);const items=slots(s),rects=[];for(let i=0;i<27;i++){const x=14+i%9*18,y=32+Math.floor(i/9)*18;slot(c,items[i],x,y,i===hit);rects.push({x,y,w:18,h:18});}txt(c,language==='zh'?'快捷栏':'Hotbar',14,110,'#d3ddcb',11);for(let i=0;i<9;i++){if(i===0){c.fillStyle='#d7c387';c.fillRect(12+i*18,130,22,22);}slot(c,items[i],14+i*18,132);}
 txt(c,language==='zh'?'左上：融合标记':'Top left: fused mark',14,173,'#c5ba98');txt(c,language==='zh'?'右下：物品数量':'Bottom right: item count',14,188,'#aaa7a7');txt(c,language==='zh'?'底部：原版宿主耐久':'Bottom: host durability',14,203,'#aaa7a7');const info=tooltip(c,items[hit],198,20,178,language);return {rects,info,hero:view(s),item:items[hit]};}
function render(){if(!ready)return;const s=current(),canvas=el('live'),scale=+el('scale').value;canvas.style.width=384*scale+'px';canvas.style.height=244*scale+'px';const result=draw(canvas.getContext('2d'),s,el('language').value,selected);lastRects=result.rects;window.lastLayout={...result,rects:result.rects,state:s,selected};el('useLabel').textContent=s.uses+' / 32';el('consume').disabled=!['fused'].includes(s.phase);el('description').textContent=s.phase==='inactive'?'这里只检查停用说明。未知材料的回退外观留给下一项 F03-03。':s.phase==='returned'?'材料已拆分，显示保留次数，不显示“已融合”角标。':s.phase==='spent'?'融合已经耗尽，移除角标与融合次数，保留宿主原版耐久和附魔。':'角标只表示融合记录；精确次数在悬停说明读取，不与数量或宿主耐久混用。';}
function set(s){hostDurability=s.durability;el('host').value=s.host;el('material').value=s.material;el('phase').value=s.phase;el('uses').value=s.uses;el('glint').checked=s.glint;selected=0;render();}
function consume(){const s=current();if(s.phase!=='fused')return false;if(s.uses===1){el('phase').value='spent';}else el('uses').value=s.uses-1;selected=0;render();return true;}
async function init(){imageAtlas=new Image();imageAtlas.src=ATLAS;await imageAtlas.decode();const cv=document.createElement('canvas');cv.width=cv.height=16;const vr=new FuseReview.Viewer(cv);for(const h of ['sword','axe','shield','arrow'])for(const m of ['stone','diamond','feather'])for(const f of [true,false]){vr.draw(h,m,'inventory',0,0,false,f);const im=new Image();im.src=cv.toDataURL();await im.decode();icons[h+'-'+m+'-'+(f?'fused':'bare')]=im;}
 for(const mat of ['stone','diamond','feather']){const old=MESH.hosts.sword;MESH.hosts.sword=MESH.materials[mat];vr.draw('sword',mat,'inventory',35,20,false,false);MESH.hosts.sword=old;const im=new Image();im.src=cv.toDataURL();await im.decode();icons['material-'+mat]=im;}
 vr.gl.deleteBuffer(vr.buffer);vr.gl.deleteProgram(vr.program);vr.gl.getExtension('WEBGL_lose_context')?.loseContext();ready=true;render();drawBoard();window.appReady=true;
}
for(const id of ['host','material','phase','uses','scale','language','glint'])el(id).addEventListener('input',()=>{if(id==='host')hostDurability=.7;selected=0;render();});el('consume').onclick=consume;el('reset').onclick=()=>set(fixture());el('live').onpointermove=e=>{const r=el('live').getBoundingClientRect(),x=(e.clientX-r.left)*384/r.width,y=(e.clientY-r.top)*244/r.height,index=lastRects.findIndex(r=>x>=r.x&&x<r.x+r.w&&y>=r.y&&y<r.y+r.h);if(index>=0&&index!==selected){selected=index;render();}};el('live').onkeydown=e=>{const d={ArrowRight:1,ArrowLeft:-1,ArrowDown:9,ArrowUp:-9}[e.key];if(d){e.preventDefault();selected=Math.max(0,Math.min(26,selected+d));render();}};
const examples=[['完整32次',fixture()],['剩余8次',fixture('fused',8,'axe','diamond')],['剩余4次',fixture('fused',4,'shield','feather')],['最后1次',fixture('fused',1,'sword','diamond',{durability:.07})],['普通物品',fixture('unfused')],['耗尽解除',fixture('spent')],['拆分后材料',fixture('returned',8)],['材料不可用',fixture('inactive',8,'axe')],['附魔区域示意',fixture('fused',32,'shield','diamond',{glint:true})]];for(const [label,s]of examples){const b=document.createElement('button');b.textContent=label;b.onclick=()=>set(s);el('samples').append(b);}
function drawBoard(){const c=el('board').getContext('2d');c.imageSmoothingEnabled=false;c.fillStyle='#112119';c.fillRect(0,0,1200,1580);const text=(s,x,y,size=19,color='#e2e9d8')=>txt(c,s,x,y,color,size),panel=(x,y,w,h)=>{c.fillStyle='#23372a';c.fillRect(x,y,w,h);c.strokeStyle='#465743';c.strokeRect(x+.5,y+.5,w-1,h-1);};text('WILDCRAFT / F03-02',30,25,15,'#b5c799');text('融合标记与剩余次数',30,57,32);text('v01 · 原16/32符号复用 / 原生5px槽位角标 / 精确次数使用文字 / 草稿待审',30,108,18,'#e0b879');
 for(const [name,region,x,zoom]of [['32×32 原符号',[0,0,32,32],30,5],['16×16 原符号',[32,0,16,16],420,10],['5×5 槽位角标',[48,0,5,5],810,24]]){panel(x,145,360,230);text(name,x+20,160,22);c.drawImage(imageAtlas,...region,x+25,202,region[2]*zoom,region[3]*zoom);text(name.startsWith('5')?'逐像素简化':'原像素不改动',x+205,230,16,'#b9c8ae');text(name.startsWith('5')?'保留中央连接':'保留金属连接环',x+205,257,16,'#b9c8ae');}
 text('18×18 原生槽位 · 角标 / 数量 / 原版耐久分开',30,400,22,'#e0b879');const tests=[fixture(),fixture('fused',8,'axe','diamond'),fixture('fused',4,'shield','feather'),fixture('fused',1,'arrow','feather'),fixture('unfused',32,'arrow','feather',{count:64}),fixture('returned',8)];for(let i=0;i<6;i++){const x=35+i*190;const temp=document.createElement('canvas');temp.width=temp.height=18;slot(temp.getContext('2d'),tests[i],0,0);c.drawImage(temp,x,443,108,108);text(['已融合32','已融合8','已融合4','融合箭1','普通箭×64','材料余8'][i],x,563,18);}
 text('悬停读数 · 32 / 8 / 4 / 1（悬停说明示意）',30,610,22,'#e0b879');for(let i=0;i<4;i++){const x=30+i*292;panel(x,650,274,326);const cv=document.createElement('canvas');cv.width=128;cv.height=220;tooltip(cv.getContext('2d'),tests[i],0,0,128,'zh');c.drawImage(cv,x+9,663,256,440);}
 text('耗尽 / 拆分 / 材料不可用',30,1006,22,'#e0b879');for(let i=0;i<3;i++){const x=30+i*390;panel(x,1050,360,375);const s=[fixture('spent'),fixture('returned',8),fixture('inactive',8,'axe')][i],cv=document.createElement('canvas');cv.width=178;cv.height=190;const info=tooltip(cv.getContext('2d'),s,0,0,178,'zh');c.drawImage(cv,x+2,1065,356,380);text(['角标移除，回到宿主','材料保留8次，不标已融合','数据保留，效果停用'][i],x+12,1398,18,'#c2d0b4');}
 text('共享64×32图集 · 3个区域 · 数字与说明不烘焙 · 新增角标1个',30,1460,23);text('物品轮廓为已采用F03-01参考；字体／附魔区域为审稿模拟；真实游戏渲染待接入复核。',30,1504,18,'#b5c6ad');text('本项没有新增融合界面；未知材料回退外观与融合特效分别留给F03-03、F03-04。',30,1545,18,'#b5c6ad');window.boardReady=true;
}
window.statusReview={fixture,view,slot,tooltip,draw,set,current,consume,icons:()=>icons,slotLayout:SLOT};init().catch(e=>{window.appError=String(e);console.error(e);});
