package dev.wildcraft.test;

import dev.wildcraft.fuse.*;
import dev.wildcraft.client.fuse.FusionPresentation;
import dev.wildcraft.equipment.BackEquipment;
import java.util.Set;
import java.util.List;
import net.fabricmc.fabric.api.client.gametest.v1.FabricClientGameTest;
import net.fabricmc.fabric.api.client.gametest.v1.context.*;
import net.fabricmc.fabric.api.client.gametest.v1.world.TestWorldSave;
import net.minecraft.core.*;
import net.minecraft.core.component.DataComponents;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.entity.projectile.arrow.AbstractArrow;
import net.minecraft.world.inventory.ContainerInput;
import net.minecraft.world.item.*;
import net.minecraft.world.item.component.ItemContainerContents;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.*;

/** Native key, attack, container, drop, pickup, disk reload and bow packets. */
public final class FusionClientSmokeTest implements FabricClientGameTest{
    private static final BlockPos CHEST=new BlockPos(2,120,2);
    @Override public void runTest(ClientGameTestContext c){
        ItemStack[] original={ItemStack.EMPTY};FusionData[] saved={null};TestWorldSave save;
        try(TestSingleplayerContext world=c.worldBuilder().create()){
            world.getConnection().waitForChunksRender();world.getServer().runCommand("gamemode survival @p");
            world.getServer().runOnServer(server -> {var level=server.overworld();var p=server.getPlayerList().getPlayers().getFirst();for(int x=-5;x<=5;x++)for(int z=-5;z<=35;z++)level.setBlockAndUpdate(new BlockPos(x,119,z),Blocks.STONE.defaultBlockState());level.setBlockAndUpdate(CHEST,Blocks.CHEST.defaultBlockState());p.teleportTo(level,.5,120,.5,Set.of(),0,0,false);p.getInventory().clearContent();var host=new ItemStack(Items.IRON_SWORD);host.setDamageValue(17);host.set(DataComponents.CUSTOM_NAME,net.minecraft.network.chat.Component.literal("P9 blade"));p.getInventory().setItem(0,host);p.getInventory().setItem(1,new ItemStack(Items.BOW));var tool=new ItemStack(Items.DIAMOND_PICKAXE);tool.setDamageValue(123);tool.set(DataComponents.CUSTOM_NAME,net.minecraft.network.chat.Component.literal("private nested tool"));var mat=new ItemStack(Items.SHULKER_BOX);mat.set(DataComponents.CONTAINER,ItemContainerContents.fromItems(List.of(tool,new ItemStack(Items.DIAMOND,3))));original[0]=mat.copy();p.setItemInHand(InteractionHand.OFF_HAND,mat);p.getInventory().setSelectedSlot(0);p.inventoryMenu.broadcastChanges();var mob=net.minecraft.world.entity.EntityTypes.VILLAGER.create(level,net.minecraft.world.entity.EntitySpawnReason.COMMAND);mob.setNoAi(true);mob.setPos(.5,120,2.5);level.addFreshEntity(mob);});
            c.runOnClient(client -> client.options.setCameraType(net.minecraft.client.CameraType.FIRST_PERSON));c.waitFor(client -> client.player.getOffhandItem().is(Items.SHULKER_BOX));key(c,false);
            c.waitFor(client -> client.player.getMainHandItem().has(FusionContent.VIEW)&&client.player.getOffhandItem().isEmpty());
            check(c.computeOnClient(client -> client.player.getMainHandItem().get(FusionContent.DATA).isProjection()&&client.player.getMainHandItem().get(FusionContent.DATA).rawMaterial().isEmpty()),"Actual inventory client receives no private nested material");
            key(c,false);c.waitTicks(5);world.getServer().runOnServer(server -> {var p=server.getPlayerList().getPlayers().getFirst();check(p.getMainHandItem().get(FusionContent.DATA).remaining()==32&&ItemStack.matches(original[0],p.getMainHandItem().get(FusionContent.DATA).material(p.registryAccess()).orElseThrow()),"Native replay does not consume twice and exact material remains server-owned");});c.takeScreenshot("p9-native-fused-hand");
            c.getInput().holdKeyFor(o -> o.keyInventory,1);c.waitFor(client -> client.gui.screen() instanceof net.minecraft.client.gui.screens.inventory.InventoryScreen);c.takeScreenshot("p9-native-fused-inventory");c.runOnClient(client -> client.player.closeContainer());c.waitFor(client -> client.gui.screen()==null);
            aim(c,new Vec3(.5,121,2.5));c.waitFor(client -> client.hitResult instanceof EntityHitResult);c.waitTicks(20);c.getInput().holdKeyFor(o -> o.keyAttack,1);c.waitFor(client -> client.player.getMainHandItem().get(FusionContent.VIEW).uses()==31);
            select(c,1);c.runOnClient(client -> client.options.setCameraType(net.minecraft.client.CameraType.THIRD_PERSON_BACK));c.waitFor(client -> BackEquipment.view(client.player).melee().has(FusionContent.VIEW));check(c.computeOnClient(client -> !BackEquipment.view(client.player).melee().has(FusionContent.DATA)),"Back tracking exposes only fusion view, not restoration snapshot");c.takeScreenshot("p9-native-fused-back");select(c,0);c.runOnClient(client -> client.options.setCameraType(net.minecraft.client.CameraType.FIRST_PERSON));openChest(c);shift(c,54);c.waitFor(client -> client.player.getInventory().getItem(0).isEmpty());c.waitTicks(5);
            world.getServer().runOnServer(server -> {var box=(net.minecraft.world.level.block.entity.ChestBlockEntity)server.overworld().getBlockEntity(CHEST);saved[0]=box.getItem(0).get(FusionContent.DATA);check(saved[0]!=null&&saved[0].remaining()==31,"Real chest transaction retains one paid material and remaining uses");});c.takeScreenshot("p9-native-fused-chest");c.runOnClient(client -> client.player.closeContainer());c.waitFor(client -> client.gui.screen()==null);save=world.getWorldSave();
        }
        try(TestSingleplayerContext world=save.open()){
            world.getConnection().waitForChunksRender();world.getServer().runOnServer(server -> {var box=(net.minecraft.world.level.block.entity.ChestBlockEntity)server.overworld().getBlockEntity(CHEST);check(saved[0].equals(box.getItem(0).get(FusionContent.DATA)),"Actual disk reload preserves exact raw material and charges");});openChest(c);shift(c,0);c.waitFor(client -> client.player.containerMenu.getSlot(0).getItem().isEmpty());c.waitTicks(5);c.runOnClient(client -> client.player.closeContainer());c.waitFor(client -> client.gui.screen()==null);
            world.getServer().runOnServer(server -> {var p=server.getPlayerList().getPlayers().getFirst();int slot=java.util.stream.IntStream.range(0,36).filter(i -> p.getInventory().getItem(i).has(FusionContent.DATA)).findFirst().orElseThrow();var actual=p.getInventory().removeItemNoUpdate(slot);p.getInventory().setItem(0,actual);for(int n=1;n<36;n++)p.getInventory().setItem(n,new ItemStack(Items.STONE,64));p.setItemInHand(InteractionHand.OFF_HAND,new ItemStack(Items.STONE,64));p.getInventory().setSelectedSlot(0);p.inventoryMenu.broadcastChanges();});select(c,0);c.waitFor(client -> client.player.getMainHandItem().has(FusionContent.VIEW));key(c,true);c.waitTicks(5);check(c.computeOnClient(client -> client.player.getMainHandItem().has(FusionContent.VIEW)),"Native full split refuses without losing material");
            world.getServer().runOnServer(server -> {var p=server.getPlayerList().getPlayers().getFirst();p.getInventory().setItem(5,ItemStack.EMPTY);p.inventoryMenu.broadcastChanges();});c.waitTicks(5);key(c,true);c.waitFor(client -> !client.player.getMainHandItem().has(FusionContent.VIEW)&&client.player.getInventory().getItem(5).is(Items.SHULKER_BOX));world.getServer().runOnServer(server -> {var p=server.getPlayerList().getPlayers().getFirst();var recovered=p.getInventory().getItem(5);check(recovered.get(FusionContent.WEAR)==31&&recovered.get(DataComponents.CONTAINER).equals(original[0].get(DataComponents.CONTAINER)),"Recovered actual private box contents plus remaining wear, no refill");p.setItemInHand(InteractionHand.OFF_HAND,p.getInventory().removeItemNoUpdate(5));p.inventoryMenu.broadcastChanges();});c.takeScreenshot("p9-native-split-material");c.waitTicks(5);key(c,false);c.waitFor(client -> client.player.getMainHandItem().has(FusionContent.VIEW)&&client.player.getMainHandItem().get(FusionContent.VIEW).uses()==31);
            c.getInput().holdKeyFor(o -> o.keyDrop,1);c.waitFor(client -> client.player.getMainHandItem().isEmpty()&&client.level.getEntitiesOfClass(ItemEntity.class,new AABB(-5,119,-5,5,123,5)).stream().anyMatch(e -> e.getItem().has(FusionContent.VIEW)));c.waitTicks(5);
            world.getServer().runOnServer(server -> {var level=server.overworld();var drops=level.getEntitiesOfClass(ItemEntity.class,new AABB(-5,119,-5,5,123,5));check(drops.size()==1&&drops.getFirst().getItem().get(FusionContent.DATA).remaining()==31,"Actual dropped entity owns one full fusion");var p=server.getPlayerList().getPlayers().getFirst();var point=drops.getFirst().position();p.teleportTo(level,point.x,point.y,point.z,Set.of(),0,0,false);});c.waitTicks(30);c.waitFor(client -> java.util.stream.IntStream.range(0,36).anyMatch(i -> client.player.getInventory().getItem(i).has(FusionContent.VIEW)));
            world.getServer().runOnServer(server -> {var p=server.getPlayerList().getPlayers().getFirst();long count=java.util.stream.IntStream.range(0,36).filter(i -> p.getInventory().getItem(i).has(FusionContent.DATA)).count();check(count==1,"Native pickup returns one host, no second material");p.getInventory().clearContent();for(var previous:server.overworld().getEntitiesOfClass(net.minecraft.world.entity.npc.villager.Villager.class,new AABB(-1,119,1,2,123,4)))previous.discard();p.teleportTo(server.overworld(),.5,120,.5,Set.of(),0,0,false);p.getInventory().setItem(0,new ItemStack(Items.ARROW,4));var bow=new ItemStack(Items.BOW);net.minecraft.world.item.enchantment.EnchantmentHelper.updateEnchantments(bow,e -> e.set(p.registryAccess().lookupOrThrow(net.minecraft.core.registries.Registries.ENCHANTMENT).getOrThrow(net.minecraft.world.item.enchantment.Enchantments.INFINITY),1));p.getInventory().setItem(2,bow);p.setItemInHand(InteractionHand.OFF_HAND,new ItemStack(Items.BLAZE_POWDER,2));p.getInventory().setSelectedSlot(0);p.inventoryMenu.broadcastChanges();var mob=net.minecraft.world.entity.EntityTypes.VILLAGER.create(server.overworld(),net.minecraft.world.entity.EntitySpawnReason.COMMAND);mob.setNoAi(true);mob.setPos(.5,120,30.5);server.overworld().addFreshEntity(mob);});select(c,0);c.waitFor(client -> client.player.getMainHandItem().is(Items.ARROW));key(c,false);c.waitFor(client -> client.player.getMainHandItem().has(FusionContent.VIEW)&&client.player.getMainHandItem().getCount()==1);select(c,2);c.waitFor(client -> client.player.getMainHandItem().is(Items.BOW));aim(c,new Vec3(.5,123,30.5));c.getInput().holdKeyFor(o -> o.keyUse,25);
            c.waitFor(client -> client.level.getEntitiesOfClass(AbstractArrow.class,new AABB(-5,119,-5,5,124,35)).stream().anyMatch(a -> a.getAttached(FusionCombat.ARROW_VIEW)!=null));c.takeScreenshot("p9-native-fused-arrow-flight");c.waitTicks(20);world.getServer().runOnServer(server -> {var p=server.getPlayerList().getPlayers().getFirst();check(!p.getInventory().getItem(0).has(FusionContent.DATA)&&p.getInventory().getItem(1).getCount()==3&&p.getOffhandItem().getCount()==1,"Actual Infinity bow consumes fused arrow once; normal remainder and material remain exact");var targets=server.overworld().getEntitiesOfClass(net.minecraft.world.entity.npc.villager.Villager.class,new AABB(-1,119,28,2,123,33));check(targets.size()==1&&targets.getFirst().isOnFire(),"Native bow projectile applies actual flame impact");});c.takeScreenshot("p9-native-infinity-arrow-impact");
        }
        System.out.println("WILDCRAFT P9 native V/sneak split, replay, private projection, actual attack/back, native chest hash transaction, disk reload, full inventory, worn material, drop/pickup and Infinity arrow once passed");
    }
    static void key(ClientGameTestContext c,boolean split){if(split)c.getInput().holdKey(o -> o.keyShift);c.getInput().holdKeyFor(FusionPresentation.FUSE,1);if(split)c.getInput().releaseKey(o -> o.keyShift);c.waitTicks(5);}
    static void select(ClientGameTestContext c,int slot){c.runOnClient(client -> client.player.getInventory().setSelectedSlot(slot));c.waitTicks(3);}
    static void aim(ClientGameTestContext c,Vec3 point){c.runOnClient(client -> {var delta=point.subtract(client.player.getEyePosition());client.player.setYRot((float)Math.toDegrees(Math.atan2(-delta.x,delta.z)));client.player.setXRot((float)-Math.toDegrees(Math.atan2(delta.y,Math.sqrt(delta.horizontalDistanceSqr()))));});c.waitTicks(4);}
    static void openChest(ClientGameTestContext c){aim(c,Vec3.atCenterOf(CHEST));c.runOnClient(client -> client.gameMode.useItemOn(client.player,InteractionHand.MAIN_HAND,new BlockHitResult(Vec3.atCenterOf(CHEST),Direction.NORTH,CHEST,false)));c.waitFor(client -> client.gui.screen() instanceof net.minecraft.client.gui.screens.inventory.ContainerScreen);}
    static void shift(ClientGameTestContext c,int slot){c.runOnClient(client -> client.gameMode.handleContainerInput(client.player.containerMenu.containerId,slot,0,ContainerInput.QUICK_MOVE,client.player));}
    static void check(boolean ok,String text){if(!ok)throw new AssertionError(text);}
}
