from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1]
def read(p):return json.loads((R/p).read_text())
data=dict(G=read('references/F05-05-geometry-and-uv.json'),F=read('references/F05-03-geometry-and-uv.json'),scenes=read('source/review-scenarios.json'),regions=read('references/F04-02-energy-regions.json')['regions'],glyphs=read('source/status-glyphs.json')['glyphs'])
images={}
for key,name in [('atlas','F05-01-machine-atlas-64.png'),('empty16','F04-02-battery-empty-16.png'),('full16','F04-02-battery-full-16.png'),('empty32','F04-02-battery-empty-32.png'),('full32','F04-02-battery-full-32.png')]:images[key]='data:image/png;base64,'+base64.b64encode((R/'references'/name).read_bytes()).decode()
html=r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · 安装预览与机械提示</title><style>
*{box-sizing:border-box}body{margin:0;background:#15251c;color:#e4e9dc;font:15px/1.75 system-ui,"PingFang SC",sans-serif}main{max-width:1220px;margin:auto;padding:28px 22px}h1{font-size:30px;margin:8px 0}h2{font-size:20px;margin:0 0 12px}p{color:#b6c5af}.tag,.note{color:#dfb877}.controls,.panel{background:#263a2b;border:1px solid #486348;padding:16px;border-radius:6px}.controls{display:flex;gap:16px;flex-wrap:wrap}label{display:flex;align-items:center;gap:7px}select,input{background:#192a20;color:#e4e9dc;border:1px solid #64795c;padding:6px;accent-color:#bf7450}input[type=range]{width:140px}button{cursor:pointer;background:#314a35;color:#e4e9dc;border:1px solid #64795c;padding:8px 12px;border-radius:4px}:focus-visible{outline:3px solid #dfb877;outline-offset:3px}.poses{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.row{display:grid;grid-template-columns:1.55fr 1fr;gap:20px;margin:18px 0}.small{font-size:13px;color:#a8bc9f}#screen{width:100%;height:auto;image-rendering:pixelated;background:#18241c}.labels{display:flex;gap:10px;flex-wrap:wrap}.labels span{padding:3px 10px;border:1px solid #64795c}.ready{color:#93e8c0}.blocked{color:#deab7a}.board{width:100%;height:auto}dl{margin:0}dt{color:#a8bc9f;margin-top:12px}dd{margin:3px 0;color:#e4e9dc}.statebox{border-left:3px solid #deab7a;padding-left:12px}#trace{font-size:13px;line-height:1.8}@media(max-width:960px){.row{grid-template-columns:1fr}main{padding:20px 14px}}
</style><main><span class="tag">F05-10 · v01 · 草稿待审 · 未接入游戏</span><h1>安装位置看得清 · 机械状态读得准</h1><p>绿色透明部件表示本地位置候选；琥珀色标记说明占用或停机条件。轮廓、符号和文字共同表达，右键安装与回收仍以服务器结果为准。沿用已采用的主体、风扇、电池与电量图标。</p>
<div class="controls"><label>审稿场景<select id="scenario"></select></label><label>本地节点<select id="node"><option value="0">顶</option><option value="1">底</option><option value="2">后</option><option value="3" selected>前</option><option value="4">左</option><option value="5">右</option></select></label><label>显示尺寸<select id="size"><option value="640,360">640 × 360</option><option value="320,240">320 × 240 · 紧凑</option><option value="960,540">960 × 540</option></select></label><label>语言<select id="lang"><option value="zh">中文</option><option value="en">English</option></select></label><label>启停键<select id="key"><option>R</option><option>J</option></select></label><label><input type="checkbox" id="gray">灰阶查看</label><label>动作定格<input id="age" type="range" min="0" max="90" step="1" value="0"></label><button id="play">播放叶轮</button></div>
<div class="poses"><button id="iso">斜侧面</button><button id="face">节点正面</button><button id="back">从背面看遮挡</button><button id="top">顶面</button><button id="bottom">底面</button></div>
<div class="row"><section class="panel"><h2>实际部件几何 + HUD布局</h2><canvas id="screen" width="640" height="360" role="img" aria-label="安装透明预览和机械状态HUD"></canvas><p id="reading" aria-live="polite"></p><p class="small">场景和下拉控件用于美术审稿。生命、精力与快捷栏仅作位置示意；字体在浏览器近似，游戏接入使用原版字体。火箭/弹簧本轮先核验读数，外观在B3补齐。</p></section><section class="panel"><h2>当前状态说明</h2><div class="labels"><span class="ready">✓ 位置可用</span><span class="blocked">× 条件不满足</span><span>□ 停机</span><span class="ready">▶ 工作</span><span class="blocked">Ⅱ 等待</span></div><dl id="trace"></dl><p class="note">有电不等于正在工作，开机不等于叶轮转动。低电量不等于空电。无电池显示“— / 1000”，与已空电池“0 / 1000”分开。</p><p class="small">安装预览不预测服务器的所有权、真实射线或库存结果；拒绝原因按实际反馈说明。本轮不改碰撞、点击范围或能源规则。</p></section></div>
<section class="panel"><h2>统一表达</h2><div class="statebox"><p>位置可用：绿色半透明的同一部件，保持原尺度与安装朝向；电池窗口按手持余量显示。预览风扇保持静止。</p><p>条件不满足：不绘制额外幽灵部件，保留原占用件，用琥珀色角标、叉号和文字说明原因。</p><p>状态读数：机械是否启用与实际工作分别判断。火箭显示真实剩余燃料刻数，弹簧显示真实冷却刻数；不猜测新充满燃料或已经复位。</p></div></section><p class="note">代表件验证范围为主体、风扇和电池。其余六类部件完成后，按同一透明渲染与HUD规范复核。</p><canvas id="board" class="board" width="1200" height="1890"></canvas><canvas id="world" width="640" height="450" hidden></canvas></main>
<script>__JS__</script><script>
const DATA=__DATA__,G=DATA.G,F=DATA.F,scenes=DATA.scenes,regions=DATA.regions,glyphs=DATA.glyphs,sources=__IMAGES__,assets={},M=WildcraftMachinePresentation,$=id=>document.getElementById(id);let yaw=-25,pitch=24,playing=false,raf=0,start=0,initialAge=0;
function current(){return M.withNode(scenes.find(s=>s.id===$('scenario').value),+$('node').value)}
function update(age=+$('age').value){const s=current(),lang=$('lang').value,key=$('key').value,gray=$('gray').checked,[w,h]=$('size').value.split(',').map(Number),world=M.drawWorld($('world'),assets.atlas,G,F,s,age,yaw,pitch,gray),hud=M.drawScreen($('screen'),$('world'),s,assets,regions,glyphs,w,h,lang,key,gray),p=M.present(s,lang,key);$('screen').style.filter=gray?'grayscale(1)':'';$('reading').textContent=s.title+' · '+(p.visible?p.detail+' · '+p.number:'界面开启，机械提示隐藏');let entries=[['安装位置',p.ghost?'同一部件透明预览 · 比例1.00':p.blocked||'不显示安装预览'],['机械状态',p.statusLabel],['电量',p.number+(p.energyLabel?' · '+p.energyLabel:'')],['节点读数',p.extra||'当前节点无独立燃料/冷却读数'],['操作提示',p.hint]];$('trace').replaceChildren(...entries.flatMap(([k,v])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;return [dt,dd]}));window.currentState={scenario:s.id,snapshot:s,presentation:p,world,hud,w,h,age,yaw,pitch,gray,lang,key,playing};}
function pause(){playing=false;cancelAnimationFrame(raf);$('play').textContent='播放叶轮';update()}
function frame(t){if(!playing)return;const age=initialAge+(t-start)/50;$('age').value=Math.floor(age)%91;update(age);raf=requestAnimationFrame(frame)}
function board(){const board=$('board'),c=board.getContext('2d');c.fillStyle='#15251c';c.fillRect(0,0,1200,1890);const text=(s,x,y,z=18,col='#e4e9dc')=>{c.font=z+'px system-ui,"PingFang SC"';c.fillStyle=col;c.textBaseline='top';c.fillText(s,x,y)};const box=(x,y,w,h)=>{c.fillStyle='#263a2b';c.fillRect(x,y,w,h);c.strokeStyle='#486348';c.strokeRect(x+.5,y+.5,w-1,h-1)};text('WILDCRAFT / INSTALL PREVIEW & MACHINE STATUS',30,24,16,'#a7bc9d');text('安装位置看得清 · 机械状态读得准',30,58,32);text('F05-10 v01 · 草稿待审 · 代表件实际几何 / 复用电量图标 · 未接入',30,108,17,'#dfb877');const screen=document.createElement('canvas'),world=document.createElement('canvas');['fan-ready','battery-ready','occupied','enabled-blocked','stopped','running'].forEach((id,i)=>{const s=scenes.find(s=>s.id===id),x=30+i%2*585,y=154+Math.floor(i/2)*386;box(x,y,555,365);text(s.title,x+15,y+14,21);M.drawWorld(world,assets.atlas,G,F,s,id==='running'?4:0,-25,24);M.drawScreen(screen,world,s,assets,regions,glyphs,640,360);c.drawImage(screen,x+8,y+54,539,303)});text('非仅颜色 · 原尺度透明预览 · 阻挡时不叠加幽灵件',30,1335,24);text('✓ 位置可用　× 条件不满足　□ 停机　▶ 工作　Ⅱ 等待',30,1380,21,'#dfb877');
['no-battery','depleted','rocket-fuel','spring-cooldown'].forEach((id,i)=>{const s=scenes.find(s=>s.id===id),x=30+i%2*585,y=1433+Math.floor(i/2)*153;box(x,y,555,139);text(s.title,x+15,y+10,18);const cn=document.createElement('canvas');cn.width=555;cn.height=210;const ctx=cn.getContext('2d');const info=M.drawHud(ctx,s,assets,regions,glyphs,555,210);c.drawImage(cn,0,info.rect.y-4,555,info.rect.height+8,x,y+37,555,info.rect.height+8)});text('电量/燃料/冷却读取真实状态；预览风扇静止，工作风扇按节点工作位转动。',30,1763,18);text('HUD居中置于快捷栏上方，按可用宽度换行；启停键取真实绑定。',30,1801,18);text('火箭与弹簧本项只复核数值布局；B3完成后做全八类部件外观复核。',30,1845,17,'#dfb877');}
window.ready=(async()=>{await Promise.all(Object.entries(sources).map(async([k,src])=>{let im=new Image();im.src=src;await im.decode();assets[k]=im}));$('scenario').innerHTML=scenes.map(s=>'<option value="'+s.id+'">'+s.title+'</option>').join('');for(const id of ['scenario','node','size','lang','key','gray'])$(id).onchange=()=>{pause();update()};$('age').oninput=()=>{pause();update()};$('play').onclick=()=>{if(playing)pause();else{playing=true;initialAge=+$('age').value;start=performance.now();$('play').textContent='暂停';raf=requestAnimationFrame(frame)}};$('iso').onclick=()=>{yaw=-25;pitch=24;update()};$('face').onclick=()=>{[yaw,pitch]=[[0,75],[0,-75],[180,0],[0,0],[90,0],[-90,0]][+$('node').value];update()};$('back').onclick=()=>{[yaw,pitch]=[[180,-75],[180,75],[0,0],[180,0],[-90,0],[90,0]][+$('node').value];update()};$('top').onclick=()=>{yaw=0;pitch=85;update()};$('bottom').onclick=()=>{yaw=-25;pitch=-65;update()};update();board();window.appReady=true;return true})();
</script></html>'''
(R/'review/preview.html').write_text(html.replace('__JS__',(R/'source/machine-presentation.js').read_text()).replace('__DATA__',json.dumps(data)).replace('__IMAGES__',json.dumps(images)))
print('Self-contained representative geometry / transparent preview / 18-state HUD review created.')
