from pathlib import Path
import json,base64,subprocess,html
import numpy as np
R=Path(__file__).resolve().parents[1]
D=json.loads((R/'source/sound-design.json').read_text());C=D['cues']
def waveform(id):
    data=subprocess.check_output([D['ffmpeg'],'-v','error','-i',str(R/'source/masters'/f'{id}.wav'),'-f','f32le','pipe:1'])
    x=np.frombuffer(data,dtype='<f4');bins=np.array_split(x,240);scale=30/max(np.abs(x));points=[]
    for i,b in enumerate(bins):points.extend([f'{i*2:.1f},{35-float(np.max(b))*scale:.1f}',f'{i*2:.1f},{35-float(np.min(b))*scale:.1f}'])
    return '<svg viewBox="0 0 480 70" role="img" aria-label="'+id+' 波形，每条独立归一显示"><path d="M0 35H480" stroke="#31463f"/><polyline points="'+' '.join(points)+'" fill="none" stroke="#aec5b1" stroke-width="1"/></svg>'
cards=[]
for c in C:
    esc=html.escape
    cards.append(f'''<article data-card="{c['id']}"><div class="cardTop"><span>{c['index']:02d} · {c['group']}</span><span>{c['seconds']:.2f}s</span></div><h2>{c['title']}</h2><p>{c['description']}</p>{waveform(c['id'])}<button data-play="{c['id']}" aria-label="试听：{c['title']}">▶ 试听</button><details><summary>用途与触发点</summary><p>{esc(c['trigger'])}</p><p>{esc(c['exclude'])}</p><small>建议音量 {c['gameVolume']} / 距离 {c['maxDistance']} 格 · 尚待游戏混音验证</small></details></article>''')
A={c['id']:base64.b64encode((R/'exports/sounds'/f"{c['id']}.ogg").read_bytes()).decode() for c in C}
for id in ['focus_enter','focus_exit']:A[id]=base64.b64encode((R/'references'/f'{id}.ogg').read_bytes()).decode()
css='''*{box-sizing:border-box}body{margin:0;background:#111916;color:#e5e9de;font:16px/1.6 system-ui,-apple-system,sans-serif}main{max-width:1180px;padding:48px 32px;margin:auto}h1{font-size:36px;line-height:1.2;margin:12px 0 16px}h2{font-size:21px;margin:10px 0}h3{font-size:20px}p{color:#bbc6ba}a{color:#d6b983}small{color:#a5b4a8}.eyebrow{color:#d0b27a;letter-spacing:2px;font-size:13px}.toolbar{position:sticky;top:0;background:#17211df5;z-index:2;border:1px solid #405045;padding:16px;border-radius:10px;display:flex;flex-wrap:wrap;gap:12px;align-items:center}button,select{font:inherit;border:1px solid #66715c;background:#26382f;color:#e9eee2;border-radius:6px;padding:9px 16px;cursor:pointer}button:hover{background:#3c5142}button:focus-visible,select:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid #dfbd7d;outline-offset:3px}button.primary{background:#b79b64;color:#172018;border-color:#b79b64;font-weight:650}label{display:flex;gap:10px;align-items:center}input{max-width:140px;accent-color:#d0b27a}#status{width:100%;font-size:14px;color:#d6b983;min-height:23px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin:26px 0}article{border:1px solid #394b3f;border-radius:10px;padding:20px;background:#19231e;min-width:0}.cardTop{display:flex;justify-content:space-between;color:#a9bcaa;font-size:13px}article p{font-size:14px;min-height:45px}article svg{display:block;width:100%;height:56px;margin:12px 0}article.playing{border-color:#dab578;background:#27372d}details{margin-top:12px;font-size:14px}summary{cursor:pointer;color:#bbc8b7}section{border-top:1px solid #394b3f;margin-top:30px;padding-top:14px}pre{white-space:pre-wrap;color:#bbccbb;background:#17211b;padding:16px;border-radius:8px;font-size:13px;min-height:80px}.controls{display:flex;align-items:center;flex-wrap:wrap;gap:12px}.note{font-size:14px;max-width:850px}footer{margin-top:32px;color:#a2b09f;font-size:13px}@media(max-width:850px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:540px){main{padding:24px 16px}.grid{grid-template-columns:1fr}h1{font-size:28px}.toolbar{position:static}label{flex-wrap:wrap}.controls{align-items:flex-start;flex-direction:column}}'''
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>S01 Wildcraft 音效审稿 v01</title><style>'''+css+'''</style><main><div class="eyebrow">WILDCRAFT / S01 / v01 · 待试听采用</div><h1>短音，让动作有材质</h1><p>料理的陶木、能源的铜接点、机械的轴与锁扣。12 个原创短音，0 个持续循环。先逐个辨认，再听叠加参考。</p><div class="toolbar"><button id="all" class="primary">▶ 整组顺序试听</button><button id="stop">■ 停止全部</button><label for="volume">试听音量 <input type="range" id="volume" min="0" max="1" step="0.01" value="0.5"><output id="volumeLabel">50%</output></label><div id="status" role="status" aria-live="polite">点击后播放；页面离开会停止试听。</div></div><p class="note">单音播放母带相对响度的 OGG 导出。各波形独立归一显示，不能按图比较响度。下方叠加使用建议游戏音量和参考距离衰减，不是游戏录音。</p><div class="grid">'''+''.join(cards)+'''</div><section><h3>多台与距离参考</h3><div class="controls"><label for="scene">场景 <select id="scene"><option value="four">四台机械同时启动</option><option value="dense">八个混合事件，最多六声</option></select></label><label for="distance">距离 <input id="distance" type="range" min="0" max="14" step="1" value="2"><output id="distanceLabel">2 格</output></label><button id="simulate">▶ 试听叠加参考</button><button id="unload">模拟来源卸载</button></div><pre id="log">同一事件最多两声，同一来源最多一声，全场最多六声；高优先级声音可替换低优先级声音。裁掉的声音不排队补播。</pre></section><section><h3>已采用专注音参考</h3><p class="note">以下两段是已有音效的原字节副本，仅供音色对照。单独试听不代表已经通过全游戏混音验证，A13-C 保留后续复核。</p><div class="controls"><button data-play="focus_enter">▶ 原专注进入</button><button data-play="focus_exit">▶ 原专注退出</button></div></section><footer>交付：12 OGG / 12 单声道 PCM24 WAV 母带 / 36 可编辑分层 WAV / 参数与渲染工程 / 事件及播放规范。当前为审稿，未采用、未接入游戏。声音由原创程序化共鸣和噪声合成，不使用外部采样。</footer></main><script>const DESIGN='''+json.dumps(D,ensure_ascii=False)+''';const AUDIO='''+json.dumps(A)+''';\n'''+(R/'source/audio-policy.js').read_text()+'\n'+(R/'source/audio-review.js').read_text()+'</script></html>'
(R/'review/preview.html').write_text(page)
print(json.dumps({'selfContainedReviewBytes':len(page.encode()),'embeddedOgg':len(A),'originalCues':12}))
