const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const R=path.resolve(__dirname,'..');const sandbox={module:{exports:{}}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'audio-policy.js'),'utf8'),sandbox);
const {SoundBudget}=sandbox.module.exports;const checks=[];
const event=(x={})=>({id:'start',source:'a',dimension:'overworld',operation:'one',confirmed:true,distance:2,limit:10,seconds:.3,volume:.3,priority:2,...x});
const test=(name,fn)=>{fn();checks.push({name,passed:true});};
test('unconfirmed transaction rejected',()=>assert(!new SoundBudget().accept(event({confirmed:false})).accepted));
test('confirmed first operation accepted',()=>assert(new SoundBudget().accept(event()).accepted));
test('duplicate packet cannot replay even after original voice ended',()=>{const b=new SoundBudget();b.accept(event());assert(!b.accept(event(),450).accepted);});
test('different dimension uses different source identity',()=>{const b=new SoundBudget();b.accept(event());assert(b.accept(event({dimension:'nether'})).accepted);});
test('reset on reconnect permits future operations',()=>{const b=new SoundBudget();b.accept(event());b.reset();assert(b.accept(event()).accepted);});
for(const d of [-1,10,11,NaN,Infinity])test('reject distance '+String(d),()=>assert(!new SoundBudget().accept(event({distance:d})).accepted));
test('distance falloff is actual volume times linear factor',()=>assert(Math.abs(new SoundBudget().accept(event()).gain-.24)<1e-10));
test('two identical nearby machine starts maximum',()=>{const b=new SoundBudget();for(let i=0;i<4;i++)b.accept(event({source:'s'+i,operation:i}));assert.equal(b.voices.length,2);});
test('six mixed voices maximum and low priority dropped',()=>{const b=new SoundBudget();for(let i=0;i<6;i++)assert(b.accept(event({id:'e'+i,source:'s'+i})).accepted);assert(!b.accept(event({id:'seven',source:'seven'})).accepted);assert.equal(b.voices.length,6);});
test('priority completion replaces oldest low priority',()=>{const b=new SoundBudget();for(let i=0;i<6;i++)b.accept(event({id:'e'+i,source:'s'+i}),i);assert.equal(b.accept(event({id:'complete',source:'other',priority:3}),10).replaced,'s0');assert.equal(b.voices.length,6);});
test('one source cannot layer equal priority operations',()=>{const b=new SoundBudget();b.accept(event());assert(!b.accept(event({id:'other',operation:'two'}),10).accepted);assert.equal(b.voices.length,1);});
test('manual success replaces background on same source',()=>{const b=new SoundBudget();b.accept(event());assert(b.accept(event({id:'manual',priority:4}),10).accepted);assert.equal(b.voices.length,1);});
test('low priority cannot replace high priority same source',()=>{const b=new SoundBudget();b.accept(event({priority:4}));assert(!b.accept(event({id:'other'}),10).accepted);});
test('finished voice expires before new operation',()=>{const b=new SoundBudget();b.accept(event());assert(b.accept(event({operation:'two'}),301).accepted);assert.equal(b.voices.length,1);});
test('cooldown applies after very short sound ends',()=>{const b=new SoundBudget();b.accept(event({seconds:.01}));assert(!b.accept(event({operation:'two'}),20).accepted);});
test('cooldown permits later fresh operation',()=>{const b=new SoundBudget();b.accept(event({seconds:.01}));assert(b.accept(event({operation:'two'}),151).accepted);});
test('mechanical cooldown can be set to 600ms',()=>{const b=new SoundBudget();b.accept(event({cooldownMs:600}));assert(!b.accept(event({operation:'two'}),450).accepted);assert(b.accept(event({operation:'three'}),601).accepted);});
test('source removal stops only that source',()=>{const b=new SoundBudget();b.accept(event());b.accept(event({source:'b'}));b.remove('a');assert.equal(b.voices.length,1);assert.equal(b.voices[0].source,'b');});
test('dedup memory bounded at 256 keys under burst',()=>{const b=new SoundBudget();for(let i=0;i<2000;i++)b.accept(event({source:'s'+i,operation:i}));assert.equal(b.seen.size,256);assert(b.voices.length<=2);});
test('dedup keys expire after 5s',()=>{const b=new SoundBudget();b.accept(event());assert(b.accept(event(),5001).accepted);assert.equal(b.seen.size,1);});
test('reset clears pending voices and memory',()=>{const b=new SoundBudget();b.accept(event());b.reset();assert.equal(b.voices.length+b.cooldowns.size+b.seen.size,0);});
test('eight mixed events retain manual and complete over starts',()=>{const b=new SoundBudget();for(let i=0;i<8;i++)b.accept(event({source:'s'+i,id:'e'+i,priority:i<4?2:i<6?4:3}));assert.equal(b.voices.length,6);for(let i=4;i<8;i++)assert(b.voices.some(v=>v.id==='e'+i));});
const result={allPassed:true,cases:checks.length,checks,gameRuntimeVerified:false,scope:'art review admission policy; no Minecraft event integration or debounce implementation'};
fs.writeFileSync(path.join(R,'review/policy-checks.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({allPassed:true,cases:checks.length}));
