from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1]
old=(R.parents[1]/'F04-03/v01/source/charger-preview.js').read_text();draw=old[old.index('function drawModel'):old.index('root.WildcraftChargerPreview=')]
draw=draw.replace('present=true,state=2','node=-1').replace('makeFaces(geo,energy,present,state)','makeFaces(geo,energy,node)').replace('x-=8;y-=8;z-=8;','y-=5.2;').replace('p[0]*22/320','p[0]*18/320').replace('p[1]*22/225','p[1]*18/225').replace('-p[2]/16','-p[2]/32').replace('batteryCuboids:present?geo.batteryParts.length:0,state,present','batteryCuboids:node>=0?geo.batteryParts.length:0,node,referenceScale:1')
draw=draw.replace("const faces=makeFaces", "const faces=makeFaces")
draw=draw.replace("for(const face of faces){", "const allPoints=faces.flatMap(f=>f.points),xs=allPoints.map(p=>p[0]),ys=allPoints.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),fit={scale:Math.min(21,580/(maxX-minX),390/(maxY-minY)),cx:(minX+maxX)/2,cy:(minY+maxY)/2};canvas._machineProjection=fit;for(const face of faces){")
draw=draw.replace("-p[0]*18/320,-p[1]*18/225", "-(p[0]-fit.cx)*fit.scale/320,-(p[1]-fit.cy)*fit.scale/225")
draw=draw.replace("depthTest:true", "depthTest:true,fit")
make=r'''function fractions(e){const q=Math.max(0,Math.min(1000,e))/1000*3;return [0,1,2].map(i=>Math.max(0,Math.min(1,q-i)));}
function rotate(v,n){const [x,y,z]=v;return [[x,z,-y],[x,-z,y],[-x,y,-z],[x,y,z],[-z,y,x],[z,y,-x]][n];}
function point(v,n,g){return n===undefined?v:rotate(v,n).map((a,i)=>a+g.nodes[n].point[i]);}
function makeFaces(geo,e,node=-1){const faces=[],normals={north:[0,0,-1],south:[0,0,1],west:[-1,0,0],east:[1,0,0],up:[0,1,0],down:[0,-1,0]};
for(const p of [...geo.parts,...(node>=0?geo.batteryParts.map(p=>({...p,node})):[])]){const [x0,y0,z0]=p.from,[x1,y1,z1]=p.to;const v={south:[[x1,y1,z1],[x0,y1,z1],[x0,y0,z1],[x1,y0,z1]],north:[[x0,y1,z0],[x1,y1,z0],[x1,y0,z0],[x0,y0,z0]],west:[[x0,y1,z1],[x0,y1,z0],[x0,y0,z0],[x0,y0,z1]],east:[[x1,y1,z0],[x1,y1,z1],[x1,y0,z1],[x1,y0,z0]],up:[[x0,y1,z1],[x1,y1,z1],[x1,y1,z0],[x0,y1,z0]],down:[[x0,y0,z0],[x1,y0,z0],[x1,y0,z1],[x0,y0,z1]]};for(const [dir,points] of Object.entries(v))faces.push({name:p.name,vertices:points.map(v=>point(v,p.node,geo)),normal:p.node===undefined?normals[dir]:rotate(normals[dir],p.node),uv:p.faces[dir].uv});}
if(node>=0)for(const w of geo.batteryWindows){const a=fractions(e)[w.indexBottomUp];if(a>0){const [x0,y0,z]=w.from,[x1,ymax]=w.to,y1=y0+(ymax-y0)*a;const [u0,v0,u1,v1]=geo.batteryEnergyUV;faces.push({name:'energy/'+w.indexBottomUp,vertices:[[x1,y1,z],[x0,y1,z],[x0,y0,z],[x1,y0,z]].map(v=>point(v,node,geo)),normal:rotate([0,0,1],node),uv:[u0,v0+(v1-v0)*(1-a),u1,v1]});}}return faces;}
function project(v,yaw,pitch,fit={scale:18,cx:0,cy:0}){const ya=yaw*Math.PI/180,pa=pitch*Math.PI/180,cy=Math.cos(ya),sy=Math.sin(ya),cp=Math.cos(pa),sp=Math.sin(pa),[x,yy,z]=v,y=yy-5.2,xx=x*cy+z*sy,zz=z*cy-x*sy;return [320-(xx-fit.cx)*fit.scale,225+(-y*cp+zz*sp-fit.cy)*fit.scale];}
'''
js='(function(root){\n'+make+draw+'root.WildcraftMachinePreview={fractions,rotate,point,makeFaces,drawModel,project};})(globalThis);\n';(R/'source/machine-preview.js').write_text(js)
images={name:'data:image/png;base64,'+base64.b64encode((R/'review'/name).read_bytes()).decode() for name in ['machine-front-three-quarter.png','machine-back-three-quarter.png','machine-front.png','machine-top.png','machine-underside.png','machine-battery-front.png','machine-battery-top.png']}
for key,name in [('atlas','machine-atlas-64.png'),('icon32','machine-body-item-32.png'),('icon16','machine-body-item-16.png')]:images[key]='data:image/png;base64,'+base64.b64encode((R/'exports'/name).read_bytes()).decode()
g=json.loads((R/'source/geometry-and-uv.json').read_text())
html=r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · 机械主体 v01</title><style>
*{box-sizing:border-box}body{margin:0;background:#14231b;color:#e2e9dc;font:15px/1.75 system-ui,"PingFang SC",sans-serif}main{max-width:1240px;padding:28px 24px;margin:auto}h1{font-size:29px;margin:10px 0}h2{font-size:18px}p{color:#b2c1ae}.tag{color:#ddb675}.controls{display:flex;flex-wrap:wrap;gap:16px;background:#253729;border:1px solid #465c44;padding:16px;border-radius:6px}label{display:flex;align-items:center;gap:8px}select,input{accent-color:#bc6542;background:#19281f;color:#e2e9dc;padding:6px;border:1px solid #657760;border-radius:3px}input[type=range]{width:150px}button{cursor:pointer;background:#304732;color:#e2e9dc;border:1px solid #657760;border-radius:4px;padding:8px 12px}:focus-visible{outline:3px solid #dfb778;outline-offset:3px}.row{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:18px 0}.panel{background:#253729;border:1px solid #465c44;border-radius:6px;padding:16px;min-width:0}.panel h2{margin:0 0 12px}.modelstage{position:relative}.modelstage canvas{width:100%;height:auto;display:block}#overlay{position:absolute;inset:0;pointer-events:none}.panel img{width:100%;height:auto;display:block}.small{font-size:13px;color:#a6b99e}.poses{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}.board{width:100%;height:auto}.icons{display:flex;gap:24px;flex-wrap:wrap;align-items:center}.icons img{image-rendering:pixelated;width:128px;height:128px}.icons span{display:block;color:#c8d6bd;font-size:14px}.note{color:#dfb778}@media(max-width:980px){.row{grid-template-columns:1fr}main{padding:20px 14px}}
</style><main><span class="tag">F05-01 · v01 · 草稿待审 · 未接入游戏</span><h1>机械主体 · 六面接头与前上控制板</h1><p>低矮承载平台，钢框、绿灰壳和铜紧固点。六个接头共用同一结构；控制板单独位于前上方。可旋转实际几何，也可放入采用电池作为尺寸参考。</p>
<div class="controls"><label>装配参考<select id="node"><option value="-1">空主体</option><option value="0">顶节点 · 电池</option><option value="1">底节点 · 电池</option><option value="2">后节点 · 电池</option><option value="3">前节点 · 电池</option><option value="4">左节点 · 电池</option><option value="5">右节点 · 电池</option></select></label><label>余量<input id="energy" type="range" min="0" max="1000" value="500"><output id="value"></output></label><label>朝向<input id="yaw" type="range" min="-180" max="180" value="-25"></label><label>俯仰<input id="pitch" type="range" min="-85" max="85" value="24"></label><label><input id="bounds" type="checkbox">查看节点与点击范围</label></div>
<div class="poses"><button data-yaw="-25" data-pitch="24">斜侧面</button><button data-yaw="0" data-pitch="0">正面</button><button data-yaw="180" data-pitch="24">背面</button><button data-yaw="90" data-pitch="0">侧面</button><button data-yaw="0" data-pitch="85">顶面</button><button data-yaw="-25" data-pitch="-65">底面</button></div>
<div class="row"><section class="panel"><h2>实际模型 · 六面装配尺寸参考</h2><div class="modelstage"><canvas id="model" width="640" height="450" role="img" aria-label="机械主体实际几何"></canvas><canvas id="overlay" width="640" height="450" aria-hidden="true"></canvas></div><p id="reading" aria-live="polite"></p><p class="small">电池比例1.00，六向变换沿用现节点。此页不模拟安装、能源分配或机械运动；完整安装适配在F05-05复核。</p></section><section class="panel"><h2>实际模型与原生纹理渲染</h2><img id="render" alt="机械主体模型和纹理"><p class="small" id="render-note">实际3D模型渲染；场景照明用于审稿，不烘焙进材质。</p></section></div>
<section class="panel"><h2>原生物品图 · 两种尺寸独立设计</h2><div class="icons"><div><img id="icon32" alt="32像素机械主体物品图"><span>32×32 · 铜角、三可见接口与控制板</span></div><div><img id="icon16" alt="16像素机械主体物品图"><span>16×16 · 同一低平台，压缩细节保持辨识</span></div></div></section>
<p class="note">点击范围仅是审稿辅助。主体1.4×0.65、六节点位置、0.34节点选择半径与现有控制板交互保持；装饰不扩大功能区域。控制板刻纹不是实时启停指示灯。</p><canvas id="board" class="board" width="1200" height="1640"></canvas></main><script>__JS__</script><script>
const G=__G__,sources=__IMAGES__,assets={},M=WildcraftMachinePreview;function get(id){return document.getElementById(id)}
function drawBounds(yaw,pitch){const c=get('overlay').getContext('2d');c.clearRect(0,0,640,450);if(!get('bounds').checked)return;const pr=v=>M.project(v,yaw,pitch,get('model')._machineProjection);c.font='13px system-ui';c.lineWidth=2;for(const n of G.nodes){const p=pr(n.point);c.fillStyle='#ddb675';c.strokeStyle='#ddb675';c.beginPath();c.arc(...p,6,0,Math.PI*2);c.stroke();c.fillText(n.id+' '+n.name,p[0]+8,p[1]-7);}const a=G.controlHitbox.min.map(v=>v*16),b=G.controlHitbox.max.map(v=>v*16),vs=[[a[0],a[1],a[2]],[b[0],a[1],a[2]],[b[0],a[1],b[2]],[a[0],a[1],b[2]],[a[0],b[1],a[2]],[b[0],b[1],a[2]],[b[0],b[1],b[2]],[a[0],b[1],b[2]]];c.strokeStyle='#82cfbf';c.setLineDash([5,4]);for(const [i,j]of [[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]]){const p=pr(vs[i]),q=pr(vs[j]);c.beginPath();c.moveTo(...p);c.lineTo(...q);c.stroke();}c.setLineDash([]);}
function update(){const node=+get('node').value,e=+get('energy').value,yaw=+get('yaw').value,pitch=+get('pitch').value;get('energy').disabled=node<0;get('value').textContent=node<0?'— / 1000':e+' / 1000';const info=M.drawModel(get('model'),assets.atlas,G,e,yaw,pitch,node);drawBounds(yaw,pitch);get('reading').textContent=node<0?'空主体 · 六个统一接头':G.nodes[node].name+'节点 · 原电池比例1.00 · '+e+' / 1000';let image=node===3?'machine-battery-front.png':node===0?'machine-battery-top.png':pitch<0?'machine-underside.png':pitch>65?'machine-top.png':yaw>120||yaw<-120?'machine-back-three-quarter.png':'machine-front-three-quarter.png';get('render').src=sources[image];get('render-note').textContent=image.includes('battery')?'静态尺寸参考：500 / 1000；左侧模型跟随当前输入。':'空主体静态渲染；左侧模型可独立旋转并切换装配参考。';window.currentState={node,e,yaw,pitch,info,bounds:get('bounds').checked};}
function drawBoard(){const c=get('board').getContext('2d');c.fillStyle='#14251b';c.fillRect(0,0,1200,1640);const text=(s,x,y,size=18,color='#dde6d4')=>{c.fillStyle=color;c.font=size+'px system-ui,"PingFang SC",sans-serif';c.textBaseline='top';c.fillText(s,x,y)};const panel=(x,y,w,h)=>{c.fillStyle='#263a2b';c.fillRect(x,y,w,h);c.strokeStyle='#445f43';c.strokeRect(x+.5,y+.5,w-1,h-1)};text('WILDCRAFT / MODULAR MACHINE BODY',30,25,16,'#a7bb99');text('机械主体 · 六面接头与控制板',30,60,32);text('F05-01 v01 · 实际模型 / 原生像素材质 · 草稿待审，未接入',30,108,17,'#ddb675');panel(30,146,565,588);text('低矮承载平台 · 1.4 × 0.65 方块',46,162,20);c.drawImage(assets['machine-front-three-quarter.png'],46,202,533,513);panel(615,146,555,588);text('背面与底部 · 六个接口同一结构',631,162,20);c.drawImage(assets['machine-back-three-quarter.png'],631,202,245,245);c.drawImage(assets['machine-underside.png'],908,202,245,245);c.drawImage(assets['machine-top.png'],631,463,245,245);text('顶节点与控制板分开',904,478,18);text('四角铜点 + 钢色骨架',904,516,18);text('共用方形钢圈',904,554,18);text('双铜接点 + 上缘刻纹',904,592,18);text('装饰不扩大点击区',904,644,17,'#ddb675');text('原生物品图 · 32×32与16×16独立排布',30,766,24);panel(30,808,565,256);panel(615,808,555,256);c.imageSmoothingEnabled=false;c.drawImage(assets.icon32,54,834,192,192);c.drawImage(assets.icon16,294,866,128,128);c.drawImage(assets.atlas,648,838,192,192);c.imageSmoothingEnabled=true;text('32px',101,1033,16);text('16px',336,1033,16);text('64px共用材质图集',863,839,20);text('电池32px区域原样复用',863,880,17);text('钢、铜、壳体与接头共享UV',863,919,17);text('后续部件复用材质块',863,958,17);text('采用电池比例1.00 · 不重做安装版电池',30,1100,24);for(const [key,caption,i]of [['machine-battery-front.png','前节点尺寸参照',0],['machine-battery-top.png','顶节点尺寸参照 · 控制板仍独立',1]]){const x=30+i*585;panel(x,1142,555,419);text(caption,x+16,1158,20);c.drawImage(assets[key],x+91,1200,365,345);}text('六节点坐标、方向与功能范围保持；网页仅作艺术及装配尺寸审稿。',30,1591,17,'#ddb675');}
window.ready=(async()=>{await Promise.all(Object.entries(sources).map(async([key,src])=>{const im=new Image();im.src=src;await im.decode();assets[key]=im;}));get('node').onchange=get('energy').oninput=get('yaw').oninput=get('pitch').oninput=get('bounds').onchange=update;document.querySelectorAll('[data-yaw]').forEach(b=>b.onclick=()=>{get('yaw').value=b.dataset.yaw;get('pitch').value=b.dataset.pitch;update()});get('icon32').src=sources.icon32;get('icon16').src=sources.icon16;update();drawBoard();window.appReady=true;return true})();
</script></html>'''
html=html.replace('__JS__',js).replace('__G__',json.dumps(g)).replace('__IMAGES__',json.dumps(images));(R/'review/preview.html').write_text(html);print('完整审稿页与实际六向几何查看器已生成。')
