from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1]
def image(p):return 'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
G=json.loads((R/'source/geometry-and-uv.json').read_text());G['body']=json.loads((R/'references/approved-machine-geometry.json').read_text())
images={p.name:image(p)for p in (R/'review').glob('*.png')if p.name not in ['rocket-review.png','rocket-live-review.png']}
images.update({p.name:image(p)for p in (R/'exports').glob('*.png')if p.name!='shared-machine-atlas-64.png'})
snapshots=[dict(id='loaded',label='未点燃 · 满燃料',fuel=80,active=False,enabled=False,ghost=False,isSpent=False),dict(id='burning',label='燃烧中 · 部分余量',fuel=37,active=True,enabled=True,ghost=False,isSpent=False),dict(id='shutdown-burning',label='已关机 · 仍在燃烧',fuel=19,active=True,enabled=False,ghost=False,isSpent=False),dict(id='spent',label='燃尽 · 留下空壳',fuel=0,active=False,enabled=False,ghost=False,isSpent=True),dict(id='final-tick',label='末刻 · 零燃料无尾焰',fuel=0,active=True,enabled=True,ghost=False,isSpent=True),dict(id='ghost',label='安装预览 · 固定无尾焰',fuel=80,active=True,enabled=False,ghost=True,isSpent=False)]
(R/'source/review-snapshots.json').write_text(json.dumps(snapshots,ensure_ascii=False,indent=2)+'\n')
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · F05-04 火箭及燃尽空壳 v01</title><style>
:root{color-scheme:dark;background:#14221c;color:#e7dec3;font:16px system-ui,sans-serif}*{box-sizing:border-box}body{margin:0 auto;padding:32px 24px;max-width:1240px}header small{color:#93b39e;letter-spacing:2px}h1{font-size:32px;margin:12px 0}p{line-height:1.7;color:#bbc7b5}h2{font-size:21px;margin-top:30px}main{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:20px}.panel,figure{background:#1c2d24;border:1px solid #354b3c;border-radius:14px;padding:18px;margin:0}canvas{display:block;width:100%;height:auto;border-radius:8px}button,select{background:#2c4235;color:#eee4ca;border:1px solid #59755e;border-radius:6px;padding:10px;min-height:40px;font:inherit;max-width:100%}button:hover{background:#405b47}label{display:block;margin:16px 0;font-size:14px;color:#c5cbb4}input[type=range]{width:100%;accent-color:#d6b078}strong{color:#f3e5bd}.note{font-size:13px}.chips{display:flex;gap:10px;flex-wrap:wrap}.chip{background:#304738;border-radius:6px;padding:8px 12px;font-size:13px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.grid img{width:100%;border-radius:8px}figcaption{font-size:13px;line-height:1.6;margin-top:8px}.icons{display:flex;gap:26px;flex-wrap:wrap}.pixel{image-rendering:pixelated}.icons img{width:128px;height:128px;background:#14221c;border:8px solid #24372b}.compare{display:grid;grid-template-columns:1fr 1fr;gap:18px}.compare img{width:100%}.atlas img{width:512px;max-width:100%;image-rendering:pixelated}a{color:#a3ddbb}@media(max-width:800px){main{grid-template-columns:1fr}.grid{grid-template-columns:repeat(2,1fr)}body{padding:24px 14px}h1{font-size:27px}.compare{gap:8px}}
</style><header><small>WILDCRAFT / B3 · F05-04</small><h1>火箭与燃尽空壳 · 同一件一次性推进器</h1><p>铜壳、钢箍、纸封套与八角喷口。装填和耗尽保留同一个安装接口，以破损封套和深空喷口表达状态。</p><div class="chips"><span class="chip">v01 草稿待审</span><span class="chip">80世界刻 · 不依赖电池</span><span class="chip">未接入游戏</span></div></header>
<h2>实际模型与有限尾焰</h2><main><section class="panel"><canvas id="live" aria-label="火箭和空壳实际模型"></canvas><p id="render-info" class="note"></p></section><aside class="panel"><label>状态快照<select id="snapshot"></select></label><label>安装视图<select id="node"><option value="-1">独立部件</option><option value="0">顶节点</option><option value="1">底节点</option><option value="2">后节点</option><option value="3">前节点</option><option value="4">左节点</option><option value="5">右节点</option></select></label><label>水平视角<input id="yaw" type="range" min="-180" max="180" value="-25"></label><label>俯仰视角<input id="pitch" type="range" min="-85" max="85" value="18"></label><button id="reset">恢复默认视图</button><p id="readout"></p><p class="note">这里展示固定状态快照，不自行倒计时。实际余量按世界刻读取；点燃后关机仍会燃烧，余量为0立即停止尾焰。</p><p class="note">空壳保留外形和节点，不可重新安装。安装预览保持静止且无尾焰。</p></aside></main>
<h2>两种状态 · 实际渲染</h2><section class="compare"><figure><img id="loaded-render"><figcaption>装填 · 完整纸封套与可见推进剂端面</figcaption></figure><figure><img id="spent-render"><figcaption>耗尽 · 破损纸封套与深空喷口</figcaption></figure></section>
<h2>原生物品图标</h2><section class="panel"><div id="icons" class="icons"></div><p class="note">四份独立像素稿：装填/空壳 × 32/16。小尺寸单独构图，共用铜壳和接口，保留破口与空腔线索。</p></section>
<h2>六向安装参考</h2><section id="mounts" class="grid"></section><p class="note">节点与尺寸均沿用现有合同。交互视图可分别查看装填、燃烧、空壳及透明预览的六向朝向。</p>
<h2>统一纹理图集</h2><section class="panel atlas"><img id="atlas"><p class="note">128×64：左侧完整复用机械64×64，右侧仅新增16×16纸纹。铜壳、钢箍、喷口内壁和根部接口均复用既有纹理。</p></section>
<h2>综合审稿板</h2><section class="panel"><canvas id="board"></canvas><p><a href="rocket-review.png">打开审稿板 PNG</a></p></section><p class="note">本轮仅美术交付；现有燃料、启停、空壳回收和推力规则保留。源稿与验证记录一起存档。</p>
<script>const G=__G__,SOURCES=__IMAGES__,SNAPSHOTS=__SNAPSHOTS__;</script><script>__RENDER__</script><script>
const loaded={},names=['顶','底','后','前','左','右'];window.reviewReady=false;
function current(){return SNAPSHOTS.find(s=>s.id===document.querySelector('#snapshot').value)||SNAPSHOTS[0]}
function geometry(s){const p=WildcraftRocketPreview.presentation(s);return {...G,...G.variants[p.variant],...p,body:G.body};}
function redraw(){const s=current(),p=WildcraftRocketPreview.presentation(s),n=+document.querySelector('#node').value;window.lastPresentation=p;window.lastRender=WildcraftRocketPreview.drawModel(document.querySelector('#live'),loaded['rocket-atlas-128x64.png'],geometry(s),+document.querySelector('#yaw').value,+document.querySelector('#pitch').value,n);document.querySelector('#render-info').textContent=`${p.variant==='spent'?'空壳':'装填火箭'} · 共用安装原点 · ${n<0?'独立模型':names[n]+'节点'} · ${p.ghost?'透明预览':'实际材质'}`;document.querySelector('#readout').innerHTML=`<strong>燃料 ${p.fuel} / 80 世界刻</strong><br>${p.flameVisible?'燃烧中 · 尾焰外向':p.variant==='spent'?'燃尽空壳 · 无尾焰':'未燃烧 · 无尾焰'}<br><span class="note">电池费用：0 · ${s.enabled?'整机已启用':'整机已停机'}</span>`;}
for(const id of ['node','snapshot','yaw','pitch'])document.querySelector('#'+id).addEventListener('input',redraw);document.querySelector('#reset').onclick=()=>{document.querySelector('#node').value=-1;document.querySelector('#snapshot').value='loaded';document.querySelector('#yaw').value=-25;document.querySelector('#pitch').value=18;redraw()};
function board(){const c=document.querySelector('#board');c.width=1200;c.height=2050;const x=c.getContext('2d');x.fillStyle='#14221c';x.fillRect(0,0,c.width,c.height);const text=(s,a,b,size=22,col='#e7dec3')=>{x.fillStyle=col;x.font=`${size}px system-ui`;x.fillText(s,a,b)},image=(n,a,b,w,h,pixel=false)=>{x.imageSmoothingEnabled=!pixel;x.drawImage(loaded[n],a,b,w,h)};
text('WILDCRAFT · F05-04 / v01',40,50,22,'#93b39e');text('火箭与燃尽空壳 · 共用底模与接口',40,101,36);text('草稿待审 / 原生32与16分别绘制 / 未接入游戏',40,139,19,'#b1bca8');image('rocket-three-quarter.png',40,163,540,540);image('spent-rocket-three-quarter.png',620,163,540,540);text('装填 · 完整封套与推进剂端面',54,735,22);text('耗尽 · 破损封套与深空喷口',634,735,22);
for(const [n,a,b,label]of [['rocket-item-32.png',100,773,'装填32×32'],['rocket-item-16.png',350,773,'装填16×16'],['spent-rocket-item-32.png',700,773,'空壳32×32'],['spent-rocket-item-16.png',950,773,'空壳16×16']]){image(n,a,b,128,128,true);text(label,a-2,b+160,20);}
text('六向安装 · 原尺度 · 喷口外向、推力反向',40,984,24);for(let i=0;i<6;i++){const a=40+i%3*383,b=1010+Math.floor(i/3)*354;image('rocket-mounted-'+i+'.png',a+14,b,330,330);text(names[i]+'节点',a+18,b+351,20)}
image('rocket-burning-native-flame.png',40,1740,270,270);text('沿用现有尾焰',60,2030,18);text('80世界刻一次性燃料',360,1785,27);text('点燃后关机仍燃烧；燃料0、空壳或安装预览无尾焰。',360,1832,21);text('空壳不重新安装或充电；拆下回收仍按现有规则。',360,1872,21);text('铜壳/钢箍/接口复用，仅新增16×16纸纹。',360,1920,21);text('模型、像素源稿、六向参考与检查记录已存档。',360,1965,21,'#b1bca8');}
(async()=>{for(const[n,src]of Object.entries(SOURCES)){const im=new Image();im.src=src;await im.decode();loaded[n]=im;}document.querySelector('#snapshot').innerHTML=SNAPSHOTS.map(s=>`<option value="${s.id}">${s.label}</option>`).join('');document.querySelector('#loaded-render').src=SOURCES['rocket-three-quarter.png'];document.querySelector('#spent-render').src=SOURCES['spent-rocket-three-quarter.png'];document.querySelector('#atlas').src=SOURCES['rocket-atlas-128x64.png'];document.querySelector('#icons').innerHTML=['rocket','spent-rocket'].flatMap(state=>[32,16].map(n=>`<figure><img class="pixel" alt="${state==='rocket'?'装填':'空壳'}${n}像素" src="${SOURCES[state+'-item-'+n+'.png']}"><figcaption>${state==='rocket'?'装填':'空壳'} · ${n}×${n}</figcaption></figure>`)).join('');document.querySelector('#mounts').innerHTML=names.map((n,i)=>`<figure><img alt="${n}节点安装" src="${SOURCES['rocket-mounted-'+i+'.png']}"><figcaption>${n}节点 · 外向喷口 / 反向推力</figcaption></figure>`).join('');redraw();board();window.reviewReady=true;})().catch(e=>{window.reviewError=e.message;document.querySelector('#render-info').textContent=e.message});
</script></html>'''
html=html.replace('__G__',json.dumps(G,separators=(',',':'),ensure_ascii=False)).replace('__IMAGES__',json.dumps(images,separators=(',',':'))).replace('__SNAPSHOTS__',json.dumps(snapshots,separators=(',',':'),ensure_ascii=False)).replace('__RENDER__',(R/'source/rocket-preview.js').read_text());(R/'review/preview.html').write_text(html)
print('Actual rocket/spent/ghost review ready.')
