(function(root){
function rotate(v,n){const [x,y,z]=v;return [[x,z,-y],[x,-z,y],[-x,y,-z],[x,y,z],[-z,y,x],[z,y,-x]][n];}
function rotorPoint(v,angle,pivot){const [x,y,z]=v,c=Math.cos(angle),s=Math.sin(angle);return [x*c-y*s,x*s+y*c,z];}
function mount(v,node,g){return node<0?v:rotate(v,node).map((a,i)=>a+g.body.nodes[node].point[i]);}
function rawBox(p,g){const [x0,y0,z0]=p.from,[x1,y1,z1]=p.to,vs=[[x0,y0,z0],[x1,y0,z0],[x1,y1,z0],[x0,y1,z0],[x0,y0,z1],[x1,y0,z1],[x1,y1,z1],[x0,y1,z1]],fm={north:[0,1,2,3],south:[5,4,7,6],east:[1,5,6,2],west:[4,0,3,7],up:[3,2,6,7],down:[4,5,1,0]};return {name:p.name,vertices:p.node===undefined?vs:vs.map(v=>mount(v,p.node,g)),faces:Object.entries(fm).map(([key,indices])=>{const [u0,v0,u1,v1]=p.faces[key].uv;return {indices,uvs:[[u0/2,v1],[u1/2,v1],[u1/2,v0],[u0/2,v0]]}})};}
function makeFaces(g,angle=0,node=-1){const parts=g.parts.map(p=>({...p,isGhost:!!g.ghost,vertices:p.vertices.map(v=>mount(p.group==='rotor'?rotorPoint(v,angle,g.rotorPivot):v,node,g))}));if(g.flameVisible){const p={name:'review/native_flame',from:g.flameBounds.min,to:g.flameBounds.max,faces:Object.fromEntries(['north','south','east','west','up','down'].map(f=>[f,{uv:[12,12,16,16]}]))};if(node>=0)p.node=node;parts.push({...rawBox(p,g),fx:true});}if(node>=0)parts.push(...g.body.parts.map(p=>rawBox(p,g)));const out=[];for(const p of parts){const center=[0,1,2].map(i=>p.vertices.reduce((s,v)=>s+v[i],0)/p.vertices.length);for(const f of p.faces){const points=f.indices.map(i=>p.vertices[i]),a=points[1].map((v,i)=>v-points[0][i]),b=points[2].map((v,i)=>v-points[0][i]);let normal=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],len=Math.hypot(...normal);normal=normal.map(v=>v/len);const fc=[0,1,2].map(i=>points.reduce((s,v)=>s+v[i],0)/points.length);if(normal.reduce((s,v,i)=>s+v*(fc[i]-center[i]),0)<0)normal=normal.map(v=>-v);out.push({pass:p.fx?1:p.isGhost?2:0,name:p.name,vertices:points,normal,uvs:f.uvs});}}return out;}
function angleFor(age,active,ghost=false){return active&&!ghost?age*.7:0;}

function presentation(s){const fuel=Math.max(0,Math.min(80,Math.trunc(s.fuel)));const spent=!!s.isSpent||fuel===0;return {fuel,variant:spent?'spent':'loaded',flameVisible:!!s.active&&fuel>0&&!s.ghost&&!spent,ghost:!!s.ghost,energyCost:0};}
function drawModel(canvas,atlas,geo,yaw=-25,pitch=18,node=-1){
canvas.width=640;canvas.height=450;let cache=canvas._rocketGl;
if(!cache){const gl=canvas.getContext('webgl',{preserveDrawingBuffer:true,alpha:false,antialias:true});if(!gl)throw Error('Review WebGL unavailable');
 const shader=(t,c)=>{const q=gl.createShader(t);gl.shaderSource(q,c);gl.compileShader(q);if(!gl.getShaderParameter(q,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(q));return q;};const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 position;attribute vec2 uv;attribute float shade;varying vec2 vUv;varying float vShade;void main(){gl_Position=vec4(position,1.0);vUv=uv;vShade=shade;}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec2 vUv;varying float vShade;uniform sampler2D atlas;uniform float mode;void main(){if(mode>1.5){gl_FragColor=vec4(.364706,.843137,.717647,136.0/255.0);return;}if(mode>.5){gl_FragColor=vec4(1.0,.835294,.545098,221.0/255.0);return;}vec4 c=texture2D(atlas,vUv);if(c.a<.5)discard;gl_FragColor=vec4(c.rgb*vShade,1.0);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,atlas);for(const t of [gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER])gl.texParameteri(gl.TEXTURE_2D,t,gl.NEAREST);for(const t of [gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T])gl.texParameteri(gl.TEXTURE_2D,t,gl.CLAMP_TO_EDGE);cache=canvas._rocketGl={gl,program,texture,buffer:gl.createBuffer(),locations:['position','uv','shade'].map(k=>gl.getAttribLocation(program,k)),mode:gl.getUniformLocation(program,'mode')};}
const {gl,program,texture,buffer,locations,mode}=cache;gl.viewport(0,0,640,450);gl.clearColor(.094,.137,.114,1);gl.depthMask(true);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.useProgram(program);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(gl.getUniformLocation(program,'atlas'),0);
const ya=yaw*Math.PI/180,pa=pitch*Math.PI/180,cy=Math.cos(ya),sy=Math.sin(ya),cp=Math.cos(pa),sp=Math.sin(pa);const transform=v=>{const[x,y,z]=v,xx=x*cy+z*sy,zz=z*cy-x*sy;return [xx,-y*cp+zz*sp,y*sp+zz*cp]};const faces=makeFaces(geo,0,node).map(f=>({...f,normal:transform(f.normal),points:f.vertices.map(transform)})).filter(f=>f.normal[2]>.001);const pts=faces.flatMap(f=>f.points),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const fit={scale:Math.min(90,580/(maxX-minX),390/(maxY-minY)),cx:(minX+maxX)/2,cy:(minY+maxY)/2};
for(const pass of [0,2,1]){const fs=faces.filter(f=>f.pass===pass);if(pass)fs.sort((a,b)=>a.points.reduce((s,p)=>s+p[2],0)/a.points.length-b.points.reduce((s,p)=>s+p[2],0)/b.points.length);const data=[];for(const f of fs){const light=Math.max(.48,Math.min(1,.58+f.normal[0]*.15-f.normal[1]*.22+f.normal[2]*.25));for(let i=1;i<f.points.length-1;i++)for(const j of [0,i,i+1]){const p=f.points[j],[u,v]=f.uvs[j];data.push(-(p[0]-fit.cx)*fit.scale/320,-(p[1]-fit.cy)*fit.scale/225,-p[2]/64,u/16,1-v/16,light);}}
 if(pass){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);}else{gl.disable(gl.BLEND);gl.depthMask(true);}gl.uniform1f(mode,pass);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.DYNAMIC_DRAW);for(let i=0;i<3;i++){gl.enableVertexAttribArray(locations[i]);gl.vertexAttribPointer(locations[i],[3,2,1][i],gl.FLOAT,false,24,[0,12,20][i]);}gl.drawArrays(gl.TRIANGLES,0,data.length/6);}
gl.depthMask(true);gl.disable(gl.BLEND);return {node,visibleFaces:faces.length,productionParts:geo.parts.length,flameVisible:geo.flameVisible,ghost:geo.ghost,fxFaces:faces.filter(f=>f.pass===1).length,ghostFaces:faces.filter(f=>f.pass===2).length,referenceBody:node>=0,depthTest:true,fit};
}
root.WildcraftRocketPreview={rotate,mount,makeFaces,presentation,drawModel};})(globalThis);
