(function(root){
function fractions(e){const q=Math.max(0,Math.min(1000,e))/1000*3;return [0,1,2].map(i=>Math.max(0,Math.min(1,q-i)));}
function makeFaces(geo,e,present=true,state=2){const faces=[],normals={north:[0,0,-1],south:[0,0,1],west:[-1,0,0],east:[1,0,0],up:[0,1,0],down:[0,-1,0]};
for(const p of [...geo.parts,...(present?geo.batteryParts:[])]){const [x0,y0,z0]=p.from,[x1,y1,z1]=p.to;
const v={south:[[x1,y1,z1],[x0,y1,z1],[x0,y0,z1],[x1,y0,z1]],north:[[x0,y1,z0],[x1,y1,z0],[x1,y0,z0],[x0,y0,z0]],west:[[x0,y1,z1],[x0,y1,z0],[x0,y0,z0],[x0,y0,z1]],east:[[x1,y1,z0],[x1,y1,z1],[x1,y0,z1],[x1,y0,z0]],up:[[x0,y1,z1],[x1,y1,z1],[x1,y1,z0],[x0,y1,z0]],down:[[x0,y0,z0],[x1,y0,z0],[x1,y0,z1],[x0,y0,z1]]};for(const [dir,points] of Object.entries(v))faces.push({name:p.name,vertices:points,normal:normals[dir],uv:p.faces[dir].uv});}
const q=geo.statusPanel;let [x0,y0,z]=q.from,[x1,y1]=q.to;faces.push({name:'status/'+state,vertices:[[x1,y1,z],[x0,y1,z],[x0,y0,z],[x1,y0,z]],normal:[0,0,1],uv:q.tiles[state]});
if(present){for(const w of geo.batteryWindows){const a=fractions(e)[w.indexBottomUp];if(a>0){const [x0,y0,z]=w.from,[x1,ymax]=w.to,y1=y0+(ymax-y0)*a;const [u0,v0,u1,v1]=geo.batteryEnergyUV;faces.push({name:'energy/'+w.indexBottomUp,vertices:[[x1,y1,z],[x0,y1,z],[x0,y0,z],[x1,y0,z]],normal:[0,0,1],uv:[u0,v0+(v1-v0)*(1-a),u1,v1]});}}}return faces;}
function drawModel(canvas,atlas,geo,energy,yaw=-25,pitch=18,present=true,state=2){
canvas.width=640;canvas.height=450;let cache=canvas._batteryGl;
if(!cache){const gl=canvas.getContext('webgl',{preserveDrawingBuffer:true,alpha:false,antialias:true});if(!gl)throw new Error('Review WebGL unavailable');
 const shader=(type,code)=>{const sh=gl.createShader(type);gl.shaderSource(sh,code);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(sh));return sh;};
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 position; attribute vec2 uv; attribute float shade; varying vec2 vUv; varying float vShade; void main(){gl_Position=vec4(position,1.0);vUv=uv;vShade=shade;}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float; varying vec2 vUv; varying float vShade; uniform sampler2D atlas; void main(){vec4 c=texture2D(atlas,vUv);if(c.a<0.5)discard;gl_FragColor=vec4(c.rgb*vShade,1.0);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));
 const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,atlas);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
 cache=canvas._batteryGl={gl,program,texture,buffer:gl.createBuffer(),locations:['position','uv','shade'].map(k=>gl.getAttribLocation(program,k))};}
const {gl,program,texture,buffer,locations}=cache;gl.viewport(0,0,640,450);gl.clearColor(.094,.137,.114,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.useProgram(program);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(gl.getUniformLocation(program,'atlas'),0);
const ya=yaw*Math.PI/180,pa=pitch*Math.PI/180,cy=Math.cos(ya),sy=Math.sin(ya),cp=Math.cos(pa),sp=Math.sin(pa);const transform=(v,position)=>{let [x,y,z]=v;if(position){x-=8;y-=8;z-=8;}const xx=x*cy+z*sy,zz=z*cy-x*sy;return [xx,-y*cp+zz*sp,y*sp+zz*cp];};
const faces=makeFaces(geo,energy,present,state).map(f=>({...f,normal:transform(f.normal,false),points:f.vertices.map(v=>transform(v,true))})).filter(f=>f.normal[2]>.001),data=[];
for(const face of faces){const [u0,v0,u1,v1]=face.uv.map(v=>v/16),uvs=[[u0,1-v0],[u1,1-v0],[u1,1-v1],[u0,1-v1]],light=Math.max(.48,Math.min(1,.58+face.normal[0]*.15-face.normal[1]*.22+face.normal[2]*.25));for(const idx of [0,1,2,0,2,3]){const p=face.points[idx];data.push(-p[0]*22/320,-p[1]*22/225,-p[2]/16,...uvs[idx],light);}}
gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.DYNAMIC_DRAW);for(let i=0;i<3;i++){gl.enableVertexAttribArray(locations[i]);gl.vertexAttribPointer(locations[i],[3,2,1][i],gl.FLOAT,false,24,[0,12,20][i]);}gl.drawArrays(gl.TRIANGLES,0,data.length/6);
return {energy,fractions:fractions(energy),visibleFaces:faces.length,yaw,pitch,modelCuboids:geo.parts.length,batteryCuboids:present?geo.batteryParts.length:0,state,present,depthTest:true};
}
root.WildcraftChargerPreview={fractions,makeFaces,drawModel};})(globalThis);
