from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1]
load=lambda p:json.loads(p.read_text())
M=load(R/'exports/focus-mix-spec.json');S=load(R/'references/adopted-s01-design.json');N=load(R/'references/native-local-map.json')['assets'];audio={p.stem:base64.b64encode(p.read_bytes()).decode() for p in (R/'references').glob('*.ogg')}
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · A13-C 专注音效混音复核</title><style>
:root{color-scheme:dark;--bg:#0a1412;--panel:#14231e;--line:#31493e;--text:#e6eee3;--soft:#a4b8ac;--green:#8ad2b2;--gold:#edcc83}*{box-sizing:border-box}body{margin:0;background:radial-gradient(ellipse at 90% 0%,#253b29,transparent 48%),var(--bg);color:var(--text);font:16px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:1060px;margin:auto;padding:48px 28px 50px}small,.muted{color:var(--soft)}.eyebrow{letter-spacing:.12em;color:var(--green);font-size:12px}h1{font-size:clamp(28px,4vw,43px);line-height:1.24;margin:15px 0}p{margin:12px 0 20px}.intro{max-width:750px;color:var(--soft)}.cards{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card,.player,.notes{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:24px}.card:last-child{border-color:#8b804e}.card h2{font-size:20px;margin:2px 0 14px}.values{font-size:23px;display:flex;gap:32px;flex-wrap:wrap}.values small{display:block;font-size:13px}.card:last-child .values{color:var(--gold)}.player{margin-top:20px}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}select,button{font:inherit;border-radius:9px;border:1px solid var(--line);padding:11px 17px;background:#203c2e;color:var(--text)}select{flex:1;min-width:180px}button{cursor:pointer}button:hover{background:#2c5140}button:focus-visible,select:focus-visible,input:focus-visible{outline:3px solid var(--gold);outline-offset:3px}.primary{background:#8cccb0;color:#102319;border-color:#8cccb0}.gold{background:#d6bd7f;color:#292211;border-color:#d6bd7f}.gold:hover{background:#ecd39a}.controls{display:grid;grid-template-columns:1fr 1fr 1fr;gap:22px;margin:24px 0}label{display:block}input[type=range]{width:100%;accent-color:var(--green)}output{color:var(--green);float:right}.sceneNote{min-height:30px;font-size:14px;color:var(--soft);margin:8px 0 20px}.status{min-height:52px;color:var(--green);font-size:15px;margin-top:16px}progress{width:100%;height:7px;accent-color:var(--green)}.timeline{display:flex;justify-content:space-between;color:var(--soft);font-size:12px}.dry{margin-top:18px}h3{font-size:16px}.notes{margin-top:20px}.notes p{font-size:14px;color:var(--soft)}.wave{width:100%;display:block;margin-top:12px;border-radius:12px}footer{font-size:12px;margin-top:24px;color:var(--soft)}@media(max-width:650px){main{padding:28px 16px}.cards,.controls{grid-template-columns:1fr}.card,.player,.notes{padding:18px}.controls{gap:14px}.row button{flex:1}.values{font-size:22px}.status{min-height:72px}}
</style><main><div class="eyebrow">WILDCRAFT · A13-C / v01 · 待试听采用</div><h1>专注提示，在环境声音里</h1><p class="intro">保留已采用的进入与退出音色。用同一组环境声比较两种音量，听退出提示在战斗和机械声中是否仍然清楚。</p><div class="cards"><section class="card"><h2>A · 原方案</h2><div class="values"><div><small>进入专注</small>0.22</div><div><small>退出专注</small>0.22</div></div><p class="muted">现有游戏参数，作为对照。</p></section><section class="card"><h2>B · 建议方案</h2><div class="values"><div><small>进入专注</small>0.22</div><div><small>退出专注</small>0.28</div></div><p class="muted">只补偿退出音量，约增加 2.1 dB。</p></section></div><section class="player" aria-label="音效试听"><label for="scene">试听场景</label><div class="row"><select id="scene">OPTIONS</select></div><p class="sceneNote" id="sceneNote"></p><div class="row"><button data-profile="current">播放 A · 原方案</button><button class="gold" data-profile="proposed">播放 B · 建议方案</button><button id="stop">停止</button></div><div class="controls"><label for="master">试听总音量 <output id="masterOut"></output><input id="master" type="range" min="0" max="1" step="0.01" value="0.6"></label><label for="background">环境声强度 <output id="backgroundOut"></output><input id="background" type="range" min="0" max="1.25" step="0.05" value="1"></label><label for="distance">S01 机械距离 <output id="distanceOut"></output><input id="distance" type="range" min="0" max="14" step="1" value="2"></label></div><progress id="progress" value="0" max="1" aria-label="试听进度"></progress><div class="timeline"><span>常规场景：1 秒进入 · 3 秒退出</span><span id="playing">等待播放</span></div><div class="status" id="status" role="status" aria-live="polite">请选择场景，再播放 A 或 B。页面不会自动播放。</div><div class="row dry"><button data-profile="proposed" data-mode="enter">单听进入</button><button data-profile="current" data-mode="exit">单听退出 A</button><button data-profile="proposed" data-mode="exit">单听退出 B</button><button data-profile="proposed" data-mode="background">单听环境声</button></div></section><section class="notes"><h3>对照时，建议总音量和场景保持一致</h3><p>建议先听安静环境，再听「射箭与受击」和「雨中战斗与机械」。关注退出音是否清晰、是否突兀，以及快速切换时是否出现堆叠。环境声强度、机械距离仅用于试听，不是新增游戏设置。</p><h3>音色与事件规则保持原样</h3><p>进入上行、退出下行；专注提示无距离衰减。快速切换停止上一段，重复状态不重复提示。S01 同时最多六声，专注单声独立；原版战斗与天气声音继续播放。</p><div class="wave">WAVE</div><p>波形采用相同纵向刻度。文件测量支持退出约增加 2.1 dB，但不能据此断言人耳辨识已通过。</p><h3>本次试听的范围</h3><p>原版雨声、雪地脚步和战斗音从本机游戏缓存读取，作为固定声音参照；不是实机录音，也未复现游戏内各类别音量及完整空间声场。雪地行走使用脚步声，不添加持续降雪声。自有专注与 S01 音效已嵌入本页，离线也可试听安静、机械、六声预算和快速切换。待你试听采用后，再安排游戏内验证。</p></section><footer>仅制作混音复核稿 · 原 OGG 与母版保留 · 未修改 Java／游戏配置 · 未接入游戏</footer></main><script>@@CONSTANTS@@</script><script>@@POLICY@@</script><script>@@PLANNER@@</script><script>@@PLAYER@@</script></html>'''
if M.get('adopted'):
 html=html.replace('v01 · 待试听采用','v01 · 已采用 · 未接入').replace('待你试听采用后，再安排游戏内验证。','本版已采用，游戏内验证待接入阶段执行。')
html=html.replace('OPTIONS',''.join(f'<option value="{s["id"]}">{s["title"]}</option>' for s in M['scenarios']))
html=html.replace('WAVE',(R/'review/focus-waveforms.svg').read_text())
html=html.replace('@@CONSTANTS@@','const MIX='+json.dumps(M,ensure_ascii=False)+';const S01='+json.dumps(S,ensure_ascii=False)+';const NATIVE='+json.dumps([{'id':a['id'],'url':a['url']} for a in N])+';const AUDIO='+json.dumps(audio)+';')
for placeholder,p in [('POLICY','references/s01-policy.js'),('PLANNER','source/mix-policy.js'),('PLAYER','source/mix-review.js')]:html=html.replace('@@'+placeholder+'@@',(R/p).read_text())
(R/'review/preview.html').write_text(html)
print('Preview built; own OGG embedded:',len(audio),'native OGG embedded: 0')
