from pathlib import Path
import base64,json
R=Path(__file__).resolve().parents[1]
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · Fuse短反馈 v01</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#102017;color:#e1e8d8;font:16px/1.65 -apple-system,"PingFang SC",sans-serif}main{max-width:1250px;margin:auto;padding:28px 24px}h1{font-size:32px;margin:8px 0}h2{font-size:22px}.tag{color:#dfb776;font-size:14px}.small,.muted{color:#b4c5aa}.small{font-size:14px}.controls{display:flex;flex-wrap:wrap;gap:14px;padding:18px;background:#25372a;border:1px solid #4c5e46;border-radius:10px;margin:20px 0}label{display:flex;align-items:center;gap:8px;flex-wrap:wrap}select,button,input{font:inherit;max-width:100%}select,button{padding:8px;background:#16291c;color:inherit;border:1px solid #718368;border-radius:5px;min-height:42px}button{cursor:pointer}button:hover{background:#354b32}select:disabled{opacity:.5}input[type=range]{width:150px;accent-color:#dbb678}:focus-visible{outline:3px solid #e4bf78;outline-offset:3px}.stage{display:grid;grid-template-columns:minmax(0,2fr) minmax(250px,1fr);gap:20px}.panel{background:#1b2c21;border:1px solid #4c5e46;border-radius:10px;padding:18px;min-width:0}canvas{image-rendering:pixelated}#live{display:block;width:100%;height:auto}.views{display:flex;gap:12px;flex-wrap:wrap;margin-top:14px}.board{width:100%;height:auto}.links{display:flex;gap:20px;flex-wrap:wrap;margin:22px 0}a{color:#e7c98a}#status{overflow-wrap:anywhere}@media(max-width:850px){.stage{grid-template-columns:1fr}main{padding:20px 14px}h1{font-size:27px}.controls{padding:14px}}
</style><main><div class="tag">WILDCRAFT / F03-04 · v01 待视觉审稿</div><h1>特殊材料与融合过程 · 短反馈</h1><p class="muted">火的上升余烬、冰的冷色碎粒、弹性的方向碎屑；融合内收、拆卸外散。</p><div class="controls"><label>反馈<select id="type"><option value="fire">火命中</option><option value="ice">冰命中</option><option value="elastic">弹性命中</option><option value="fuse">融合成功</option><option value="split">拆卸成功</option></select></label><label>触发场景<select id="channel"><option value="melee">近战命中</option><option value="shield-melee">完整格挡近战</option><option value="arrow-entity">箭命中实体</option><option value="arrow-block">箭射中方块</option><option value="shield-ranged">完整格挡投射物</option><option value="shield-partial">部分格挡</option><option value="action" id="actionOption" disabled>物品操作事务</option></select></label><label>结果<select id="result"><option value="confirmed">确认生效</option><option value="refused">失败或未生效</option><option value="inactive">材料数据不可用</option><option value="duplicate">重复通知</option><option value="model-only" id="modelOnlyOption">显示资源缺失，效果生效</option></select></label><label>粒子设置<select id="mode"><option value="all">全部</option><option value="reduced">减少</option><option value="minimal">最少额外粒子</option></select></label><label><input id="light" type="checkbox">浅色环境</label><label><input id="protected" type="checkbox">显示准星保护参考</label></div><div class="stage"><section class="panel"><canvas id="live" width="480" height="270" role="img" aria-label="融合短反馈动态参考"></canvas><div class="views"><button id="play">播放一次</button><button id="stress">密集事件参考</button><button id="reset">重置示例</button><label>时间<input id="time" type="range" min="0" max="12" step="0.1" value="2"><span id="timeLabel">0.10 s</span></label></div><p class="small">可播放或拖动时间检查起始、方向和消退。一次反馈最长8世界刻；密集参考使用同一预算。</p></section><section class="panel"><h2 id="typeLabel"></h2><p id="stats" class="small"></p><canvas id="detail" width="192" height="144" aria-label="粒子局部3倍放大参考"></canvas><p class="small">局部3倍放大，仅用于审稿。</p><p id="status" aria-live="polite"></p><p class="small">当前为美术动态模拟。图中场景和粒子形状是程序化近似，真实游戏接入将复用原版精灵。不会执行真实融合、拆卸或战斗操作。</p><p class="small">反馈不改变原版火焰、缓慢与击退，也不新增飞箭拖尾、全屏滤镜或闪屏。</p></section></div><h2>时序审稿总览</h2><canvas id="board" class="board" width="1200" height="1680" role="img" aria-label="五种融合短反馈时序审稿"></canvas><div class="links"><a href="/exports/fuse-feedback-presets.json">五套反馈参数</a><a href="/source/feedback-engine.js">动态参考源</a><a href="/integration-map.md">接入与触发规则</a><a href="/README.md">制作说明</a></div><p class="small">2026-10-06 · F03-03已采用 · 本项待采用、未接入 · 下一项：S01音效配套</p></main><script>const CONFIG=__CONFIG__,ATLAS=__ATLAS__;</script><script>__ENGINE__</script><script>__REVIEW__</script></html>'''
for key,value in [('__CONFIG__',(R/'exports/fuse-feedback-presets.json').read_text()),('__ATLAS__',json.dumps('data:image/png;base64,'+base64.b64encode((R/'references/adopted-fuse-atlas.png').read_bytes()).decode())),('__ENGINE__',(R/'source/feedback-engine.js').read_text()),('__REVIEW__',(R/'source/feedback-review.js').read_text())]:html=html.replace(key,value)
(R/'review/preview.html').write_text(html)
print('Five-preset animation review created')
