from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1];P=R.parents[3]
s=(R/'references/fan-preview.js').read_text().replace('WildcraftFanPreview','WildcraftWingPreview').replace('fanParts','wingParts');s=s.replace('[u0,v1],[u1,v1],[u1,v0],[u0,v0]','[u0/2,v1],[u1/2,v1],[u1/2,v0],[u0/2,v0]');s=s.replace("angleFor(age,active,ghost=false){return active&&!ghost?age*.7:0;}","angleFor(age,active,ghost=false){return 0;}")
# The review renderer retains shared coordinates, depth testing and native nearest texels.
(R/'source/wing-preview.js').write_text(s)
def data(p):return 'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
G=json.loads((R/'source/geometry-and-uv.json').read_text());G['body']=json.loads((R/'references/approved-machine-geometry.json').read_text())
images={n:data(R/'review'/n)for n in ['wing-three-quarter.png','wing-top.png','wing-root.png','wing-side.png','wing-underside.png']+[f'wing-mounted-{n}.png'for n in range(6)]}
images.update({n:data(R/'exports'/n)for n in ['wing-item-32.png','wing-item-16.png','wing-atlas-128x64.png']})
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · F05-02 机械翼 v01</title><style>
:root{color-scheme:dark;background:#14221c;color:#e7dec3;font:16px system-ui,sans-serif}*{box-sizing:border-box}body{margin:0 auto;padding:36px 24px;max-width:1240px}header small{color:#93b39e;letter-spacing:2px}h1{font-size:32px;margin:12px 0}p{line-height:1.7;color:#bbc7b5}h2{font-size:20px;margin-top:30px}main{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:20px}.panel,figure{background:#1c2d24;border:1px solid #354b3c;border-radius:14px;padding:18px;margin:0}canvas{display:block;width:100%;height:auto;border-radius:8px}button,select{background:#2c4235;color:#eee4ca;border:1px solid #59755e;border-radius:6px;padding:10px;min-height:40px;font:inherit}button:hover{background:#405b47}label{display:block;margin:18px 0;font-size:14px;color:#c5cbb4}input[type=range]{width:100%;accent-color:#d6b078}input[type=checkbox]{accent-color:#93e8c0}strong{color:#f3e5bd}.note{font-size:13px}.chips{display:flex;gap:10px;flex-wrap:wrap}.chip{background:#304738;border-radius:6px;padding:8px 12px;font-size:13px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.grid img{width:100%;border-radius:8px}figcaption{font-size:13px;line-height:1.6;margin-top:8px}.icons{display:flex;align-items:center;gap:28px;flex-wrap:wrap}.pixel{image-rendering:pixelated}.icons img{width:128px;height:128px;background:#14221c;border:8px solid #24372b}.atlas img{width:512px;max-width:100%;image-rendering:pixelated}a{color:#a3ddbb}@media(max-width:800px){main{grid-template-columns:1fr}.grid{grid-template-columns:repeat(2,1fr)}body{padding:24px 14px}h1{font-size:27px}}
</style><header><small>WILDCRAFT / B3 · F05-02</small><h1>机械翼 · 布木被动滑翔面</h1><p>平直双翼、亚麻与橄榄布面、固定木骨架。沿用已采用的机械接口与滑翔伞材质。</p><div class="chips"><span class="chip">v01 草稿待审</span><span class="chip">不耗电 · 无转动部件</span><span class="chip">未接入游戏</span></div></header>
<h2>实际模型与安装方向</h2><main><section class="panel"><canvas id="live" aria-label="可旋转机械翼实际网格"></canvas><p id="render-info" class="note"></p></section><aside class="panel"><label>安装视图<select id="node"><option value="-1">单独机械翼</option><option value="0">顶节点</option><option value="1">底节点</option><option value="2">后节点</option><option value="3">前节点</option><option value="4">左节点</option><option value="5">右节点</option></select></label><label>水平视角 <input id="yaw" type="range" min="-180" max="180" value="-25"></label><label>俯仰视角 <input id="pitch" type="range" min="-85" max="85" value="50"></label><button id="reset">恢复默认视图</button><label><input id="active" type="checkbox"> 演示已有的「滑翔起效」提示</label><p id="passive"><strong>被动翼 · 无能源读数</strong></p><p class="note">此开关只演示提示。实际状态须读取游戏的翼生效标记；翼面始终保持固定，不增加扇动或发光。</p><p class="note">六向使用现有节点坐标，不新增安装旋转规则。顶/底安装会将翼面转到竖直方向；是否起效沿用当前游戏判定。</p></aside></main>
<h2>原生物品图标</h2><section class="panel"><div class="icons"><figure><img id="icon32" class="pixel"><figcaption>32×32 · 分层源稿</figcaption></figure><figure><img id="icon16" class="pixel"><figcaption>16×16 · 独立绘制</figcaption></figure></div><p class="note">分别设计轮廓、布面明暗与木铜结构。没有从大图缩小，也没有将32像素图压成16像素图。</p></section>
<h2>实际模型渲染 · 六向装配</h2><section id="mounts" class="grid"></section>
<h2>材质复用</h2><section class="panel atlas"><img id="atlas"><p class="note">128×64图集：左侧保留完整机械64×64像素；右侧直接复用滑翔伞的四块32×32布木区域。像素未重采样，单张图集绑定模型。</p></section>
<h2>审稿板</h2><section class="panel"><canvas id="board"></canvas><p class="note">板中展示实际交付模型，不以生图概念参考代替模型。</p><a href="wing-review.png">打开审稿板 PNG</a></section>
<p class="note">存档包含 Blender、Blockbench、Aseprite、PNG、模型/UV规范与验证记录。仅美术产出，原有Java与dev.14保持原样。</p>
<script>const GEOMETRY=__G__, SOURCES=__IMAGES__;</script><script>__RENDER__</script><script>
const loaded={};window.reviewReady=false;const names=['顶','底','后','前','左','右'];
function redraw(){const n=+document.querySelector('#node').value;window.lastRender=WildcraftWingPreview.drawModel(document.querySelector('#live'),loaded['wing-atlas-128x64.png'],GEOMETRY,0,+document.querySelector('#yaw').value,+document.querySelector('#pitch').value,n);document.querySelector('#render-info').textContent=`28个固定部件 · 原始比例 · ${n<0?'翼面本体':names[n]+'节点 + 已采用机体'} · 共用纹理图集`;document.querySelector('#passive').innerHTML=document.querySelector('#active').checked?'<strong>滑翔起效 · 不消耗电量</strong>':'<strong>被动翼 · 无能源读数</strong>';}
for(const id of ['node','yaw','pitch','active'])document.querySelector('#'+id).addEventListener('input',redraw);
document.querySelector('#reset').onclick=()=>{document.querySelector('#node').value='-1';document.querySelector('#yaw').value=-25;document.querySelector('#pitch').value=50;document.querySelector('#active').checked=false;redraw()};
function board(){const c=document.querySelector('#board');c.width=1200;c.height=1730;const x=c.getContext('2d');x.fillStyle='#14221c';x.fillRect(0,0,c.width,c.height);const text=(s,px,py,size=22,col='#e7dec3')=>{x.font=`${size}px system-ui`;x.fillStyle=col;x.fillText(s,px,py)};const image=(name,px,py,w,h,nearest=false)=>{x.imageSmoothingEnabled=!nearest;x.drawImage(loaded[name],px,py,w,h)};text('WILDCRAFT · F05-02 / v01',40,54,22,'#93b39e');text('机械翼 · 布木被动滑翔面',40,106,38);text('草稿待审  /  原生32与16图标  /  未接入游戏',40,145,20,'#b1bca8');
image('wing-three-quarter.png',40,174,640,640);image('wing-top.png',742,174,418,418);text('实际模型 · 俯视',758,624,20);image('wing-item-32.png',782,655,128,128,true);image('wing-item-16.png',992,655,128,128,true);text('32×32',804,816,20);text('16×16',1015,816,20);text('六向安装参考 · 使用现有节点旋转，保持1.00比例',40,865,24);
for(let i=0;i<6;i++){const px=40+(i%3)*382,py=892+Math.floor(i/3)*355;image('wing-mounted-'+i+'.png',px+23,py,310,310);text(names[i]+'节点',px+12,py+338,20)}
text('材料复用：机械接口 + 滑翔伞布木像素 → 一张128×64图集',40,1647,22);text('无耗电、无扇动、无发光；模型与源稿已保存，游戏表现仍待接入验证。',40,1690,19,'#b1bca8');}
(async()=>{for(const [name,src]of Object.entries(SOURCES)){const im=new Image();im.src=src;await im.decode();loaded[name]=im;}document.querySelector('#icon32').src=SOURCES['wing-item-32.png'];document.querySelector('#icon16').src=SOURCES['wing-item-16.png'];document.querySelector('#atlas').src=SOURCES['wing-atlas-128x64.png'];document.querySelector('#mounts').innerHTML=names.map((n,i)=>`<figure><img alt="${n}节点装配" src="${SOURCES['wing-mounted-'+i+'.png']}"><figcaption>${n}节点 · 固定原尺寸</figcaption></figure>`).join('');redraw();board();window.reviewReady=true;})().catch(e=>{document.querySelector('#render-info').textContent=e.message;window.reviewError=e.message;});
</script></html>'''
html=html.replace('__G__',json.dumps(G,separators=(',',':'),ensure_ascii=False)).replace('__IMAGES__',json.dumps(images,separators=(',',':'))).replace('__RENDER__',s)
(R/'review/preview.html').write_text(html)
print('Self-contained actual mesh review ready.')
