(function(root){
function rotate(v,n){const [x,y,z]=v;return [[x,z,-y],[x,-z,y],[-x,y,-z],[x,y,z],[-z,y,x],[z,y,-x]][n];}
function rotorPoint(v,angle,pivot){const [x,y,z]=v,c=Math.cos(angle),s=Math.sin(angle);return [x*c-y*s,x*s+y*c,z];}
function mount(v,node,g){return node<0?v:rotate(v,node).map((a,i)=>a+g.body.nodes[node].point[i]);}
function rawBox(p,g){const [x0,y0,z0]=p.from,[x1,y1,z1]=p.to,vs=[[x0,y0,z0],[x1,y0,z0],[x1,y1,z0],[x0,y1,z0],[x0,y0,z1],[x1,y0,z1],[x1,y1,z1],[x0,y1,z1]],fm={north:[0,1,2,3],south:[5,4,7,6],east:[1,5,6,2],west:[4,0,3,7],up:[3,2,6,7],down:[4,5,1,0]};return {name:p.name,vertices:p.node===undefined?vs:vs.map(v=>mount(v,p.node,g)),faces:Object.entries(fm).map(([key,indices])=>{const [u0,v0,u1,v1]=p.faces[key].uv;return {indices,uvs:[[u0/2,v1],[u1/2,v1],[u1/2,v0],[u0/2,v0]]}})};}
function makeFaces(g,angle=0,node=-1){const parts=g.parts.map(p=>({...p,vertices:p.vertices.map(v=>mount(p.group==='rotor'?rotorPoint(v,angle,g.rotorPivot):v,node,g))}));if(node>=0)parts.push(...g.body.parts.map(p=>rawBox(p,g)));const out=[];for(const p of parts){const center=[0,1,2].map(i=>p.vertices.reduce((s,v)=>s+v[i],0)/p.vertices.length);for(const f of p.faces){const points=f.indices.map(i=>p.vertices[i]),a=points[1].map((v,i)=>v-points[0][i]),b=points[2].map((v,i)=>v-points[0][i]);let normal=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],len=Math.hypot(...normal);normal=normal.map(v=>v/len);const fc=[0,1,2].map(i=>points.reduce((s,v)=>s+v[i],0)/points.length);if(normal.reduce((s,v,i)=>s+v*(fc[i]-center[i]),0)<0)normal=normal.map(v=>-v);out.push({name:p.name,vertices:points,normal,uvs:f.uvs});}}return out;}
function angleFor(age,active,ghost=false){return 0;}
function drawModel(canvas,atlas,geo,angle=0,yaw=-25,pitch=18,node=-1){
canvas.width=640;canvas.height=450;let cache=canvas._batteryGl;
if(!cache){const gl=canvas.getContext('webgl',{preserveDrawingBuffer:true,alpha:false,antialias:true});if(!gl)throw new Error('Review WebGL unavailable');
 const shader=(type,code)=>{const sh=gl.createShader(type);gl.shaderSource(sh,code);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(sh));return sh;};
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 position; attribute vec2 uv; attribute float shade; varying vec2 vUv; varying float vShade; void main(){gl_Position=vec4(position,1.0);vUv=uv;vShade=shade;}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float; varying vec2 vUv; varying float vShade; uniform sampler2D atlas; void main(){vec4 c=texture2D(atlas,vUv);if(c.a<0.5)discard;gl_FragColor=vec4(c.rgb*vShade,1.0);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));
 const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,atlas);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
 cache=canvas._batteryGl={gl,program,texture,buffer:gl.createBuffer(),locations:['position','uv','shade'].map(k=>gl.getAttribLocation(program,k))};}
const {gl,program,texture,buffer,locations}=cache;gl.viewport(0,0,640,450);gl.clearColor(.094,.137,.114,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.useProgram(program);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(gl.getUniformLocation(program,'atlas'),0);
const ya=yaw*Math.PI/180,pa=pitch*Math.PI/180,cy=Math.cos(ya),sy=Math.sin(ya),cp=Math.cos(pa),sp=Math.sin(pa);const transform=(v,position)=>{let [x,y,z]=v;if(position){}const xx=x*cy+z*sy,zz=z*cy-x*sy;return [xx,-y*cp+zz*sp,y*sp+zz*cp];};
const faces=makeFaces(geo,angle,node).map(f=>({...f,normal:transform(f.normal,false),points:f.vertices.map(v=>transform(v,true))})).filter(f=>f.normal[2]>.001),data=[];
const allPoints=faces.flatMap(f=>f.points),xs=allPoints.map(p=>p[0]),ys=allPoints.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),fit={scale:Math.min(48,580/(maxX-minX),390/(maxY-minY)),cx:(minX+maxX)/2,cy:(minY+maxY)/2};canvas._machineProjection=fit;for(const face of faces){const light=Math.max(.48,Math.min(1,.58+face.normal[0]*.15-face.normal[1]*.22+face.normal[2]*.25));for(let i=1;i<face.points.length-1;i++)for(const idx of [0,i,i+1]){const p=face.points[idx],[u,v]=face.uvs[idx];data.push(-(p[0]-fit.cx)*fit.scale/320,-(p[1]-fit.cy)*fit.scale/225,-p[2]/64,u/16,1-v/16,light);}}
gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.DYNAMIC_DRAW);for(let i=0;i<3;i++){gl.enableVertexAttribArray(locations[i]);gl.vertexAttribPointer(locations[i],[3,2,1][i],gl.FLOAT,false,24,[0,12,20][i]);}gl.drawArrays(gl.TRIANGLES,0,data.length/6);
return {angle,node,visibleFaces:faces.length,wingParts:geo.parts.length,movingParts:geo.parts.filter(p=>p.group==='rotor').length,fixedParts:geo.parts.filter(p=>p.group==='housing').length,referenceBody:node>=0,depthTest:true,fit};
}
root.WildcraftWingPreview={rotate,mount,rotorPoint,makeFaces,angleFor,drawModel};})(globalThis);
