from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1];G=json.loads((R/'source/geometry-and-uv.json').read_text())
js=(R/'references/F05-01-machine-preview.js').read_text().replace('function makeFaces(geo,e,node=-1)','function localFaces(geo,e,node=-1)')
addition=r'''
function rootMotion(v,yaw=0,roll=0){const a=-yaw*Math.PI/180,b=roll*Math.PI/180,[x,y,z]=v,xx=x*Math.cos(b)-y*Math.sin(b),yy=x*Math.sin(b)+y*Math.cos(b);return [xx*Math.cos(a)+z*Math.sin(a),yy,-xx*Math.sin(a)+z*Math.cos(a)];}
function makeFaces(geo,e,node=-1){const gap=geo.reviewGap||0,normal=node>=0?geo.nodes[node].normal:[0,0,0];return localFaces(geo,e,node).map(f=>({...f,vertices:f.vertices.map(p=>rootMotion(p.map((v,i)=>v+(f.name.startsWith('battery/')||f.name.startsWith('energy/')?normal[i]*gap:0)),geo.bodyYaw,geo.bodyRoll)),normal:rootMotion(f.normal,geo.bodyYaw,geo.bodyRoll)}));}
'''
js=js.replace('function project(',addition+'\nfunction project(')
js=js.replace('for(const face of faces){const','for(const face of faces){if(geo.reviewOutline&&(face.name.startsWith("battery/")||face.name.startsWith("energy/")))continue;const')
js=js.replace('makeFaces,drawModel,project','makeFaces,drawModel,project,rootMotion')
(R/'source/battery-mount-preview.js').write_text(js)
names=['mount-'+str(i)+'.png' for i in range(6)]+['empty.png','exploded.png','energy-0.png','energy-99.png','energy-500.png','energy-1000.png']
images={n:'data:image/png;base64,'+base64.b64encode((R/'review'/n).read_bytes()).decode() for n in names}
images['atlas']='data:image/png;base64,'+base64.b64encode((R/'references/F05-01-machine-atlas-64.png').read_bytes()).decode()
html=r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · 电池六节点安装适配</title><style>
*{box-sizing:border-box}body{background:#15251c;color:#e5eadd;margin:0;font:15px/1.8 system-ui,"PingFang SC",sans-serif}main{max-width:1220px;margin:auto;padding:28px 22px}h1{font-size:30px;margin:8px 0}h2{font-size:20px;margin:0 0 12px}p{color:#b8c8b2}small,.small{font-size:13px;color:#aabda3}.tag,.note{color:#dfb877}.controls,.panel{background:#263a2b;border:1px solid #486348;padding:16px;border-radius:6px}.controls{display:flex;gap:16px;flex-wrap:wrap}label{display:flex;align-items:center;gap:6px}select,input{background:#192a20;color:#e5eadd;border:1px solid #62795a;padding:5px;accent-color:#bd734c}input[type=range]{width:120px}button{background:#314a35;color:#e5eadd;border:1px solid #62795a;padding:8px 12px;border-radius:4px;cursor:pointer}:focus-visible{outline:3px solid #dfb877;outline-offset:3px}.poses{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.row{display:grid;grid-template-columns:1.15fr 1fr;gap:20px;margin:18px 0}.stage{position:relative}.stage canvas{width:100%;display:block}#overlay{position:absolute;inset:0;pointer-events:none}.panel img,.board{width:100%;height:auto}.gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.gallery figure{margin:0;background:#263a2b;padding:12px;border:1px solid #486348}.gallery img{width:100%}.gallery figcaption{color:#ccb993}a{color:#9fd3bd}table{border-collapse:collapse;width:100%;font-size:14px}td,th{text-align:left;border-bottom:1px solid #486348;padding:7px}@media(max-width:900px){.row{grid-template-columns:1fr}.gallery{grid-template-columns:repeat(2,1fr)}main{padding:20px 14px}}
</style><main><span class="tag">F05-05 · v01 · 草稿待审 · 未接入游戏</span><h1>同一块电池 · 六个安装方向</h1><p>沿用已采用电池、机械主体与材质。比例始终1.00；安装偏移对齐原电池背面低位铜触点，电量窗口跟随实际余量。下面六张图是六个独立场景，每台仅装一块电池。</p>
<div class="controls"><label>节点<select id="node"><option value="0">顶节点</option><option value="1">底节点</option><option value="2">后节点</option><option value="3" selected>前节点</option><option value="4">左节点</option><option value="5">右节点</option></select></label><label>查看状态<select id="mode"><option value="installed">安装完成</option><option value="outline">安装轮廓参考</option><option value="exploded">拆出方向参考</option><option value="empty">移除后空主体</option></select></label><label>电量<input id="energy" type="range" min="0" max="1000" value="500"><output id="value"></output></label><label>视角<input id="yaw" type="range" min="-180" max="180" value="-25"></label><label>俯仰<input id="pitch" type="range" min="-85" max="85" value="24"></label><label>主体朝向<select id="bodyYaw"><option>0</option><option>90</option><option>180</option><option>270</option></select></label><label>主体倾斜<select id="bodyRoll"><option>0</option><option>-6</option><option>6</option></select></label></div>
<div class="poses"><button id="face">看电量窗口</button><button id="iso">斜侧面</button><button id="top">顶面与控制板</button><button id="bottom">底部</button><button data-e="0">空电</button><button data-e="99">99 / 1000</button><button data-e="500">半电</button><button data-e="1000">满电</button></div>
<div class="row"><section class="panel"><h2>实际几何 · 自由查看</h2><div class="stage"><canvas id="model" width="640" height="450" role="img" aria-label="可切换六个方向的电池安装模型"></canvas><canvas id="overlay" width="640" height="450" aria-hidden="true"></canvas></div><p id="reading" aria-live="polite"></p><p class="small">轮廓和拆出间距仅作位置审稿，不新增游戏菜单或拆卸动画；安装、回收与电量仍由服务器真实数据决定。</p></section><section class="panel"><h2>当前节点 · 实际模型渲染</h2><img id="render" alt="当前方向的电池安装实景渲染"><p class="small">静态渲染余量500 / 1000；左侧模型跟随输入。底节点采用悬空视角查看，原主体碰撞没有扩张。</p></section></div>
<section class="panel"><h2>触点对齐与间隙</h2><table><tr><th>检查项</th><th>本次结果</th></tr><tr><td>原电池尺寸与比例</td><td>0.400 × 0.460 × 0.121 方块；比例1.00，模型和纹理复用</td></tr><tr><td>安装偏移（模型单位）</td><td>X −8 / Y −6.1 / Z −6.57；再做节点旋转与位移</td></tr><tr><td>两枚铜触点</td><td>各0.30 × 1.40模型单位重叠，表面相接</td></tr><tr><td>顶节点与控制板</td><td>电池前缘距控制板0.209方块</td></tr><tr><td>底节点与地面</td><td>电池伸出主体底面0.159方块；六向外观检查通过，落地穿插待游戏接入解决</td></tr></table><p class="note">对齐触点需要沿电池长边上移；这不是缩放。外壳与接口边缘有≤0.003125方块的贴合嵌入。电池朝向跟随整机，窗口位于接口外侧；背面、底面等视角会自然被主体遮挡。</p></section>
<h2 style="margin-top:28px">六个独立装配场景</h2><div id="gallery" class="gallery"></div><p class="note">每台最多一块电池，停机且目标节点空闲才能安装或回收。回收保留电量，背包需有空间。可见电池外表面不等于扩大后的点击范围；交互继续使用现主体碰撞和节点规则。</p><canvas id="board" class="board" width="1200" height="1620"></canvas><p class="small">完整交付与接入规范见对话中的文件入口。</p></main>
<script>__JS__</script><script>
const G=__G__,sources=__IMAGES__,assets={},M=WildcraftMachinePreview,$=id=>document.getElementById(id),views=[[0,75],[0,-75],[180,0],[0,0],[90,0],[-90,0]];
function update(){let n=+$('node').value,e=+$('energy').value,mode=$('mode').value;G.bodyYaw=+$('bodyYaw').value;G.bodyRoll=+$('bodyRoll').value;G.reviewGap=mode==='exploded'?6:0;G.reviewOutline=mode==='outline';const node=mode==='empty'?-1:n,yaw=+$('yaw').value,pitch=+$('pitch').value,info=M.drawModel($('model'),assets.atlas,G,e,yaw,pitch,node);$('energy').disabled=mode==='empty';$('value').textContent=mode==='empty'?'— / 1000':e+' / 1000';$('reading').textContent=G.nodes[n].name+'节点 · '+$('mode').selectedOptions[0].textContent+' · 原电池比例1.00'+(mode==='empty'?'':(' · '+e+' / 1000'));$('render').src=sources['mount-'+n+'.png'];const c=$('overlay').getContext('2d');c.clearRect(0,0,640,450);if(mode==='outline'){c.strokeStyle='#ddb778';c.lineWidth=1.2;c.setLineDash([4,4]);for(const f of M.makeFaces(G,e,n).filter(f=>f.name.startsWith('battery/'))){c.beginPath();f.vertices.forEach((v,i)=>{const p=M.project(v,yaw,pitch,$('model')._machineProjection);i?c.lineTo(...p):c.moveTo(...p)});c.closePath();c.stroke()}c.setLineDash([])}window.currentState={node:n,mode,e,yaw,pitch,bodyYaw:G.bodyYaw,bodyRoll:G.bodyRoll,info};}
function board(){const c=$('board').getContext('2d');c.fillStyle='#15251c';c.fillRect(0,0,1200,1620);const t=(s,x,y,size=18,col='#e2e9dc')=>{c.font=size+'px system-ui,"PingFang SC"';c.fillStyle=col;c.textBaseline='top';c.fillText(s,x,y)};const box=(x,y,w,h)=>{c.fillStyle='#263a2b';c.fillRect(x,y,w,h);c.strokeStyle='#486348';c.strokeRect(x+.5,y+.5,w-1,h-1)};t('WILDCRAFT / BATTERY MOUNT ADAPTATION',30,24,16,'#a9be9e');t('同一块电池 · 六节点安装适配',30,58,33);t('F05-05 v01 · 草稿待审 · 比例1.00 · 实际模型渲染 · 未接入游戏',30,109,17,'#dfb877');
for(let n=0;n<6;n++){const x=30+n%3*390,y=154+Math.floor(n/3)*373;box(x,y,360,355);t(G.nodes[n].name+'节点 · 外侧电量窗口',x+15,y+15,19);c.drawImage(assets['mount-'+n+'.png'],x+10,y+49,340,300)}
t('触点对齐 · 原尺寸保持',30,922,25);t('安装偏移 X −8 / Y −6.1 / Z −6.57，再沿现节点旋转与位移。',30,965,18);t('两枚铜触点各重叠0.30 × 1.40模型单位；主体与电池纹理均原样复用。',30,1001,18,'#b8cbb0');
for(let i=0;i<4;i++){const k=['energy-0.png','energy-99.png','energy-500.png','energy-1000.png'][i],x=30+i*292;box(x,1056,264,300);t(['0 / 1000','99 / 1000','500 / 1000','1000 / 1000'][i],x+15,1070,20);c.drawImage(assets[k],x+5,1110,254,235)}
t('窗口按余量从底到顶连续填充；六向共用同一组几何与材质。',30,1381,19);t('顶面电池与控制板留0.209方块间隙；每台只装一块电池。',30,1417,19);t('底部电池伸出0.159方块；本图底装为悬空检查，落地效果仍待游戏实测。',30,1464,18,'#dfb877');t('安装、回收、点击仍遵循现有规则；本轮交付美术适配，不修改碰撞或Java。',30,1504,18,'#b8cbb0');t('复用F04-01电池 + F05-01主体  /  0新增贴图、图标或电池外观',30,1566,17,'#dfb877');}
window.ready=(async()=>{await Promise.all(Object.entries(sources).map(async([k,src])=>{let im=new Image();im.src=src;await im.decode();assets[k]=im}));for(const id of ['node','mode','bodyYaw','bodyRoll'])$(id).onchange=update;for(const id of ['energy','yaw','pitch'])$(id).oninput=update;$('node').onchange=()=>{const [a,b]=views[+$('node').value];$('yaw').value=a;$('pitch').value=b;update()};$('face').onclick=()=>{const [a,b]=views[+$('node').value];$('yaw').value=a;$('pitch').value=b;$('bodyYaw').value=0;$('bodyRoll').value=0;update()};for(const [id,a,b]of [['iso',-25,24],['top',0,85],['bottom',-25,-65]])$(id).onclick=()=>{$('yaw').value=a;$('pitch').value=b;update()};document.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{$('energy').value=b.dataset.e;update()});$('gallery').innerHTML=G.nodes.map(n=>'<figure><img src="'+sources['mount-'+n.id+'.png']+'" alt="'+n.name+'节点独立装配"><figcaption>'+n.id+' · '+n.name+'节点 · 500 / 1000'+(n.id===1?' · 悬空检查':'')+'</figcaption></figure>').join('');update();board();window.appReady=true;return true})();
</script></html>'''
(R/'review/preview.html').write_text(html.replace('__JS__',js).replace('__G__',json.dumps(G)).replace('__IMAGES__',json.dumps(images)))
print('Self-contained six-node review and board created')
