from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1]
def image(p):return 'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
G=json.loads((R/'source/geometry-and-uv.json').read_text());G['body']=json.loads((R/'references/approved-machine-geometry.json').read_text())
images={p.name:image(p)for folder in ['review','exports']for p in (R/folder).glob('*.png')if 'review'not in p.name}
S=[dict(id='dry',label='陆地 · 无浮力',fluid='air',waterHeight=0,mass=1.1,active=False),dict(id='shallow',label='浅水 · 有限浮力',fluid='water',waterHeight=.1,waterY=2,mass=1.1,active=True),dict(id='water',label='水中 · 载重范围内',fluid='water',waterHeight=.4,waterY=4,mass=1.1,active=True),dict(id='threshold',label='载重1.75 · 临界仍有效',fluid='water',waterHeight=.4,waterY=4,mass=1.75,active=True),dict(id='overload',label='载重1.85 · 超载无浮力',fluid='water',waterHeight=.4,waterY=8.64,mass=1.85,active=False),dict(id='disabled',label='整机关闭/无电 · 被动浮力仍有效',fluid='water',waterHeight=.4,waterY=4,mass=1.1,enabled=False,energy=0,active=True),dict(id='lava',label='岩浆 · 不提供浮力',fluid='lava',waterHeight=0,mass=1.1,active=False),dict(id='ghost',label='水中安装预览 · 不提供浮力',fluid='water',waterHeight=.4,waterY=4,mass=1.1,active=False,ghost=True)]
(R/'source/review-snapshots.json').write_text(json.dumps(S,ensure_ascii=False,indent=2)+'\n')
css=''' :root{color-scheme:dark;background:#14221c;color:#e7dec3;font:16px system-ui}*{box-sizing:border-box}body{max-width:1240px;margin:auto;padding:30px 24px}h1{font-size:32px}h2{font-size:22px;margin-top:32px}p{line-height:1.7;color:#bdc9b7}small{color:#93b39e}main{display:grid;grid-template-columns:minmax(0,2fr) minmax(240px,1fr);gap:20px}.panel,figure{background:#1c2d24;border:1px solid #354b3c;border-radius:14px;padding:18px;margin:0}canvas,img{max-width:100%;height:auto}canvas{width:100%;display:block}select,button{font:inherit;background:#304738;color:#eee4ca;border:1px solid #59755e;border-radius:6px;padding:10px;max-width:100%}label{display:block;margin:16px 0}input{width:100%}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}figcaption{font-size:13px;line-height:1.7}.icons{display:flex;gap:36px;flex-wrap:wrap}.pixel{image-rendering:pixelated}.icons img{width:160px;background:#14221c}.note{font-size:13px}.chips{display:flex;gap:12px;flex-wrap:wrap}.chips span{background:#304738;padding:8px;border-radius:6px}a{color:#a3ddbb}@media(max-width:800px){main{grid-template-columns:1fr}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}body{padding:24px 14px}h1{font-size:27px}}'''
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · F05-09 浮力装置 v01</title><style>__CSS__</style><header><small>WILDCRAFT / B3 · F05-09</small><h1>浮力装置 · 浅色浮体与中央束带</h1><p>横向倒角浮体、铜色束带与钢扣，背面保留现有节点安装板。被动水中部件，通过形态表达用途。</p><div class="chips"><span>v01 草稿待审</span><span>复用已采用128×64图集</span><span>未接入游戏</span></div></header><h2>实际网格与水线对照</h2><main><section class="panel"><canvas id="live" aria-label="浮力装置模型与装配参考"></canvas><p id="render-info" class="note"></p></section><aside class="panel"><label>场景参考<select id="snapshot"></select></label><label>安装视图<select id="node"><option value="-1">独立部件</option><option value="0">顶节点</option><option value="1">底节点</option><option value="2">后节点</option><option value="3" selected>前节点</option><option value="4">左节点</option><option value="5">右节点</option></select></label><label>水平视角<input id="yaw" type="range" min="-180" max="180" value="-25"></label><label>俯仰视角<input id="pitch" type="range" min="-85" max="85" value="18"></label><button id="reset">恢复默认视图</button><p id="readout"></p><p class="note">水面是装配审稿参考，不计算平衡水线或模拟真实浮沉。实际浮力依据机械主体的WATER浸水高度与总载重，未按浮体模型体积改变碰撞。</p><p class="note">没有工作灯、变形或新粒子。整机关闭/无电仍可获得被动浮力；安装预览不参与载重与浮力。</p></aside></main><h2>可编辑模型 · 实际渲染</h2><section id="views" class="grid"></section><h2>原生物品图标</h2><section class="panel"><div id="icons" class="icons"></div><p class="note">32×32与16×16分别绘制，保留浅色厚浮体、中央束带与钢扣；可编辑三层源稿，没有缩小概念图充当像素资产。</p></section><h2>六向安装</h2><section id="mounts" class="grid"></section><h2>水中辨识与遮挡</h2><section id="water" class="grid"></section><p class="note">水线与深浸水仅作视觉参考，不承诺某个载重对应固定水面。底装伸出主体碰撞箱，保持现有主体碰撞；实际水下观感与地面穿插待游戏验证。</p><h2>统一图集</h2><section class="panel"><img id="atlas" class="pixel" width="512"><p class="note">原样复用已采用机械翼128×64图集，含机械金属及浅色材质。新增生产纹理像素0，无湿润变体或动画贴图。</p></section><h2>综合审稿板</h2><section class="panel"><canvas id="board"></canvas><a href="buoyancy-review.png">打开审稿板 PNG</a></section><p class="note">本轮仅制作美术。模型、源稿、导出和场景参考已保存；本项待用户采用，游戏接入与全件组合复核尚未完成。</p><script>const G=__G__,SOURCES=__IMAGES__,SNAPSHOTS=__SNAPSHOTS__;</script><script>__RENDER__</script><script>
const loaded={},names=['顶','底','后','前','左','右'];window.reviewReady=false;
function current(){return SNAPSHOTS.find(s=>s.id===document.querySelector('#snapshot').value)||SNAPSHOTS[0]}
function redraw(){const s=current(),p=WildcraftBuoyancyPreview.presentation(s),n=+document.querySelector('#node').value;window.lastPresentation=p;window.lastRender=WildcraftBuoyancyPreview.drawModel(document.querySelector('#live'),loaded[G.texture],{...G,...p},+document.querySelector('#yaw').value,+document.querySelector('#pitch').value,n);document.querySelector('#render-info').textContent=`${s.label} · ${n<0?'独立部件':names[n]+'节点'} · 模型固定`;document.querySelector('#readout').textContent=`${p.ghost?'安装预览':p.active?'参考：水中被动浮力有效':'参考：当前不提供浮力'}。单件上限1.75；当前场景总载重${s.mass}。耗电0。${s.id==='overload'?'超载不会改成红灯或变形。':''}`;}
for(const id of ['snapshot','node','yaw','pitch'])document.querySelector('#'+id).addEventListener('input',redraw);document.querySelector('#reset').onclick=()=>{document.querySelector('#snapshot').value='water';document.querySelector('#node').value=3;document.querySelector('#yaw').value=-25;document.querySelector('#pitch').value=18;redraw()};
function board(){const c=document.querySelector('#board');c.width=1200;c.height=1820;const x=c.getContext('2d');x.fillStyle='#14221c';x.fillRect(0,0,c.width,c.height);const text=(s,a,b,size=22,col='#e7dec3')=>{x.fillStyle=col;x.font=`${size}px system-ui`;x.fillText(s,a,b)},image=(n,a,b,w,h,pixel=false)=>{x.imageSmoothingEnabled=!pixel;x.drawImage(loaded[n],a,b,w,h)};
text('WILDCRAFT · F05-09 / v01',40,50,22,'#93b39e');text('浮力装置 · 浅色浮体与中央束带',40,101,36);text('草稿待审 / 原生32与16分别绘制 / 未接入游戏',40,141,19,'#b1bca8');image('buoyancy-three-quarter.png',40,175,440,440);image('buoyancy-waterline.png',510,175,310,310);image('buoyancy-submerged-reference.png',850,175,310,310);text('同一固定浮体',60,651,22);text('水线参考 · 不计算平衡水位',530,529,19);text('深浸水 · 仅遮挡参考',860,529,19);
image('buoyancy-item-32.png',560,570,144,144,true);image('buoyancy-item-16.png',850,570,144,144,true);text('32×32独立像素稿',540,750,20);text('16×16独立像素稿',830,750,20);
text('六向安装 · 原节点与外形范围',40,811,25);for(let i=0;i<6;i++){const a=40+i%3*383,b=840+Math.floor(i/3)*340;image('buoyancy-mounted-'+i+'.png',a+18,b,300,300);text(names[i]+'节点',a+20,b+319,20)}
text('被动水中浮力 · 不耗电 · 单件最多支持1.75载重',40,1580,24);text('浮体与束带固定，无工作灯、变形、动画贴图或新粒子。',40,1630,22);text('复用已采用128×64图集，新增生产纹理像素0。',40,1678,22);text('水线是审稿参考；保留主体碰撞与现有总载重规则。',40,1726,22);text('实际游戏安装、水下观感、底装与组合待接入验证。',40,1774,21,'#b1bca8');}
(async()=>{for(const[n,src]of Object.entries(SOURCES)){const im=new Image();im.src=src;await im.decode();loaded[n]=im;}document.querySelector('#snapshot').innerHTML=SNAPSHOTS.map(s=>`<option value="${s.id}">${s.label}</option>`).join('');document.querySelector('#snapshot').value='water';const figures=(id,items)=>{document.querySelector('#'+id).innerHTML=items.map(([file,label])=>`<figure><img alt="${label}" src="${SOURCES[file]}"><figcaption>${label}</figcaption></figure>`).join('')};figures('views',[['buoyancy-three-quarter.png','斜视 · 浅色浮体与束带'],['buoyancy-front.png','正面 · 中央钢扣'],['buoyancy-back.png','背面 · 机械安装板']]);figures('mounts',names.map((n,i)=>['buoyancy-mounted-'+i+'.png',n+'节点']));figures('water',[['buoyancy-waterline.png','水线参考'],['buoyancy-submerged-reference.png','深浸水遮挡参考'],['buoyancy-side.png','侧面 · 浮体厚度']]);document.querySelector('#icons').innerHTML=[32,16].map(n=>`<figure><img class="pixel" alt="浮力装置${n}像素" src="${SOURCES['buoyancy-item-'+n+'.png']}"><figcaption>${n}×${n} · 独立源稿</figcaption></figure>`).join('');document.querySelector('#atlas').src=SOURCES[G.texture];redraw();board();window.reviewReady=true;})().catch(e=>{window.reviewError=e.message;document.querySelector('#render-info').textContent=e.message});
</script></html>'''
html=html.replace('__CSS__',css).replace('__G__',json.dumps(G,separators=(',',':'),ensure_ascii=False)).replace('__IMAGES__',json.dumps(images,separators=(',',':'))).replace('__SNAPSHOTS__',json.dumps(S,separators=(',',':'),ensure_ascii=False)).replace('__RENDER__',(R/'source/buoyancy-preview.js').read_text());(R/'review/preview.html').write_text(html);print('Review page prepared')
