from pathlib import Path
import json,base64
r=Path(__file__).resolve().parents[1]
images={p.stem:'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode() for p in (r/'review').glob('*.png') if p.stem.split('-')[0] in ['sword','axe','shield','arrow','flight','hand'] and '-gui-' not in p.stem}
spec=json.loads((r/'source/mount-spec.json').read_text());mesh=json.loads((r/'source/reference-meshes.json').read_text());back=json.loads((r/'references/adopted-back-layout.json').read_text())
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · Fuse 挂点 v01</title><style>
:root{color-scheme:dark;--bg:#0d1815;--card:#14241f;--border:#34443a;--text:#eee8d3;--muted:#a7b6a8;--accent:#e1b972}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.65 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}main{max-width:1320px;margin:auto;padding:34px 24px}h1{margin:5px 0 10px;font-size:32px;line-height:1.3}h2{margin:0 0 15px;font-size:20px}p{margin:10px 0}.eyebrow{color:var(--accent);font-size:13px;letter-spacing:2px}.muted{color:var(--muted)}.tag{display:inline-block;border:1px solid #687449;border-radius:30px;padding:3px 13px;color:#e6d29a;font-size:13px}.grid{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(300px,1fr);gap:20px;margin:25px 0}.card{background:var(--card);border:1px solid var(--border);border-radius:15px;padding:22px;min-width:0}#view{width:100%;aspect-ratio:1;height:auto;display:block;border-radius:8px;touch-action:none}label{display:block;color:var(--muted);font-size:14px;margin:13px 0 5px}select{width:100%;padding:10px;background:#0d1815;color:var(--text);border:1px solid #647364;border-radius:6px;font:inherit}input[type=range]{width:100%;accent-color:var(--accent)}button{cursor:pointer;padding:8px 15px;border:1px solid #71836c;border-radius:6px;background:#294036;color:var(--text);font:inherit;min-height:40px}button:hover{background:#3a5143}button:focus-visible,select:focus-visible,input:focus-visible,a:focus-visible{outline:3px solid var(--accent);outline-offset:3px}.buttons{display:flex;flex-wrap:wrap;gap:8px;margin:15px 0}.smallrow{display:flex;gap:25px;align-items:flex-end;margin-top:20px}.pixel{image-rendering:pixelated;border:1px solid #405847;width:128px;height:128px}.pixelwrap{font-size:13px;color:var(--muted);text-align:center}.rule{border-left:3px solid var(--accent);padding-left:13px;margin:20px 0}.board{width:100%;height:auto;border-radius:10px;display:block}a{color:#e3c286}#note{color:#c6d5c0;font-size:14px;min-height:75px}.meta{font-size:13px}.sideframe{width:100%;height:auto;border-radius:7px}.reference{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.reference img{width:100%;border-radius:7px}.reviewlinks{display:flex;gap:20px;flex-wrap:wrap}@media(max-width:900px){.grid{grid-template-columns:1fr}.reference{grid-template-columns:1fr}main{padding:24px 14px}h1{font-size:27px}.card{padding:16px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}
</style><main><div class="eyebrow">WILDCRAFT / F03-01</div><h1>Fuse 通用组合外观与挂点</h1><span class="tag">v01 · 待审稿</span><p class="muted">保留宿主与材料的原版外观，分别安排剑、斧、盾、箭的附着位置。</p>
<div class="grid"><section class="card"><h2>旋转查看组合</h2><canvas id="view" width="700" height="700" aria-label="融合组合三维参考"></canvas><p class="muted meta">拖动模型旋转，或使用右侧角度滑块。这里是原版像素轮廓参考，不是游戏截图。</p></section><section class="card"><h2>选择检查场景</h2><label for="host">宿主</label><select id="host"><option value="sword">剑 · 剑刃前端</option><option value="axe">斧 · 斧头</option><option value="shield">盾 · 上缘</option><option value="arrow">箭 · 箭尖</option></select><label for="material">材料</label><select id="material"><option value="stone">石头 · 方块材料</option><option value="diamond">钻石 · 扁平材料</option><option value="feather">羽毛 · 细长材料</option></select><label for="context">展示场景</label><select id="context"><option value="inventory">物品外观</option><option value="held">手持参考</option><option value="back">背负参考</option><option value="ground">掉落物参考</option><option value="flight">飞箭参考（仅箭）</option></select><label for="yaw">水平角度 <span id="yawvalue">0°</span></label><input id="yaw" type="range" min="-180" max="180" step="1" value="0"><label for="pitch">俯仰角度 <span id="pitchvalue">6°</span></label><input id="pitch" type="range" min="-75" max="75" step="1" value="6"><div class="buttons"><button id="front">正面</button><button id="side">侧面</button><button id="reset">重置视角</button></div><label><input type="checkbox" id="guide"> 显示盾牌中央保留区</label><div id="note" role="status"></div><div class="smallrow"><div class="pixelwrap"><canvas class="pixel" id="icon16" width="16" height="16" aria-label="16像素直接渲染参考"></canvas><br>16×16 直接渲染</div><div class="pixelwrap"><canvas class="pixel" id="icon32" width="32" height="32" aria-label="32像素直接渲染参考"></canvas><br>32×32 直接渲染</div></div><p class="muted meta">两种小尺寸均在各自画布上渲染同一组合，不另画一套物品图标。</p></section></div>
<section class="card"><h2>四类挂点与跨场景对照</h2><canvas id="board" class="board" width="1440" height="1440" aria-label="四类Fuse挂点审稿板"></canvas><p class="muted">盾牌的蓝色十字仅标示中央纹样保留区，游戏中仍使用实际盾纹。右下飞箭采用原版透明像素轮廓；飞行抖动与附魔光泽待接入后检查。</p></section>
<div class="grid"><section class="card"><h2>手持与背负保持同样尺度</h2><img id="pose" class="sideframe" alt="当前宿主手持与背负的同镜头对照"><p class="muted">左为背负、右为手持；相同宿主及附着材料的有效世界尺度为 1∶1。人物姿态为静态参考。第一人称的视野、动作和屏幕占比需要在游戏中复核。</p></section><section class="card"><h2>这版的制作规则</h2><div class="rule">根据材料实际外观尺寸统一缩放，分别贴合四类宿主的表面，避免把所有材料放在同一个点。</div><p>剑、斧保留握持部位；盾牌保留中央纹样；箭物品与飞箭各用自己的挂点。</p><p>不新增融合宿主模型、材料贴图或通用连接件。组合继续复用真实物品外观。</p><p class="muted meta">目前检查石头、钻石、羽毛三个代表。其他模组的特殊模型、动画或大面积透明材料需要单独验证。</p></section></div>
<div class="reviewlinks"><a href="../source/fuse-mount-review-v01.blend">可编辑三维参考源稿</a><a href="../exports/fuse-mount-layout.json">挂点与尺度规范</a><a href="../README.md">制作说明</a></div><p class="muted meta">2026-10-06 · 制造机界面 F06-02 已采用 · 本项待审，未接入游戏 · 下一项：F03-02 融合标识与剩余次数提示</p></main>
<script>const SPEC=__SPEC__,MESH=__MESH__,BACK=__BACK__,SOURCES=__IMAGES__;</script><script>__RENDERER__</script><script>
const $=id=>document.getElementById(id),state={host:'sword',material:'stone',context:'inventory',yaw:0,pitch:6,guide:false},viewer=new FuseReview.Viewer($('view')),v16=new FuseReview.Viewer($('icon16')),v32=new FuseReview.Viewer($('icon32')),imgs={};
const labels={sword:'剑',axe:'斧',shield:'盾',arrow:'箭',flight:'飞箭',stone:'石头',diamond:'钻石',feather:'羽毛'};
function render(){state.host=$('host').value;state.material=$('material').value;state.context=$('context').value;state.yaw=+$('yaw').value;state.pitch=+$('pitch').value;state.guide=$('guide').checked;
 $('context').querySelector('[value=back]').disabled=state.host==='arrow';$('context').querySelector('[value=flight]').disabled=state.host!=='arrow';if((state.host==='arrow'&&state.context==='back')||(state.host!=='arrow'&&state.context==='flight')){$('context').value=state.context='inventory';}
 viewer.draw(state.host,state.material,state.context,state.yaw,state.pitch,state.guide);v16.draw(state.host,state.material,'inventory',0,0,false);v32.draw(state.host,state.material,'inventory',0,0,false);$('yawvalue').textContent=state.yaw+'°';$('pitchvalue').textContent=state.pitch+'°';
 $('guide').disabled=state.host!=='shield';const p=SPEC.profiles[state.host];$('note').textContent=p.label+'。材料最大边限定在宿主局部 '+p.maxSpan+' 单位；'+(state.host==='arrow'?'箭没有背负槽位，飞行参考沿用原版箭轮廓。':'手持／背负有效尺度相同。')+(state.host==='shield'?' 中央区域保留给盾纹。':'');$('pose').src=SOURCES[(state.host==='arrow'?'sword':state.host)+'-held-back-pose'];$('pose').alt=state.host==='arrow'?'剑的手持背负对照；箭无背负记录':labels[state.host]+'的手持背负对照';window.lastRender=viewer.last;
}
for(const id of ['host','material','context','yaw','pitch','guide'])$(id).addEventListener('input',render);
for(const [id,angle,pitch] of [['front',0,0],['side',70,8],['reset',0,6]])$(id).onclick=()=>{$('yaw').value=angle;$('pitch').value=pitch;render();};let pointer=null;$('view').onpointerdown=e=>{pointer=[e.clientX,e.clientY,+$('yaw').value,+$('pitch').value];$('view').setPointerCapture(e.pointerId);};$('view').onpointermove=e=>{if(pointer){$('yaw').value=Math.max(-180,Math.min(180,pointer[2]+(e.clientX-pointer[0])*.6));$('pitch').value=Math.max(-75,Math.min(75,pointer[3]-(e.clientY-pointer[1])*.4));render();}};$('view').onpointerup=$('view').onpointercancel=()=>pointer=null;
function text(ctx,t,x,y,size=24,color='#eee8d3'){ctx.fillStyle=color;ctx.font=size+'px -apple-system,"PingFang SC",sans-serif';ctx.fillText(t,x,y);}
async function board(){await Promise.all(Object.entries(SOURCES).map(([k,url])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{imgs[k]=im;resolve();};im.onerror=reject;im.src=url;})));const b=$('board'),c=b.getContext('2d');c.fillStyle='#0e1b16';c.fillRect(0,0,b.width,b.height);text(c,'WILDCRAFT · FUSE 外观与挂点',40,62,32);text(c,'v01 · 四类宿主 × 三种材料 / 保留原版外观 / 草稿待审',40,103,19,'#b6c5b2');
 const hosts=['sword','axe','shield','arrow'],mats=['stone','diamond','feather'];for(let h=0;h<4;h++){let x=40+h*350;text(c,labels[hosts[h]]+' · '+SPEC.profiles[hosts[h]].label,x,150,23,'#e7c686');for(let m=0;m<3;m++){let y=170+m*253;c.fillStyle='#203027';c.fillRect(x,y,310,240);c.drawImage(imgs[hosts[h]+'-'+mats[m]+'-front'],x,y,230,230);text(c,labels[mats[m]],x+240,y+38,18);text(c,'32',x+257,y+115,16,'#a4b5a1');const mini=document.createElement('canvas');mini.width=mini.height=32;const renderer=new FuseReview.Viewer(mini);renderer.draw(hosts[h],mats[m],'inventory',0,0,false);c.imageSmoothingEnabled=false;c.drawImage(mini,x+241,y+126,64,64);renderer.gl.deleteBuffer(renderer.buffer);renderer.gl.deleteProgram(renderer.program);renderer.gl.getExtension('WEBGL_lose_context')?.loseContext();c.imageSmoothingEnabled=true;const tiny=document.createElement('canvas');tiny.width=tiny.height=16;const tr=new FuseReview.Viewer(tiny);tr.draw(hosts[h],mats[m],'inventory',0,0,false);c.imageSmoothingEnabled=false;c.drawImage(tiny,x+241,y+199,32,32);c.imageSmoothingEnabled=true;text(c,'16',x+280,y+223,15,'#a4b5a1');tr.gl.deleteBuffer(tr.buffer);tr.gl.deleteProgram(tr.program);tr.gl.getExtension('WEBGL_lose_context')?.loseContext();}}
 text(c,'侧面连接与飞行参考',40,982,25,'#e7c686');for(let h=0;h<4;h++){let x=40+h*350;c.drawImage(imgs[(h===3?'flight':'sword axe shield'.split(' ')[h])+'-stone-side'],x,1005,230,230);text(c,h===3?'飞箭':labels[hosts[h]]+' · 侧面',x+235,1060,17);text(c,h===3?'无背负记录':'表面贴合',x+235,1100,16,'#b6c5b2');}
 text(c,'新增模型 0 · 新贴图 0 · 连接件 0 · 手持／背负尺度比 1.00',40,1300,23);text(c,'盾纹保留区使用蓝色示意；真实组件、附魔光泽、第一人称动作与第三方模型待游戏接入验证。',40,1344,20,'#b6c5b2');text(c,'三维轮廓来源：已采用 A09 源稿 + 本地原版物品像素 / 此板不是游戏截图',40,1387,18,'#90a38f');window.boardReady=true;
}
render();board().catch(e=>{window.boardError=String(e);console.error(e);});window.reviewApp={state,render,viewer,v16,v32};window.appReady=true;
</script></html>'''
for k,v in [('__SPEC__',json.dumps(spec,ensure_ascii=False,separators=(',',':'))),('__MESH__',json.dumps(mesh,separators=(',',':'))),('__BACK__',json.dumps(back,separators=(',',':'))),('__IMAGES__',json.dumps(images,separators=(',',':'))),('__RENDERER__',(r/'source/fuse-review.js').read_text())]:html=html.replace(k,v)
(r/'review/preview.html').write_text(html)
(r/'exports/fuse-mount-layout.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n')
print('Interactive review saved',len(html))
