from pathlib import Path
import json,base64
ROOT=Path(__file__).resolve().parents[1]
def uri(p):return 'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
assets={}
for key,stem in [('warmth','warmth-meal'),('cooling','cooling-meal'),('recovery','stamina-recovery')]:assets[key]=uri(ROOT/'exports'/f'{stem}-16.png')
assets['stamina']=uri(ROOT/'references/stamina-hud-atlas.png')
html='''<!DOCTYPE html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft 料理效果 HUD · v01 审稿</title>
<style>*{box-sizing:border-box}body{margin:0;background:#111b17;color:#e3e8d9;font:15px/1.6 system-ui,-apple-system,sans-serif}main{max-width:1280px;margin:auto;padding:30px}h1{margin:8px 0;font-size:29px}h2{font-size:20px;margin:0 0 12px}.kicker{color:#d6b77d;font-size:12px;letter-spacing:2px}.muted{color:#a4b7a6}.controls{display:flex;gap:16px;flex-wrap:wrap;padding:18px;background:#202d25;border:1px solid #38463b;border-radius:10px;margin:22px 0}label{display:flex;gap:8px;align-items:center}select,button,input{font:inherit}select,button{background:#304331;color:#e3e8d9;border:1px solid #617b57;border-radius:5px;padding:6px 10px}select:focus-visible,button:focus-visible,input:focus-visible{outline:3px solid #d6b77d;outline-offset:3px}.stage{padding:16px;background:#090f0c;border:1px solid #3a4c3d;overflow:auto;border-radius:10px}canvas{display:block;image-rendering:pixelated;image-rendering:crisp-edges;max-width:none}.status{margin-top:12px;color:#c9d5bf;min-height:24px}.notes{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px;margin:24px 0}.note{padding:18px;background:#1d2a22;border:1px solid #35473a;border-radius:10px}.note p{margin:8px 0}.gallery{display:grid;grid-template-columns:repeat(auto-fit,minmax(400px,1fr));gap:18px}.card{background:#1c2820;padding:18px;border-radius:10px;border:1px solid #3b4a3f;overflow:hidden}.card h3{margin:0 0 12px;font-size:16px}.card canvas{border:1px solid #3b4a3f}.card small{color:#b2c2ac}footer{border-top:1px solid #3e4b3d;padding:18px 0;color:#9eaf9f;font-size:13px}@media(max-width:600px){main{padding:16px}.gallery{grid-template-columns:1fr}.card{overflow:auto}}</style>
<main><div class="kicker">WILDCRAFT · F01-03 · v01</div><h1>料理效果 HUD 排布</h1><p class="muted">沿用已采用的保暖、耐热、精力恢复图标。下方是布局模拟，字体近似；不是实机截图。</p>
<div class="controls"><label>场景<select id="scenario"></select></label><label>语言<select id="language"><option value="zh">中文</option><option value="en">English</option></select></label><label>显示倍数<select id="scale"><option>1</option><option selected>2</option><option>3</option></select></label><label><input id="stamina" type="checkbox" checked>显示精力</label><label><input id="bounds" type="checkbox">检查边界</label><label>保暖剩余秒<input id="seconds" type="range" min="0" max="600" value="127"><output id="seconds-label">127</output></label></div>
<section class="stage" aria-label="可切换的HUD布局模拟"><canvas id="live" role="img" aria-label="料理图标与红心、精力、温度的排列"></canvas></section><div class="status" id="status" aria-live="polite"></div>
<div class="notes"><div class="note"><h2>默认：图标与两列文字</h2><p>图标 16×16；左列名称与 I / II，右列倒计时。三个效果按保暖、耐热、恢复排序。未激活的项目不占位置。</p></div><div class="note"><h2>紧凑：图标、等级与时间</h2><p>多排红心或较短视窗时，改成小组横排；图标不缩小，所有等级和倒计时保留，宽度不足时再换行。</p></div><div class="note"><h2>时间与屏幕空间</h2><p>倒计时读取有效实际时间。暂停 / 离线不消耗，林克时间不延长。十秒内仅文字变琥珀色，不闪烁，不加全屏滤镜。</p></div></div>
<h2>状态对照 · 均为布局模拟</h2><div id="gallery" class="gallery"></div>
<footer>温度暂用现有七格占位；下一项再审温度图标。红心 / 吸收心为位置示意；精力条用已接入纹理。底部经验与快捷栏只标预留区域。图标原件及源稿保持原哈希，本次布局未采用、未接入游戏。</footer></main>
<script>__MODEL__</script><script>const ASSET=__ASSETS__;</script><script>
const M=WildcraftMealHud,imgs={};
let state={...M.presets.normal};
function imageLoad(){return Promise.all(Object.entries(ASSET).map(([key,src])=>new Promise((resolve,reject)=>{let im=new Image();im.onload=()=>{imgs[key]=im;resolve()};im.onerror=reject;im.src=src;})));}
const heartRows=['.oo.oo...','orrroro..','orrhrrro.','orrrrrro.','.orrrro..','..orro...','...oo....'];
function label(c,t,x,y,color='#e1d7ae',size=9){c.font=`${size}px monospace, "PingFang SC", sans-serif`;c.textBaseline='top';c.fillStyle='#0b100b';c.fillText(t,x+1,y+1);c.fillStyle=color;c.fillText(t,x,y);}
function hearts(c,s){const map={o:'#181c13',r:'#c84440',h:'#ee8c72'};for(let row=0;row<s.rows;row++){for(let k=0;k<10;k++){let x=12+k*8,y=12+row*s.rowHeight;heartRows.forEach((r,j)=>[...r].forEach((a,i)=>{if(a!=='.'){c.fillStyle=(s.absorption&&row===s.rows-1)?{o:'#252516',r:'#d1a648',h:'#f4dc89'}[a]:map[a];c.fillRect(x+i,y+j,1,1);}}));}}}
function backdrop(c,s){c.fillStyle='#78988b';c.fillRect(0,0,s.w,s.h);c.fillStyle='#b9c8af';c.fillRect(0,0,s.w,Math.floor(s.h*.44));c.fillStyle='#49694d';for(let i=0;i<12;i++){let x=i*43,y=Math.floor(s.h*.38)+(i%3)*7;c.fillRect(x,y,45,s.h-y);}c.fillStyle='#254331';for(let i=0;i<7;i++){let x=155+i*51,y=Math.floor(s.h*.32)+(i%2)*13;c.fillRect(x,y,17,26);c.fillStyle='#634e38';c.fillRect(x+7,y+23,4,14);c.fillStyle='#254331';}c.fillStyle='#617946';c.fillRect(0,Math.floor(s.h*.61),s.w,Math.ceil(s.h*.4));c.fillStyle='#415d3b';for(let i=0;i<20;i++)c.fillRect((i*37)%s.w,s.h-60-(i%3)*8,7,2);
 c.fillStyle='#253227';c.fillRect(0,s.h-46,s.w,46);label(c,s.language==='zh'?'经验 / 快捷栏预留区域':'XP / hotbar reserved',Math.max(12,s.w/2-57),s.h-28,'#9fa88d',8);
 c.fillStyle='#eceddc';let cx=Math.floor(s.w/2),cy=Math.floor(s.h/2);c.fillRect(cx-3,cy,7,1);c.fillRect(cx,cy-3,1,7);
}
function draw(canvas,s,scale){const l=M.compute(s);canvas.width=s.w;canvas.height=s.h;canvas.style.width=`${s.w*scale}px`;canvas.style.height=`${s.h*scale}px`;const c=canvas.getContext('2d');c.imageSmoothingEnabled=false;backdrop(c,s);hearts(c,s);
 if(s.stamina){label(c,s.language==='zh'?'精力 64 / 100':'Stamina 64 / 100',12,l.staminaLabelY,'#dce8d0');c.drawImage(imgs.stamina,0,0,112,7,12,l.staminaTrackY,112,7);c.drawImage(imgs.stamina,0,8,69,3,14,l.staminaTrackY+2,69,3);}
 c.fillStyle='rgba(21,35,27,.44)';c.fillRect(10,l.temperatureY-2,s.language==='zh'?68:108,12);for(let i=0;i<7;i++){c.fillStyle=i===3?'#ccd8c2':'#4d5f51';c.fillRect(12+i*5,l.temperatureY+2,3,4);}label(c,s.language==='zh'?'舒适':'Comfortable',51,l.temperatureY,'#ccd8c2');
 if(l.fits){for(const b of l.boxes){c.fillStyle='rgba(21,35,27,.44)';c.fillRect(b.x-2,b.y-1,b.width+4,b.height+2);c.drawImage(imgs[b.key],b.iconX,b.iconY,16,16);if(l.mode==='full')label(c,`${b.name} ${b.levelText}`,b.nameX,b.nameY);else label(c,b.levelText,b.levelX,b.levelY);label(c,b.timeText,b.timerX,b.timerY,b.lowTime?'#f0b84d':'#d4dccb');}}
 if(s.bounds){c.strokeStyle='#ffc16d';c.lineWidth=1;for(const b of l.boxes)c.strokeRect(b.x-.5,b.y-.5,b.width+1,b.height+1);c.strokeStyle='#ed8681';c.beginPath();c.moveTo(0,l.bottom+.5);c.lineTo(s.w,l.bottom+.5);c.stroke();}
 canvas.setAttribute('aria-label',`${s.title}，${l.mode==='full'?'纵排':'紧凑排列'}，${l.boxes.length}个效果`);return l;
}
function update(){const l=draw(document.querySelector('#live'),state,Number(document.querySelector('#scale').value));document.querySelector('#status').textContent=`${state.title} · ${state.w}×${state.h} 逻辑尺寸 · ${l.mode==='full'?'纵排':'紧凑排列'} · ${l.boxes.length} 个效果 · ${l.fits?'布局可容纳':'空间不足：不覆盖红心或底部区域'}${state.focus?' · 专注时保持料理读取，温度边缘色调关闭':''}`;window.lastLayout=l;}
function apply(key){state={...M.presets[key],levels:[...M.presets[key].levels],seconds:[...M.presets[key].seconds]};document.querySelector('#language').value=state.language;document.querySelector('#stamina').checked=state.stamina;document.querySelector('#seconds').value=state.seconds[0];document.querySelector('#seconds-label').value=state.seconds[0];update();}
for(const [k,s] of Object.entries(M.presets)){let o=new Option(s.title,k);document.querySelector('#scenario').add(o);}
document.querySelector('#scenario').onchange=e=>apply(e.target.value);document.querySelector('#language').onchange=e=>{state.language=e.target.value;update();};document.querySelector('#stamina').onchange=e=>{state.stamina=e.target.checked;update();};document.querySelector('#bounds').onchange=e=>{state.bounds=e.target.checked;update();};document.querySelector('#scale').onchange=update;document.querySelector('#seconds').oninput=e=>{state.seconds[0]=Number(e.target.value);state.levels[0]=state.seconds[0]>0?2:0;document.querySelector('#seconds-label').value=e.target.value;update();};
window.reviewReady=false;imageLoad().then(()=>{apply('normal');for(const [key,s] of Object.entries(M.presets)){const d=document.createElement('article');d.className='card';const h=document.createElement('h3');h.textContent=s.title;d.append(h);const cv=document.createElement('canvas');cv.id='sample-'+key;d.append(cv);let l=draw(cv,s,1);const p=document.createElement('small');p.textContent=`${s.w}×${s.h} · ${l.mode==='full'?'纵排':'紧凑'} · ${l.boxes.length}项；模拟 / 字体近似`;d.append(p);document.querySelector('#gallery').append(d);}window.reviewReady=true;});
</script></html>'''
html=html.replace('__MODEL__',(ROOT/'source/hud-layout.js').read_text()).replace('__ASSETS__',json.dumps(assets))
(ROOT/'review/preview.html').write_text(html)
print('交互审稿页已生成：9个场景，中英文/精力隐藏/秒数与边界可切换。')
