from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
spec=json.loads((R/'exports/transition-spec.json').read_text())
options=''.join(f'<option value="{s["id"]}">{s["label"]}</option>'for s in spec['scenarios'])
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft 探索动作衔接 v01</title><style>
*{box-sizing:border-box}body{margin:0;background:#0d1814;color:#e7e7d5;font:16px/1.65 -apple-system,"PingFang SC",sans-serif}main{max-width:1300px;margin:auto;padding:32px 24px}h1{font-size:32px;line-height:1.3;margin:8px 0}h2{font-size:20px;margin:0 0 14px}p{color:#aabbab;margin:12px 0}.eyebrow{font-size:13px;letter-spacing:2px;color:#dab479}.tag{font-size:13px;color:#dfc38c}.card{background:#17241d;border:1px solid #3b4e40;border-radius:12px;padding:20px;min-width:0;margin:20px 0}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}.pair .card{margin:0}.controls{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}canvas{display:block;width:100%;height:auto;background:#111b17;border-radius:8px}label{display:block;color:#b9c8b5;font-size:14px;margin:10px 0 3px}select{width:100%;padding:8px;background:#0f1b14;border:1px solid #60705a;color:#e3e9d7;border-radius:6px;font:inherit}input[type=range]{width:100%;accent-color:#d4b77d}button{font:inherit;padding:7px 13px;border:1px solid #6b785e;background:#2b4132;color:#e5e8d6;border-radius:6px;cursor:pointer}button:hover{background:#405744}button:focus-visible,select:focus-visible,input:focus-visible{outline:3px solid #dbbc80;outline-offset:3px}.buttons{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.note{font-size:14px;color:#b6c9b3}.checks{display:flex;gap:20px;flex-wrap:wrap}.first-frame{max-width:860px;margin:auto;position:relative}.safe{position:absolute;left:35%;top:30%;width:30%;height:30%;border:1px dashed #aeb89266;pointer-events:none}.links{display:flex;gap:20px;flex-wrap:wrap}a{color:#ddbc81}#status{color:#dfc38c}#note{min-height:48px}@media(max-width:850px){.pair{grid-template-columns:1fr}.controls{grid-template-columns:1fr 1fr}main{padding:24px 14px}}@media(max-width:480px){h1{font-size:26px}.card{padding:14px}.controls{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}
</style><main><div class="eyebrow">WILDCRAFT / A07-A08-C</div><h1>探索动作，衔接与即时恢复</h1><span class="tag">v01 · 待审稿，未接入</span><p>沿用已采用的攀爬、握伞与装备尺寸。让动作从当下姿态衔接；取物、拉弓与举盾直接优先，操作不等待动画。</p>
<section class="card"><h2>选择一个衔接场景</h2><div class="controls"><div><label for="id">场景</label><select id="id">__OPTIONS__</select></div><div><label for="variant">手臂</label><select id="variant"><option value="standard">标准手臂</option><option value="slim">细手臂</option></select></div><div><label for="main">主手</label><select id="main"><option value="right">右手</option><option value="left">左手</option></select></div><div><label for="cover">装备挂位</label><select id="cover"><option value="cape">披风与采用侧腰布局</option><option value="none">无披风，采用背部布局</option></select></div></div><p id="note"></p><label for="time">时间 <output id="clock">0.720 s</output> · 0.65s为触发点</label><input type="range" id="time" min="0" max="1.8" step="0.001" value="0.72"><div class="buttons"><button id="play">播放</button><button id="restart">回到开始</button><button id="event">跳到触发点</button><button id="step">下一帧</button></div><label for="speed">审稿速度</label><select id="speed"><option value="1">正常速度</option><option value="0.25">四分之一速度</option><option value="0.5">半速</option></select><p id="status" role="status"></p></section>
<div class="pair"><section class="card"><h2>当前肢体采样</h2><canvas id="current" width="620" height="640" aria-label="当前肢体采样三维参考"></canvas><p class="note">复现当前烘焙肢体的帧选取与旋转插值。装备统一使用已采用布局，便于对照；这不是当前游戏截图。</p></section><section class="card"><h2>修订衔接参考</h2><canvas id="revised" width="620" height="640" aria-label="修订衔接三维参考"></canvas><p class="note">当前姿态接入、旋转走短路径、空手结束对齐原版；行为优先级与伞的显隐即时生效。</p></section></div>
<section class="card"><div class="buttons"><button id="front">正面</button><button id="side">侧面</button><button id="back">背面</button></div><div class="controls"><div><label for="yaw">水平角度</label><input id="yaw" type="range" min="-180" max="180" value="-35"></div><div><label for="pitch">俯仰</label><input id="pitch" type="range" min="-75" max="75" value="-8"></div></div><div class="checks"><label><input id="reduced" type="checkbox"> 减少视觉过渡</label><label><input id="fusion" type="checkbox"> 已采用Fuse石头占用参考</label></div><p class="note">可拖动任一三维画布同步旋转。播放由你启动，页面隐藏时暂停；减少过渡不会改变物品归属或操作时机。</p></section>
<section class="card"><h2>第一人称占用参考</h2><div class="first-frame"><canvas id="first" width="960" height="540" aria-label="第一人称双手与伞框占用参考"></canvas><div class="safe"></div></div><label for="fov">参考垂直视场</label><input id="fov" type="range" min="55" max="95" value="70"><p id="first-note" class="note"></p><p class="note">原稳态双手与原伞框几何；70°与16:9为采用参考，其他角度仅辅助审稿。取物后的手部与物品是简化引导，未重建原版第一人称摆动、投影或皮肤袖层。此处不调整游戏镜头。</p></section>
<section class="card"><h2>关键时刻对照</h2><canvas id="board" width="1200" height="1490" aria-label="四类动作关键帧审稿板"></canvas></section><div class="links"><a href="/source/exploration-joins-v01.blend">可编辑动作源稿</a><a href="/exports/transition-spec.json">衔接参数</a><a href="/README.md">制作与验证说明</a></div><p class="note">2026-10-06 · A09-C已采用 · 本版仅审稿，未接入游戏。审稿位移为测试输入，不是游戏物理或新的攀爬速度；未制作新贴图、装备模型或完整动画套件。</p></main>
__DATA__<script>__WAIST__</script><script>__ENGINE__</script><script>__VIEWER__</script><script>__APP__</script></html>'''
data=[]
for key,path in [('CLIPS','references/runtime-clips.json'),('GEOMETRY','source/reference-geometry.json'),('LAYOUT','references/adopted-waist.json'),('BACK','references/adopted-back.json'),('FUSE','references/adopted-fuse.json'),('FIRST_FRAME','references/first-person-frame.json'),('SPEC','exports/transition-spec.json')]:
    data.append('const '+key+'='+json.dumps(json.loads((R/path).read_text()),ensure_ascii=False,separators=(',',':'))+';')
page=page.replace('__OPTIONS__',options).replace('__DATA__','<script>'+''.join(data)+'</script>')
for token,path in [('__WAIST__','references/waist-engine.js'),('__ENGINE__','source/transition-engine.js'),('__VIEWER__','source/motion-viewer.js'),('__APP__','source/motion-review.js')]:page=page.replace(token,(R/path).read_text())
(R/'review/preview.html').write_text(page)
print('Review bytes',len(page.encode()))
