from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1]
def image(p):return 'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
G=json.loads((R/'source/geometry-and-uv.json').read_text());G['body']=json.loads((R/'references/approved-machine-geometry.json').read_text())
images={p.name:image(p)for folder in ['review','exports']for p in (R/folder).glob('*.png')if 'review'not in p.name}
snapshots=[dict(id='idle',label='停转 · 节点未工作',ageInTicks=20,active=False,ghost=False),dict(id='working',label='运转 · 工作节点',ageInTicks=20,active=True,ghost=False),dict(id='quarter',label='运转 · 45°相位',ageInTicks=1.9634954085,active=True,ghost=False),dict(id='reverse',label='后退输入参考 · 同向转动',ageInTicks=20,active=True,ghost=False,drive=-1),dict(id='inactive',label='整机开启 · 节点未工作',ageInTicks=20,active=False,ghost=False,enabled=True),dict(id='ghost',label='安装预览 · 静止',ageInTicks=20,active=True,ghost=True)]
(R/'source/review-snapshots.json').write_text(json.dumps(snapshots,ensure_ascii=False,indent=2)+'\n')
css=(R.parents[1]/'F05-06/v01/source/build-preview.py').read_text().split('<style>')[1].split('</style>')[0]
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · F05-07 车轮 v01</title><style>__CSS__</style><header><small>WILDCRAFT / B3 · F05-07</small><h1>车轮 · 深色胎面、钢圈与铜轮毂</h1><p>16段胎面包围四辐条轮圈，辐条间保留真实开孔。固定轴座保持不动，轮体沿现有节点轴转动。</p><div class="chips"><span class="chip">v01 草稿待审</span><span class="chip">复用机械64×64图集</span><span class="chip">未接入游戏</span></div></header>
<h2>实际模型与停转／运转</h2><main><section class="panel"><canvas id="live" aria-label="车轮实际模型"></canvas><p id="render-info" class="note"></p></section><aside class="panel"><label>状态快照<select id="snapshot"></select></label><label>安装视图<select id="node"><option value="-1">独立部件</option><option value="0">顶节点</option><option value="1">底节点</option><option value="2">后节点</option><option value="3">前节点</option><option value="4">左节点</option><option value="5">右节点</option></select></label><label>转动相位参考 <span id="age">20</span> 世界刻<input id="ticks" type="range" min="0" max="100" step="0.01" value="20"></label><button id="play">播放转动演示</button><label>水平视角<input id="yaw" type="range" min="-180" max="180" value="-25"></label><label>俯仰视角<input id="pitch" type="range" min="-85" max="85" value="18"></label><button id="reset">恢复默认视图</button><p id="readout"></p><p class="note">工作节点按0.4弧度／世界刻转动，停转及安装预览回到0角度。后退输入不改变现有视觉转向。</p><p class="note">播放仅为20刻／秒的美术演示，不消耗实际能源。游戏接入后读取真实age和节点active，不从整机启用或电池存在推断转动。</p></aside></main>
<h2>停转与运转相位 · 同尺度实际渲染</h2><section class="compare"><figure><img id="idle-render"><figcaption>停转 · 四辐条与铜色轮毂</figcaption></figure><figure><img id="phase-render"><figcaption>运转相位 · 45°，轴座和安装接口固定</figcaption></figure></section>
<h2>原生物品图标</h2><section class="panel"><div id="icons" class="icons"></div><p class="note">32与16分别绘制，保持深色胎面、钢圈、四辐条、铜轮毂及开孔；不是生图缩小。</p></section>
<h2>六向安装参考</h2><section id="mounts" class="grid"></section><p class="note">复用现有六个节点。接地驱动由整机onGround与真实能源支付决定，不新增独立车轮碰撞或悬架。</p>
<h2>当前接地外观参考</h2><section class="panel"><img id="ground" style="width:480px;max-width:100%;border-radius:8px"><p class="note">保持原型直径0.50方块与侧节点高度0.325方块。相对机体底平面，侧轮下缘约留0.075方块；此处展示真实间隙，接入时需核对地面外观，未扩大车轮或改动碰撞。</p></section>
<h2>统一纹理图集</h2><section class="panel atlas"><img id="atlas"><p class="note">完整复用采用机械64×64图集，新增生产贴图像素0。胎面与槽纹复用recess/vent，钢圈与铜嵌件复用steel/copper。</p></section>
<h2>综合审稿板</h2><section class="panel"><canvas id="board"></canvas><p><a href="wheel-review.png">打开审稿板 PNG</a></p></section><p class="note">当前仅美术交付。可编辑源稿、六向参考及验证记录已存档；实际游戏装配、接地和驱动仍待接入验证。</p>
<script>const G=__G__,SOURCES=__IMAGES__,SNAPSHOTS=__SNAPSHOTS__;</script><script>__RENDER__</script><script>
const loaded={},names=['顶','底','后','前','左','右'];window.reviewReady=false;let playing=false,lastTime=0,raf;
function current(){const s=SNAPSHOTS.find(s=>s.id===document.querySelector('#snapshot').value)||SNAPSHOTS[0];return {...s,ageInTicks:+document.querySelector('#ticks').value}}
function redraw(){const s=current(),p=WildcraftWheelPreview.presentation(s),n=+document.querySelector('#node').value;window.lastPresentation=p;window.lastRender=WildcraftWheelPreview.drawModel(document.querySelector('#live'),loaded['shared-machine-atlas-64.png'],{...G,...p},+document.querySelector('#yaw').value,+document.querySelector('#pitch').value,n);document.querySelector('#age').textContent=p.ageInTicks.toFixed(2);document.querySelector('#render-info').textContent=`${p.rotating?'运转相位':'静止'} · ${n<0?'独立部件':names[n]+'节点'} · ${p.ghost?'透明安装预览':'实际材质'}`;document.querySelector('#readout').innerHTML=`<strong>${p.rotating?'运转':'静止'} · ${(p.angle*180/Math.PI%360).toFixed(1)}°</strong><br>固定安装座与轴；轮体整体转动<br><span class="note">接地驱动时每个车轮1能量／世界刻。</span>`;}
function stop(){playing=false;cancelAnimationFrame(raf);document.querySelector('#play').textContent='播放转动演示';window.demoPlaying=false}
function loop(t){if(!playing)return;const s=current();if(!s.active||s.ghost){stop();return}const el=document.querySelector('#ticks');el.value=(+el.value+Math.min(100,t-lastTime)*.02)%100;lastTime=t;redraw();raf=requestAnimationFrame(loop)}
document.querySelector('#play').onclick=()=>{if(playing){stop();return}if(!current().active||current().ghost){document.querySelector('#snapshot').value='working';document.querySelector('#ticks').value=20}playing=true;window.demoPlaying=true;lastTime=performance.now();document.querySelector('#play').textContent='暂停演示';redraw();raf=requestAnimationFrame(loop)};
document.querySelector('#snapshot').addEventListener('input',()=>{stop();document.querySelector('#ticks').value=SNAPSHOTS.find(s=>s.id===document.querySelector('#snapshot').value).ageInTicks;redraw()});for(const id of ['node','ticks','yaw','pitch'])document.querySelector('#'+id).addEventListener('input',()=>{if(id==='ticks')stop();redraw()});document.querySelector('#reset').onclick=()=>{stop();document.querySelector('#node').value=-1;document.querySelector('#snapshot').value='idle';document.querySelector('#ticks').value=20;document.querySelector('#yaw').value=-25;document.querySelector('#pitch').value=18;redraw()};
function board(){const c=document.querySelector('#board');c.width=1200;c.height=1870;const x=c.getContext('2d');x.fillStyle='#14221c';x.fillRect(0,0,c.width,c.height);const text=(s,a,b,size=22,col='#e7dec3')=>{x.fillStyle=col;x.font=`${size}px system-ui`;x.fillText(s,a,b)},image=(n,a,b,w,h,pixel=false)=>{x.imageSmoothingEnabled=!pixel;x.drawImage(loaded[n],a,b,w,h)};
text('WILDCRAFT · F05-07 / v01',40,50,22,'#93b39e');text('车轮 · 深色胎面、钢圈与铜轮毂',40,101,36);text('草稿待审 / 原生32与16分别绘制 / 未接入游戏',40,139,19,'#b1bca8');image('wheel-idle-three-quarter.png',40,163,540,540);image('wheel-running-phase.png',620,163,540,540);text('停转 · 开孔四辐条与16段胎面',54,735,22);text('运转45°相位 · 固定轴座不动',634,735,22);
image('wheel-item-32.png',90,782,160,160,true);image('wheel-item-16.png',370,782,160,160,true);text('32×32 独立像素稿',80,975,20);text('16×16 独立像素稿',355,975,20);text('0.50方块直径 · 现有转轴',620,822,25);text('轮胎 / 钢圈 / 铜嵌件分组',620,870,22);text('64×64统一图集，新增贴图像素0',620,915,21);
text('六向安装 · 原尺度 · 同节点轴向',40,1044,24);for(let i=0;i<6;i++){const a=40+i%3*383,b=1070+Math.floor(i/3)*330;image('wheel-mounted-'+i+'.png',a+18,b,300,300);text(names[i]+'节点',a+20,b+319,20)}
text('节点active才转动；停转与安装预览保持0角度。',40,1760,23);text('沿用0.4弧度／世界刻；不新增悬架、轮胎碰撞或速度推导。',40,1806,21);text('实际网格、可编辑源稿、原生图标与接地参考已存档。',40,1845,20,'#b1bca8');}
(async()=>{for(const[n,src]of Object.entries(SOURCES)){const im=new Image();im.src=src;await im.decode();loaded[n]=im;}document.querySelector('#snapshot').innerHTML=SNAPSHOTS.map(s=>`<option value="${s.id}">${s.label}</option>`).join('');document.querySelector('#idle-render').src=SOURCES['wheel-idle-three-quarter.png'];document.querySelector('#phase-render').src=SOURCES['wheel-running-phase.png'];document.querySelector('#atlas').src=SOURCES['shared-machine-atlas-64.png'];document.querySelector('#ground').src=SOURCES['wheel-side-ground-reference.png'];document.querySelector('#icons').innerHTML=[32,16].map(n=>`<figure><img class="pixel" alt="车轮${n}像素" src="${SOURCES['wheel-item-'+n+'.png']}"><figcaption>${n}×${n} · 铜轮毂与开孔</figcaption></figure>`).join('');document.querySelector('#mounts').innerHTML=names.map((n,i)=>`<figure><img alt="${n}节点安装" src="${SOURCES['wheel-mounted-'+i+'.png']}"><figcaption>${n}节点 · 轮轴沿外法线</figcaption></figure>`).join('');redraw();board();window.demoPlaying=false;window.reviewReady=true;})().catch(e=>{window.reviewError=e.message;document.querySelector('#render-info').textContent=e.message});
</script></html>'''
html=html.replace('__CSS__',css).replace('__G__',json.dumps(G,separators=(',',':'),ensure_ascii=False)).replace('__IMAGES__',json.dumps(images,separators=(',',':'))).replace('__SNAPSHOTS__',json.dumps(snapshots,separators=(',',':'),ensure_ascii=False)).replace('__RENDER__',(R/'source/wheel-preview.js').read_text());(R/'review/preview.html').write_text(html);print('Wheel actual mesh review ready')
