from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1]
def uri(p):return 'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
assets={'panel':uri(R/'exports/charger-ui-176x166.png')}
for name in ['battery-item-16','battery-empty-16','battery-full-16','charger-atlas-64']:assets[name]=uri(R/'references'/(name+'.png'))
regions=json.loads((R/'references/energy-regions.json').read_text())['regions']['16'];physical=json.loads((R/'references/battery-item-energy-regions.json').read_text())['regions']['16']
html=r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · 充电器界面 v01</title><style>
*{box-sizing:border-box}body{margin:0;background:#13211a;color:#e1e8d9;font:15px/1.7 system-ui,"PingFang SC",sans-serif}main{max-width:1240px;margin:auto;padding:28px}h1{font-size:29px;margin:6px 0 10px}h2{font-size:19px}.tag{color:#dbb573;font-size:13px}.muted{color:#a9bca1}.controls{display:flex;flex-wrap:wrap;gap:16px;padding:18px;background:#253729;border:1px solid #465a43;border-radius:6px;margin:20px 0}label{display:flex;align-items:center;gap:8px}select,input{accent-color:#b4432b;background:#17271c;color:inherit;border:1px solid #65765b;border-radius:3px;padding:6px}input[type=range]{width:180px}input[type=number]{width:90px}button{background:#304631;color:inherit;border:1px solid #65765b;border-radius:4px;padding:6px 12px;cursor:pointer}:focus-visible{outline:3px solid #e5bd78;outline-offset:3px}.samples{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.stage{background:#0b130e;border:1px solid #3d513b;padding:18px;overflow:auto}canvas{image-rendering:pixelated;display:block}.board{max-width:100%;height:auto;image-rendering:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px}.card{background:#253729;border:1px solid #465a43;padding:16px;overflow:auto}.card h3{font-size:17px;margin:0 0 12px}.card p{font-size:13px;color:#b5c6aa}.small{font-size:13px;color:#a3b69b}.description{padding:12px 0;min-height:44px}@media(max-width:650px){main{padding:20px 14px}}
</style><main><span class="tag">F04-04 · v01 · 草稿待审 · 未接入游戏</span><h1>充电器界面 · 电量与共享供电</h1><p class="muted">原生176×166底图，保留1个真实电池槽和36格物品栏。复用已采用的电池物品图、电量读数与五态符号。</p>
<div class="controls"><label>场景<select id="scenario"></select></label><label>语言<select id="language"><option value="zh">中文</option><option value="en">English</option></select></label><label>显示倍数<select id="scale"><option>1</option><option>2</option><option selected>3</option><option>4</option></select></label><label>余量<input id="energy" type="range" min="0" max="1000" value="500"></label><label>准确值<input id="number" type="number" min="0" max="1000" value="500"></label><label>悬停提示<select id="hover"><option value="auto">随鼠标</option><option value="none">关闭</option><option value="status">供电说明</option><option value="battery">电池详情</option></select></label><label><input id="bounds" type="checkbox">查看实际槽位</label></div>
<div class="samples" id="samples"></div><div class="stage"><canvas id="live" role="img" aria-label="充电器界面模拟"></canvas></div><div class="description" id="description" aria-live="polite"></div>
<p class="small">在状态行或电池上悬停，可查看完整说明。没有电池显示“— / 1000”；缺源和等待不会清空余量。浏览器字体与提示框为近似模拟，正式接入使用原版字体和物品提示。</p>
<h2>五种状态完整对照</h2><div class="grid" id="gallery"></div><h2>审稿总览</h2><canvas id="board" class="board" width="1200" height="1320"></canvas><p class="small">此页只模拟显示与提示，不模拟物品转移、实际充电或共享能源分配。单槽与背包坐标、1000容量和105px电量条保持现规则；状态行上移，为原版背包标题留出空间。</p></main>
<script>__UI__</script><script>__READOUT__</script><script>__PHYSICAL__</script><script>
const U=WildcraftChargerUi,B=WildcraftBatteryReadout,P=WildcraftBatteryPreview,sources=__ASSETS__,regions=__REGIONS__,physical=__PHYSICALREGIONS__,imgs={};let state={...U.fixtures.charging,language:'zh',bounds:false},hoverTarget=null;
function get(id){return document.getElementById(id)}
function text(c,str,x,y,color='#354438'){c.font='9px monospace,"PingFang SC",sans-serif';c.textBaseline='top';c.fillStyle=color;c.fillText(str,x,y);return {text:str,x,y,width:c.measureText(str).width,height:9};}
function ghost(c){c.fillStyle='#81928a';c.fillRect(31,38,6,1);c.fillRect(31,47,6,1);c.fillRect(30,39,1,8);c.fillRect(37,39,1,8);c.fillRect(33,37,2,1);}
function drawUi(c,s){c.save();c.imageSmoothingEnabled=false;c.drawImage(imgs.panel,0,0);const status=U.deriveStatus(s),st=U.states[status],L=U.labels[s.language],labels=[];labels.push(text(c,L.title,8,7));labels.push(text(c,L.battery,14,22));labels.push(text(c,L.charge,78,22));labels.push(text(c,L.inventory,8,72));
 if(s.present){P.drawIcon(c,imgs['battery-item-16'],physical,16,s.energy,26,35);c.fillStyle=s.energy<100?'#d8a24d':'#7aae83';c.fillRect(28,48,Math.round(13*s.energy/1000),1);}else ghost(c);
 const readout=B.drawReadout(c,{empty:imgs['battery-empty-16'],full:imgs['battery-full-16']},regions,s.energy,s.present,54,29,1,'light',status);const fill=U.chargeWidth(s.energy,s.present);c.fillStyle='#608865';if(fill)c.fillRect(55,48,fill,5);
 c.drawImage(imgs['charger-atlas-64'],status*8,48,8,8,10,60,8,8);const statusText=text(c,st[s.language],22,60,st.color);labels.push(statusText);
 if(s.bounds){c.strokeStyle='#da722b';c.lineWidth=1;for(const q of U.slots)c.strokeRect(q.x-.5,q.y-.5,17,17);}
 c.restore();return {status,energy:s.present?s.energy:null,present:s.present,readout:readout.text,readoutSemantic:readout.semantic,readoutColor:readout.color,barWidth:fill,itemBarWidth:s.present?Math.round(13*s.energy/1000):0,statusText,labels,slots:U.slots,size:[176,166]};}
function wrap(c,str,maxWidth){c.font='9px monospace,"PingFang SC",sans-serif';const tokens=/[\u3400-\u9fff]/.test(str)?[...str]:str.split(/\s+/).map((s,i)=>(i?' ':'')+s);const lines=[];let line='';for(const token of tokens){if(c.measureText(line+token).width<=maxWidth||!line){line+=token;}else{lines.push(line.trim());line=token.trimStart();}}if(line)lines.push(line.trim());return lines;}
function tooltipLines(s,kind,c){const st=U.states[U.deriveStatus(s)];if(kind==='battery'&&s.present)return [{text:s.language==='zh'?'有限电池':'Battery',color:'#e9d9ad'},{text:s.energy+' / 1000',color:'#d0ddbb'},...wrap(c,s.language==='zh'?'放入紧邻固定红石块的充电器':'Charge beside a fixed redstone block',164).map(text=>({text,color:'#b5c0ae'}))];return [{text:st[s.language],color:'#e9d9ad'},...wrap(c,st[s.language==='zh'?'helpZh':'helpEn'],164).map(text=>({text,color:'#c8d2bf'}))];}
function drawTooltip(c,s,kind){if(kind==='battery'&&!s.present)return null;const lines=tooltipLines(s,kind,c),x=180,width=176,height=lines.length*11+12,y=Math.max(4,Math.min(kind==='battery'?35:57,166-height-4));c.fillStyle='#201d2b';c.fillRect(x,y,width,height);c.strokeStyle='#6f587a';c.strokeRect(x+.5,y+.5,width-1,height-1);const measured=[];for(let i=0;i<lines.length;i++)measured.push(text(c,lines[i].text,x+6,y+6+i*11,lines[i].color));return {kind,x,y,width,height,lines:measured};}
function currentTooltip(){const chosen=get('hover').value;return chosen==='none'?null:chosen==='auto'?hoverTarget:chosen;}
function drawLive(){const cv=get('live'),scale=+get('scale').value,tip=currentTooltip(),shown=tip&&!(tip==='battery'&&!state.present);cv.width=shown?360:176;cv.height=166;cv.style.width=cv.width*scale+'px';cv.style.height=166*scale+'px';const c=cv.getContext('2d');c.clearRect(0,0,cv.width,cv.height);const layout=drawUi(c,state);layout.tooltip=shown?drawTooltip(c,state,tip):null;window.lastLayout=layout;get('description').textContent=U.states[layout.status][state.language]+' · '+layout.readout+(layout.status===4?'；有固定红石源，正在等候共享供电。':'');cv.setAttribute('aria-label',U.states[layout.status][state.language]+', '+layout.readout+', 1 charging slot and 36 inventory slots');}
function update(){state.language=get('language').value;state.bounds=get('bounds').checked;get('energy').value=get('number').value=state.energy;get('energy').disabled=get('number').disabled=!state.present;get('scenario').value=U.states[U.deriveStatus(state)].key;drawLive();}
function apply(key){state={...U.fixtures[key],language:get('language').value,bounds:get('bounds').checked};hoverTarget=null;update();}
function setEnergy(e){state.energy=B.energyValue(e);update();}
function drawGallery(){get('gallery').replaceChildren();for(const st of U.states){const card=document.createElement('article');card.className='card';const h=document.createElement('h3');h.textContent=st[get('language').value];card.append(h);const cv=document.createElement('canvas');cv.id='sample-'+st.key;cv.width=176;cv.height=166;cv.style.width='176px';cv.style.height='166px';drawUi(cv.getContext('2d'),{...U.fixtures[st.key],language:get('language').value,bounds:false});card.append(cv);const p=document.createElement('p');p.textContent=st[get('language').value==='zh'?'helpZh':'helpEn'];card.append(p);get('gallery').append(card)}}
function drawBoard(){const c=get('board').getContext('2d');c.imageSmoothingEnabled=false;const label=(s,x,y,size=18,color='#dce6d4')=>{c.font=size+'px system-ui,"PingFang SC",sans-serif';c.textBaseline='top';c.fillStyle=color;c.fillText(s,x,y)};const panel=(x,y,w,h)=>{c.fillStyle='#24392a';c.fillRect(x,y,w,h);c.strokeStyle='#415b40';c.strokeRect(x+.5,y+.5,w-1,h-1)};const full=(key,lang='zh')=>{const cv=document.createElement('canvas');cv.width=176;cv.height=166;drawUi(cv.getContext('2d'),{...U.fixtures[key],language:lang,bounds:false});return cv;};c.fillStyle='#13251b';c.fillRect(0,0,1200,1320);label('WILDCRAFT / CHARGER UI',30,30,16,'#a7bb9a');label('充电器界面 · 电量与共享供电',30,64,32);label('F04-04 v01 · 原生176×166 · 单槽与物品栏保持 · 草稿待审，未接入',30,111,17,'#ddb777');panel(30,150,557,550);label('充电中 · 500 / 1000',48,164,20);c.drawImage(full('charging'),45,198,528,498);panel(609,150,561,550);label('同一底图，共享五种状态',630,164,20);c.drawImage(imgs.panel,640,205,352,332);label('1 个电池槽 + 27 格背包 + 9 格快捷栏',630,560,18,'#dcb575');label('数字、物品、符号和电量条由程序绘制',630,598,17);label('状态行上移，为背包标题留出空间',630,634,17);label('复用采用电池、电量图标和五态符号',630,668,17);
label('五种状态 · 上半区 ×2；下方物品栏共享',30,730,22);U.states.forEach((st,i)=>{const x=30+(i%3)*390,y=777+Math.floor(i/3)*217;panel(x,y,371,204);label(st.zh,x+10,y+9,18);c.drawImage(full(st.key),0,0,176,76,x+9,y+39,352,152);});const x=820,y=1016;label('低像素保留准确数字',x,y,20,'#dcb575');B.drawReadout(c,{empty:imgs['battery-empty-16'],full:imgs['battery-full-16']},regions,1,true,x,y+44,2,'dark',2);B.drawReadout(c,{empty:imgs['battery-empty-16'],full:imgs['battery-full-16']},regions,999,true,x,y+92,2,'dark',2);label('无电池≠空电；等待≠缺电源',x,y+145,16);label('中英文短状态与完整悬停说明',30,1234,19);label('原生四层底图；字体为浏览器近似，正式游戏字体与提示框待接入验证。',30,1275,15,'#a3b69a');}
for(const st of U.states)get('scenario').add(new Option(st.zh,st.key));get('scenario').value='charging';get('scenario').onchange=e=>apply(e.target.value);get('language').onchange=()=>{update();drawGallery();};get('scale').onchange=drawLive;get('bounds').onchange=update;get('hover').onchange=drawLive;get('energy').oninput=e=>setEnergy(+e.target.value);get('number').oninput=e=>setEnergy(+e.target.value);
get('live').onmousemove=e=>{if(get('hover').value!=='auto')return;const cv=get('live'),r=cv.getBoundingClientRect(),x=(e.clientX-r.left)/(+get('scale').value),y=(e.clientY-r.top)/(+get('scale').value);const next=state.present&&x>=26&&x<42&&y>=35&&y<51?'battery':x>=8&&x<168&&y>=57&&y<71?'status':null;if(next!==hoverTarget){hoverTarget=next;drawLive();}};get('live').onmouseleave=()=>{if(hoverTarget){hoverTarget=null;drawLive();}};
window.ready=(async()=>{await Promise.all(Object.entries(sources).map(async([k,src])=>{const im=new Image();im.src=src;await im.decode();imgs[k]=im;}));for(const e of [0,1,99,100,333,500,667,999,1000]){const b=document.createElement('button');b.textContent=String(e);b.onclick=()=>{if(!state.present)state={...U.fixtures.charging,language:get('language').value,bounds:false};setEnergy(e)};get('samples').append(b)}update();drawGallery();drawBoard();window.appReady=true;return true})();
</script></html>'''
for token,value in [('__UI__',(R/'source/charger-ui.js').read_text()),('__READOUT__',(R/'references/battery-readout.js').read_text()),('__PHYSICAL__',(R/'references/battery-preview.js').read_text()),('__ASSETS__',json.dumps(assets)),('__REGIONS__',json.dumps(regions)),('__PHYSICALREGIONS__',json.dumps(physical))]:html=html.replace(token,value)
(R/'review/preview.html').write_text(html);print('自包含五态界面、悬停说明和审稿板已生成。',len(html))
