from pathlib import Path
import json,base64
from PIL import Image
R=Path(__file__).resolve().parents[1]
mesh=json.loads((R/'references/adopted-reference-meshes.json').read_text())
im=Image.open(R/'exports/fuse-unavailable-16.png').convert('RGBA')
verts=[];faces=[];boxes=[]
for y in range(16):
 for x in range(16):
  color=im.getpixel((x,y))
  if not color[3]:continue
  a=[(x-8)/16,-1/32,(7-y)/16];b=[(x-7)/16,1/32,(8-y)/16];i=len(verts)
  verts.extend([[a[0],a[1],a[2]],[b[0],a[1],a[2]],[b[0],b[1],a[2]],[a[0],b[1],a[2]],[a[0],a[1],b[2]],[b[0],a[1],b[2]],[b[0],b[1],b[2]],[a[0],b[1],b[2]]])
  faces.extend([{'indices':[i+j for j in v],'color':[c/255 for c in color[:3]]} for v in [[0,3,2,1],[4,5,6,7],[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7]]]);boxes.append({'min':a,'max':b,'pixel':[x,y]})
mesh['materials']['fallback']={'vertices':verts,'faces':faces,'note':'Review-only thin extrusion derived from actual native16 sprite; no production model authored'}
(R/'review/fallback-reference-boxes.json').write_text(json.dumps(boxes,indent=2)+'\n')
(R/'source/review-meshes.json').write_text(json.dumps(mesh,separators=(',',':'))+'\n')
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · 未知材料回退 v01</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#102017;color:#e1e8d8;font:16px/1.6 -apple-system,"PingFang SC",sans-serif}main{max-width:1250px;margin:auto;padding:28px 24px}h1{font-size:32px;margin:8px 0}h2{font-size:22px}.tag{color:#dfb776;font-size:14px}.muted,.small{color:#b4c5aa}.small{font-size:14px}p{margin:8px 0}.controls{display:flex;flex-wrap:wrap;gap:14px;padding:18px;background:#25372a;border:1px solid #4c5e46;border-radius:10px;margin:20px 0}label{display:flex;align-items:center;gap:8px;flex-wrap:wrap}select,button,input{font:inherit;max-width:100%}select,button{padding:8px;background:#16291c;color:inherit;border:1px solid #718368;border-radius:5px;min-height:42px}button{cursor:pointer}button:hover{background:#354b32}input[type=range]{width:125px;accent-color:#dbb678}:focus-visible{outline:3px solid #e4bf78;outline-offset:3px}.liveGrid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:20px}.panel{background:#1b2c21;border:1px solid #4c5e46;border-radius:10px;padding:18px;min-width:0}#live{display:block;width:100%;height:auto;max-width:520px;image-rendering:pixelated;touch-action:none;border-radius:5px}#slots{width:512px;max-width:100%;height:auto;image-rendering:pixelated}#tooltip{background:#151019;border:1px solid #655479;padding:18px;margin-top:16px}#stateTitle{font-size:20px;margin-top:0}#tooltipLines p{margin:8px 0;font-size:15px}.views{display:flex;gap:12px;flex-wrap:wrap;margin-top:14px}.board{width:100%;height:auto}.links{display:flex;gap:20px;flex-wrap:wrap;margin:22px 0}a{color:#e7c98a}@media(max-width:850px){.liveGrid{grid-template-columns:1fr}main{padding:20px 14px}h1{font-size:27px}.controls{padding:14px}}
</style><main><div class="tag">WILDCRAFT / F03-03 · v01 待视觉审稿</div><h1>未知材料 · 通用回退外观</h1><p class="muted">灰银色断开连接方片：同一原生16像素符号，用于材料不可用或显示资源故障。</p><div class="controls"><label>宿主<select id="host"><option value="sword">剑</option><option value="axe">斧</option><option value="shield">盾</option><option value="arrow">箭</option></select></label><label>状态<select id="phase"><option value="data-unavailable">材料数据不可用</option><option value="model-unavailable">显示资源不可用</option><option value="restored-reference">恢复后参考</option><option value="unfused">普通宿主</option></select></label><label>场景<select id="context"><option value="gui">物品展示</option><option value="held">手持参考</option><option value="back" id="backOption">背负参考</option><option value="ground">掉落参考</option><option value="flight" id="flightOption" disabled>飞行箭参考</option></select></label><label>次数参考<input id="uses" type="range" min="1" max="32" value="8"><span id="useLabel">8次</span></label><label>旋转<input id="angle" type="range" min="-180" max="180" value="0"><span id="angleLabel">0°</span></label><label><input id="light" type="checkbox">浅色背景</label></div><div class="liveGrid"><section class="panel"><canvas id="live" width="520" height="370" tabindex="0" role="img" aria-label="未知材料外观参考"></canvas><div class="views"><button id="front">正面</button><button id="side">侧面</button></div><p class="small">拖动旋转，或聚焦画布后用左右方向键观察。所有场景复用已采用挂点；箭没有背负状态。</p></section><section class="panel"><h2>槽位与说明参考</h2><canvas id="slots" width="256" height="88" role="img" aria-label="原生16与32宿主渲染参考"></canvas><div id="tooltip" aria-live="polite"><h2 id="stateTitle"></h2><p id="materialName"></p><div id="tooltipLines"></div></div><p id="stateHint" class="small"></p><p class="small">只有材料数据不可用才说明效果和拆卸停用。仅模型显示失败时，玩法仍遵循真实服务端状态。</p></section></div><h2>审稿总览</h2><canvas id="board" class="board" width="1200" height="1880" role="img" aria-label="未知材料回退外观审稿总览"></canvas><p class="small">原生符号为16×16；放大的符号保留整数像素。图中32px宿主是独立尺寸渲染，不是新画的32px回退贴图。所有宿主几何与状态均为美术参考，未接入游戏。</p><div class="links"><a href="/source/fuse-unavailable-16.aseprite">16px源稿</a><a href="/exports/fuse-unavailable-16.png">16px PNG</a><a href="/source/fuse-shared-atlas-64x32.aseprite">共享图集源稿</a><a href="/exports/fuse-shared-atlas-64x32.png">共享图集PNG</a><a href="/README.md">制作说明</a></div><p class="small">F03-02已采用 · 本项待审、未接入 · 采用后再制作F03-04</p></main><script>const SPEC=__SPEC__,MESH=__MESH__,BACK=__BACK__,ATLAS=__ATLAS__;</script><script>__RENDERER__</script><script>__REVIEW__</script></html>'''
for key,value in [('__SPEC__',(R/'references/adopted-mount-spec.json').read_text()),('__MESH__',json.dumps(mesh,separators=(',',':'))),('__BACK__',(R/'references/adopted-back-layout.json').read_text()),('__ATLAS__',json.dumps('data:image/png;base64,'+base64.b64encode((R/'exports/fuse-shared-atlas-64x32.png').read_bytes()).decode())),('__RENDERER__',(R/'source/native-reference-renderer.js').read_text()),('__REVIEW__',(R/'source/fallback-review.js').read_text())]:html=html.replace(key,value)
(R/'review/preview.html').write_text(html)
print('Review HTML created; sprite extrusion has',len(boxes),'opaque pixel cuboids')
