from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1]
def image(p):return 'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
G=json.loads((R/'source/geometry-and-uv.json').read_text());G['body']=json.loads((R/'references/approved-machine-geometry.json').read_text())
images={p.name:image(p)for folder in ['review','exports']for p in (R/folder).glob('*.png')if 'review'not in p.name}
snapshots=[dict(id='compressed',label='压缩 · 冷却0',cooldown=0,active=False,ghost=False),dict(id='fired',label='弹出 · 触发后40刻',cooldown=40,active=True,ghost=False),dict(id='cooling',label='弹出 · 冷却35刻',cooldown=35,active=False,ghost=False),dict(id='boundary31',label='边界 · 剩余31刻仍弹出',cooldown=31,active=False,ghost=False),dict(id='boundary30',label='边界 · 剩余30刻回压缩',cooldown=30,active=False,ghost=False),dict(id='cooling10',label='压缩 · 冷却10刻',cooldown=10,active=False,ghost=False),dict(id='ghost',label='安装预览 · 始终压缩',cooldown=40,active=True,ghost=True)]
(R/'source/review-snapshots.json').write_text(json.dumps(snapshots,ensure_ascii=False,indent=2)+'\n')
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · F05-06 弹簧 v01</title><style>
:root{color-scheme:dark;background:#14221c;color:#e7dec3;font:16px system-ui,sans-serif}*{box-sizing:border-box}body{margin:auto;padding:32px 24px;max-width:1240px}header small{color:#93b39e;letter-spacing:2px}h1{font-size:32px;margin:12px 0}p{line-height:1.7;color:#bbc7b5}h2{font-size:21px;margin-top:30px}main{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:20px}.panel,figure{background:#1c2d24;border:1px solid #354b3c;border-radius:14px;padding:18px;margin:0}canvas{display:block;width:100%;height:auto;border-radius:8px}button,select{background:#2c4235;color:#eee4ca;border:1px solid #59755e;border-radius:6px;padding:10px;min-height:40px;font:inherit;max-width:100%}button:hover{background:#405b47}label{display:block;margin:16px 0;font-size:14px;color:#c5cbb4}input[type=range]{width:100%;accent-color:#d6b078}strong{color:#f3e5bd}.note{font-size:13px}.chips{display:flex;gap:10px;flex-wrap:wrap}.chip{background:#304738;border-radius:6px;padding:8px 12px;font-size:13px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.grid img{width:100%;border-radius:8px}figcaption{font-size:13px;line-height:1.6;margin-top:8px}.icons{display:flex;gap:26px;flex-wrap:wrap}.pixel{image-rendering:pixelated}.icons img{width:128px;height:128px;background:#14221c;border:8px solid #24372b}.compare{display:grid;grid-template-columns:1fr 1fr;gap:18px}.compare img{width:100%}.atlas img{width:256px;max-width:100%;image-rendering:pixelated}a{color:#a3ddbb}@media(max-width:800px){main{grid-template-columns:1fr}.grid{grid-template-columns:repeat(2,1fr)}body{padding:24px 14px}h1{font-size:27px}.compare{gap:8px}}
</style><header><small>WILDCRAFT / B3 · F05-06</small><h1>弹簧 · 固定底座、连续螺旋与方形推板</h1><p>三圈钢制螺旋围绕伸缩导杆。弹出时推板向外移动，圈距展开；底座、钢丝粗细和安装尺度保持一致。</p><div class="chips"><span class="chip">v01 草稿待审</span><span class="chip">复用机械64×64图集</span><span class="chip">未接入游戏</span></div></header>
<h2>实际模型与两种姿态</h2><main><section class="panel"><canvas id="live" aria-label="弹簧实际模型"></canvas><p id="render-info" class="note"></p></section><aside class="panel"><label>状态快照<select id="snapshot"></select></label><label>安装视图<select id="node"><option value="-1">独立部件</option><option value="0">顶节点</option><option value="1">底节点</option><option value="2">后节点</option><option value="3">前节点</option><option value="4">左节点</option><option value="5">右节点</option></select></label><label>冷却剩余 <span id="ticks">0</span> / 40<input id="cooldown" type="range" min="0" max="40" value="0"></label><label>水平视角<input id="yaw" type="range" min="-180" max="180" value="-25"></label><label>俯仰视角<input id="pitch" type="range" min="-85" max="85" value="18"></label><button id="reset">恢复默认视图</button><p id="readout"></p><p class="note">31–40刻为弹出姿态；0–30刻为压缩姿态。安装预览始终压缩。此页手动展示状态，不自动模拟弹射。</p><p class="note">冷却归零并不表示已可再次弹射；还须满足停机、落地和服务端复位条件，每个就绪弹簧耗能20。</p></aside></main>
<h2>压缩与弹出 · 同尺度实际渲染</h2><section class="compare"><figure><img id="compressed-render"><figcaption>压缩 · 推板前缘5.76模型单位</figcaption></figure><figure><img id="extended-render"><figcaption>弹出 · 推板前缘8.96，行程3.20模型单位</figcaption></figure></section>
<h2>原生物品图标</h2><section class="panel"><div id="icons" class="icons"></div><p class="note">32与16分别绘制，选用展开的弹簧圈加强小尺寸辨识。以方形推板、绿垫、铜钉和分开的弹簧圈保持同一设计。</p></section>
<h2>六向安装参考</h2><section id="mounts" class="grid"></section><p class="note">图示弹出姿态。交互视图可查看每个节点的压缩、弹出和透明预览；推板沿外法线移动，弹射方向相反。</p>
<h2>统一纹理图集</h2><section class="panel atlas"><img id="atlas"><p class="note">完整复用已采用机械64×64图集，新增生产贴图像素为0。钢、铜、绿垫和导杆使用统一UV区域。</p></section>
<h2>综合审稿板</h2><section class="panel"><canvas id="board"></canvas><p><a href="spring-review.png">打开审稿板 PNG</a></p></section><p class="note">本轮仅美术交付，源稿、姿态参数和检查记录已存档。尚未在游戏里验证装配或弹射。</p>
<script>const G=__G__,SOURCES=__IMAGES__,SNAPSHOTS=__SNAPSHOTS__;</script><script>__RENDER__</script><script>
const loaded={},names=['顶','底','后','前','左','右'];window.reviewReady=false;
function current(){const s=SNAPSHOTS.find(s=>s.id===document.querySelector('#snapshot').value)||SNAPSHOTS[0];return {...s,cooldown:+document.querySelector('#cooldown').value}}
function redraw(){const s=current(),p=WildcraftSpringPreview.presentation(s),n=+document.querySelector('#node').value;window.lastPresentation=p;window.lastRender=WildcraftSpringPreview.drawModel(document.querySelector('#live'),loaded['shared-machine-atlas-64.png'],{...G,...p},+document.querySelector('#yaw').value,+document.querySelector('#pitch').value,n);document.querySelector('#ticks').textContent=p.cooldown;document.querySelector('#render-info').textContent=`${p.extended?'弹出':'压缩'} · ${n<0?'独立部件':names[n]+'节点'} · ${p.ghost?'透明安装预览':'实际材质'}`;document.querySelector('#readout').innerHTML=`<strong>${p.extended?'弹出':'压缩'} · 冷却 ${p.cooldown} / 40 世界刻</strong><br>推板行程 ${p.extended?'3.20':'0.00'} 模型单位<br><span class="note">每个就绪弹簧耗能20；再次弹射由服务端条件决定。</span>`;}
document.querySelector('#snapshot').addEventListener('input',()=>{document.querySelector('#cooldown').value=SNAPSHOTS.find(s=>s.id===document.querySelector('#snapshot').value).cooldown;redraw()});for(const id of ['node','cooldown','yaw','pitch'])document.querySelector('#'+id).addEventListener('input',redraw);document.querySelector('#reset').onclick=()=>{document.querySelector('#node').value=-1;document.querySelector('#snapshot').value='compressed';document.querySelector('#cooldown').value=0;document.querySelector('#yaw').value=-25;document.querySelector('#pitch').value=18;redraw()};
function board(){const c=document.querySelector('#board');c.width=1200;c.height=1870;const x=c.getContext('2d');x.fillStyle='#14221c';x.fillRect(0,0,c.width,c.height);const text=(s,a,b,size=22,col='#e7dec3')=>{x.fillStyle=col;x.font=`${size}px system-ui`;x.fillText(s,a,b)},image=(n,a,b,w,h,pixel=false)=>{x.imageSmoothingEnabled=!pixel;x.drawImage(loaded[n],a,b,w,h)};
text('WILDCRAFT · F05-06 / v01',40,50,22,'#93b39e');text('弹簧 · 连续螺旋与方形推板',40,101,36);text('草稿待审 / 原生32与16分别绘制 / 未接入游戏',40,139,19,'#b1bca8');image('spring-compressed-three-quarter.png',40,163,540,540);image('spring-extended-three-quarter.png',620,163,540,540);text('压缩 · 前缘5.76',54,735,22);text('弹出 · 前缘8.96 / 行程3.20',634,735,22);
image('spring-item-32.png',90,782,160,160,true);image('spring-item-16.png',370,782,160,160,true);text('32×32 独立像素稿',80,975,20);text('16×16 独立像素稿',355,975,20);text('三圈螺旋 · 钢丝粗细固定',620,822,25);text('固定底座 / 伸缩导杆 / 绿垫推板',620,870,22);text('64×64统一图集，新增贴图像素0',620,915,21);
text('六向安装 · 弹出姿态 · 保持现有节点与尺度',40,1044,24);for(let i=0;i<6;i++){const a=40+i%3*383,b=1070+Math.floor(i/3)*330;image('spring-extended-mounted-'+i+'.png',a+18,b,300,300);text(names[i]+'节点',a+20,b+319,20)}
text('31–40刻弹出；0–30刻压缩；安装预览始终压缩。',40,1760,23);text('冷却0不直接代表已复位；停机与落地条件沿用现有机制。',40,1806,21);text('实际网格、可编辑源稿、原生图标与检查记录已存档。',40,1845,20,'#b1bca8');}
(async()=>{for(const[n,src]of Object.entries(SOURCES)){const im=new Image();im.src=src;await im.decode();loaded[n]=im;}document.querySelector('#snapshot').innerHTML=SNAPSHOTS.map(s=>`<option value="${s.id}">${s.label}</option>`).join('');for(const p of ['compressed','extended'])document.querySelector('#'+p+'-render').src=SOURCES['spring-'+p+'-three-quarter.png'];document.querySelector('#atlas').src=SOURCES['shared-machine-atlas-64.png'];document.querySelector('#icons').innerHTML=[32,16].map(n=>`<figure><img class="pixel" alt="弹簧${n}像素" src="${SOURCES['spring-item-'+n+'.png']}"><figcaption>${n}×${n} · 弹簧圈展开</figcaption></figure>`).join('');document.querySelector('#mounts').innerHTML=names.map((n,i)=>`<figure><img alt="${n}节点安装" src="${SOURCES['spring-extended-mounted-'+i+'.png']}"><figcaption>${n}节点 · 推板向外 / 弹射反向</figcaption></figure>`).join('');redraw();board();window.reviewReady=true;})().catch(e=>{window.reviewError=e.message;document.querySelector('#render-info').textContent=e.message});
</script></html>'''
html=html.replace('__G__',json.dumps(G,separators=(',',':'),ensure_ascii=False)).replace('__IMAGES__',json.dumps(images,separators=(',',':'))).replace('__SNAPSHOTS__',json.dumps(snapshots,separators=(',',':'),ensure_ascii=False)).replace('__RENDER__',(R/'source/spring-preview.js').read_text());(R/'review/preview.html').write_text(html);print('Spring actual mesh review ready')
