from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1]
old=(R.parents[1]/'F04-01/v01/source/battery-preview.js').read_text()
draw=old[old.index('function drawModel'):old.index('root.WildcraftBatteryPreview=')]
draw=draw.replace('yaw=-25,pitch=18)','yaw=-25,pitch=18,present=true,state=2)').replace('makeFaces(geo,energy)','makeFaces(geo,energy,present,state)').replace('z-=8.16','z-=8').replace('p[0]*42/320','-p[0]*22/320').replace('-p[1]*42/225','-p[1]*22/225').replace('modelCuboids:geo.parts.length','modelCuboids:geo.parts.length,batteryCuboids:present?geo.batteryParts.length:0,state,present')
make='''function fractions(e){const q=Math.max(0,Math.min(1000,e))/1000*3;return [0,1,2].map(i=>Math.max(0,Math.min(1,q-i)));}
function makeFaces(geo,e,present=true,state=2){const faces=[],normals={north:[0,0,-1],south:[0,0,1],west:[-1,0,0],east:[1,0,0],up:[0,1,0],down:[0,-1,0]};
for(const p of [...geo.parts,...(present?geo.batteryParts:[])]){const [x0,y0,z0]=p.from,[x1,y1,z1]=p.to;
const v={south:[[x1,y1,z1],[x0,y1,z1],[x0,y0,z1],[x1,y0,z1]],north:[[x0,y1,z0],[x1,y1,z0],[x1,y0,z0],[x0,y0,z0]],west:[[x0,y1,z1],[x0,y1,z0],[x0,y0,z0],[x0,y0,z1]],east:[[x1,y1,z0],[x1,y1,z1],[x1,y0,z1],[x1,y0,z0]],up:[[x0,y1,z1],[x1,y1,z1],[x1,y1,z0],[x0,y1,z0]],down:[[x0,y0,z0],[x1,y0,z0],[x1,y0,z1],[x0,y0,z1]]};for(const [dir,points] of Object.entries(v))faces.push({name:p.name,vertices:points,normal:normals[dir],uv:p.faces[dir].uv});}
const q=geo.statusPanel;let [x0,y0,z]=q.from,[x1,y1]=q.to;faces.push({name:'status/'+state,vertices:[[x1,y1,z],[x0,y1,z],[x0,y0,z],[x1,y0,z]],normal:[0,0,1],uv:q.tiles[state]});
if(present){for(const w of geo.batteryWindows){const a=fractions(e)[w.indexBottomUp];if(a>0){const [x0,y0,z]=w.from,[x1,ymax]=w.to,y1=y0+(ymax-y0)*a;const [u0,v0,u1,v1]=geo.batteryEnergyUV;faces.push({name:'energy/'+w.indexBottomUp,vertices:[[x1,y1,z],[x0,y1,z],[x0,y0,z],[x1,y0,z]],normal:[0,0,1],uv:[u0,v0+(v1-v0)*(1-a),u1,v1]});}}}return faces;}
'''
js='(function(root){\n'+make+draw+'root.WildcraftChargerPreview={fractions,makeFaces,drawModel};})(globalThis);\n'
(R/'source/charger-preview.js').write_text(js)
images={name:'data:image/png;base64,'+base64.b64encode((R/'review'/name).read_bytes()).decode() for name in ['charger-state-'+str(i)+'.png' for i in range(5)]+['charger-empty-front.png','charger-back.png','charger-battery-fit-exploded.png']}
images['atlas']='data:image/png;base64,'+base64.b64encode((R/'exports/charger-atlas-64.png').read_bytes()).decode()
g=json.loads((R/'source/geometry-and-uv.json').read_text())
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · 充电器模型 v01</title><style>
*{box-sizing:border-box}body{margin:0;background:#14231b;color:#e2e9dc;font:15px system-ui,"PingFang SC",sans-serif}main{max-width:1240px;padding:28px 24px;margin:auto}h1{font-size:29px;margin:10px 0}p{color:#b2c1ae;line-height:1.75}.tag{color:#ddb675}.controls{display:flex;flex-wrap:wrap;gap:16px;background:#253729;border:1px solid #465c44;padding:16px;border-radius:6px}label{display:flex;align-items:center;gap:8px}select,input{accent-color:#b9432c;background:#19281f;color:#e2e9dc;padding:6px;border:1px solid #657760;border-radius:3px}button{cursor:pointer;background:#304732;color:#e2e9dc;border:1px solid #657760;border-radius:4px;padding:8px 12px}.row{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:18px 0}.panel{background:#253729;border:1px solid #465c44;border-radius:6px;padding:16px;min-width:0}.panel h2{font-size:17px;margin:0 0 12px}canvas.model{width:100%;height:auto;display:block}img{max-width:100%;height:auto}#render{display:block}.pixel{image-rendering:pixelated}.small{font-size:13px;color:#a6b99e}.poses{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}.board{width:100%;height:auto}a{color:#d3dfbd}@media(max-width:980px){.row{grid-template-columns:1fr}main{padding:20px 14px}}
</style><main><span class="tag">F04-03 · v01 · 草稿待审 · 未接入游戏</span><h1>充电器 · 原尺寸电池嵌入槽</h1><p>钢色支柱、铜接点、开放式单槽。电池沿用 F04-01 已采用模型，比例 1.00；一张原生64px图集同时服务充电器与电池。五态状态窗用不同形状辅助识别。</p>
<div class="controls"><label>状态<select id="state"><option value="0">没有电池</option><option value="1">缺少固定红石源</option><option selected value="2">充电中</option><option value="3">已充满</option><option value="4">等待共享供电</option></select></label><label>余量<input id="energy" type="range" min="0" max="1000" value="500"><output id="value">500 / 1000</output></label><label>朝向<input id="yaw" type="range" min="-180" max="180" value="-25"></label><label>俯仰<input id="pitch" type="range" min="-65" max="65" value="18"></label></div><div class="poses"><button data-yaw="0">正面</button><button data-yaw="-25">斜侧面</button><button data-yaw="180">背面</button><button data-yaw="90">侧面</button></div>
<div class="row"><section class="panel"><h2>实际几何交互查看</h2><canvas class="model" id="model" width="640" height="450"></canvas><p id="reading"></p><p class="small">五态及电量为审稿输入。当前游戏仅向充电菜单同步状态，世界中的电池和状态灯需要后续接入。</p></section><section class="panel"><h2>实际模型与UV渲染</h2><img id="render"><p class="small" id="render-note"></p></section></div>
<section class="panel"><h2>五种状态形状 · 同一原生图集</h2><canvas class="pixel" id="glyphs" width="320" height="64" style="max-width:100%;width:640px"></canvas><p class="small">空框：无电池；断线：缺电源；箭头：充电；勾：充满；双竖线：等待。无闪烁、光柱或发光Shader。</p></section>
<canvas class="board" id="board" width="1200" height="1720"></canvas><p>六个相邻方向的固定红石块均遵循现有供电规则；铜饰面不是限定方向的插口。正面保持固定 +Z，未新增旋转方块状态或改变完整方块碰撞。完整充电器界面在 F04-04 制作。</p></main>
<script>__JS__</script><script>
const G=__G__,sources=__IMAGES__,assets={},C=WildcraftChargerPreview,names=['没有电池','缺少电源','充电中','已充满','等待共享供电'];function get(id){return document.getElementById(id)}
function update(){let s=+get('state').value,e=+get('energy').value;if(s===0)e=0;else if(s===3)e=1000;else if(e===1000)s=3;get('state').value=s;get('energy').value=e;get('energy').disabled=s===0;const present=s!==0;get('value').textContent=present?e+' / 1000':'— / 1000';const info=C.drawModel(get('model'),assets.atlas,G,e,+get('yaw').value,+get('pitch').value,present,s);get('reading').textContent=names[s]+' · '+get('value').textContent;get('render').src=sources['charger-state-'+s+'.png'];get('render-note').textContent='静态渲染中的电量：'+(s===0?'没有电池':s===3?'1000 / 1000':'500 / 1000')+'；左侧模型跟随当前余量。';window.currentState={s,e,present,info};}
function setEnergy(e){if(+get('state').value===3&&e<1000)get('state').value=2;get('energy').value=e;update();}
function text(c,s,x,y,size=18,color='#dde6d4',bold=false){c.fillStyle=color;c.font=(bold?'600 ':'')+size+'px system-ui,"PingFang SC",sans-serif';c.fillText(s,x,y)}
function panel(c,x,y,w,h){c.fillStyle='#263a2b';c.fillRect(x,y,w,h);c.strokeStyle='#445f43';c.strokeRect(x+.5,y+.5,w-1,h-1)}
function drawBoard(){const c=get('board').getContext('2d');c.fillStyle='#14251b';c.fillRect(0,0,1200,1720);text(c,'WILDCRAFT / CHARGER',38,47,16,'#a6ba98',true);text(c,'充电器 · 单槽、铜接点与五态提示',38,94,32,'#e2ead9',true);text(c,'F04-03 v01 · 实际模型与原生纹理 · 草稿待审 · 未接入游戏',38,127,17,'#dfb778');
for(const [i,caption] of [[2,'装入原电池 · 500 / 1000'],[0,'移除电池 · 空槽与接点可见']]){const x=i===2?38:612;panel(c,x,153,550,554);text(c,caption,x+16,182,18,'#c1d2b5',true);c.drawImage(assets['charger-state-'+i+'.png'],x+25,195,500,500);}
text(c,'30个固定方盒 + 独立状态面；电池保持 6.4 × 7.36 × 1.93 模型单位。',38,739,18,'#c1d2b5');text(c,'五种状态 · 形状与颜色共同提示',38,788,24,'#e2ead9',true);
for(let i=0;i<5;i++){const x=38+i*226;panel(c,x,811,214,278);text(c,names[i],x+12,839,17,'#c1d2b5',true);c.drawImage(assets['charger-state-'+i+'.png'],x+12,850,190,190);c.imageSmoothingEnabled=false;c.drawImage(assets.atlas,i*8,48,8,8,x+14,1045,32,32);c.imageSmoothingEnabled=true;text(c,i===0?'— / 1000':i===3?'1000 / 1000':'500 / 1000',x+60,1067,16);}
text(c,'安装与供电阅读',38,1140,24,'#e2ead9',true);const views=[['charger-empty-front.png','空槽：双铜点对应电池背面'],['charger-battery-fit-exploded.png','安装参照：电池比例 1.00'],['charger-back.png','背面与侧面：铜面及金属外壳']];views.forEach(([key,label],i)=>{const x=38+i*382;panel(c,x,1163,360,397);text(c,label,x+12,1193,16,'#c1d2b5',true);c.drawImage(assets[key],x+9,1204,342,342);});
text(c,'共享图集：原电池32px区域原样嵌入；状态符号5个8px图块共用同一材质。',38,1608,18,'#c1d2b5');text(c,'六向固定红石源规则保持；不增加线缆、第二个电池槽或能量等级。',38,1645,18,'#c1d2b5');text(c,'世界电池/状态灯尚无同步接入；本页五态为审稿模拟。完整GUI下一项制作。',38,1684,16,'#dcb46f');}
window.ready=(async()=>{await Promise.all(Object.entries(sources).map(async([key,src])=>{const im=new Image();im.src=src;await im.decode();assets[key]=im;}));get('state').onchange=update;get('energy').oninput=()=>setEnergy(+get('energy').value);get('yaw').oninput=get('pitch').oninput=update;document.querySelectorAll('[data-yaw]').forEach(b=>b.onclick=()=>{get('yaw').value=b.dataset.yaw;get('pitch').value=18;update()});const gc=get('glyphs').getContext('2d');gc.imageSmoothingEnabled=false;for(let i=0;i<5;i++)gc.drawImage(assets.atlas,i*8,48,8,8,8+i*64,8,48,48);update();drawBoard();window.appReady=true;return true})();
</script></html>'''
html=html.replace('__JS__',js).replace('__G__',json.dumps(g)).replace('__IMAGES__',json.dumps(images));(R/'review/preview.html').write_text(html);print('自包含审稿页与实际几何查看器已生成。',len(html))
