/* Dependency-free review renderer using actual model cuboids and native atlas. */
(function(root){
const capacity=1000;
function fractions(energy){const q=Math.max(0,Math.min(capacity,energy))/capacity*3;return [0,1,2].map(i=>Math.max(0,Math.min(1,q-i)));}
function drawIcon(c,img,regions,n,energy,x=0,y=0,scale=1){c.save();c.translate(x,y);c.scale(scale,scale);c.imageSmoothingEnabled=false;c.drawImage(img,0,0,n,n);const values=fractions(energy),visible=[];regions.slice().reverse().forEach((r,i)=>{const width=Math.floor(r.w*values[i]);visible.push(width);if(width){c.fillStyle='#bc2323';c.fillRect(r.x,r.y,width,r.h);c.fillStyle='#ed4b2d';c.fillRect(r.x,r.y,Math.max(1,width-1),1);if(width>2){c.fillStyle='#ff9457';c.fillRect(r.x+1,r.y,Math.max(1,width-3),1);}if(r.h>1){c.fillStyle='#78151c';c.fillRect(r.x+Math.max(0,width-2),r.y+1,Math.min(2,width),r.h-1);}}});c.restore();return {energy,fractions:values,visiblePixelWidths:visible};}
function makeFaces(geo,energy){const f=[],normals={north:[0,0,-1],south:[0,0,1],west:[-1,0,0],east:[1,0,0],up:[0,1,0],down:[0,-1,0]};for(const part of geo.parts){const [x0,y0,z0]=part.from,[x1,y1,z1]=part.to;const verts={south:[[x0,y1,z1],[x1,y1,z1],[x1,y0,z1],[x0,y0,z1]],north:[[x1,y1,z0],[x0,y1,z0],[x0,y0,z0],[x1,y0,z0]],west:[[x0,y1,z0],[x0,y1,z1],[x0,y0,z1],[x0,y0,z0]],east:[[x1,y1,z1],[x1,y1,z0],[x1,y0,z0],[x1,y0,z1]],up:[[x0,y1,z0],[x1,y1,z0],[x1,y1,z1],[x0,y1,z1]],down:[[x0,y0,z1],[x1,y0,z1],[x1,y0,z0],[x0,y0,z0]]};for(const [dir,v] of Object.entries(verts))f.push({name:part.name,vertices:v,normal:normals[dir],uv:part.faces[dir].uv});}
const values=fractions(energy);for(const window of geo.windows){const amount=values[window.indexBottomUp];if(amount>0){const [x0,y0,z0]=window.from,[x1,ymax]=window.to,y1=y0+(ymax-y0)*amount;f.push({name:'energy'+window.indexBottomUp,vertices:[[x0,y1,z0],[x1,y1,z0],[x1,y0,z0],[x0,y0,z0]],normal:[0,0,1],uv:[6,8+4*(1-amount),12,12]});}}
return f;}
function drawModel(canvas,atlas,geo,energy,yaw=-25,pitch=18){
canvas.width=640;canvas.height=450;let cache=canvas._batteryGl;
if(!cache){const gl=canvas.getContext('webgl',{preserveDrawingBuffer:true,alpha:false,antialias:true});if(!gl)throw new Error('Review WebGL unavailable');
 const shader=(type,code)=>{const sh=gl.createShader(type);gl.shaderSource(sh,code);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(sh));return sh;};
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 position; attribute vec2 uv; attribute float shade; varying vec2 vUv; varying float vShade; void main(){gl_Position=vec4(position,1.0);vUv=uv;vShade=shade;}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float; varying vec2 vUv; varying float vShade; uniform sampler2D atlas; void main(){vec4 c=texture2D(atlas,vUv);if(c.a<0.5)discard;gl_FragColor=vec4(c.rgb*vShade,1.0);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));
 const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,atlas);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
 cache=canvas._batteryGl={gl,program,texture,buffer:gl.createBuffer(),locations:['position','uv','shade'].map(k=>gl.getAttribLocation(program,k))};}
const {gl,program,texture,buffer,locations}=cache;gl.viewport(0,0,640,450);gl.clearColor(.094,.137,.114,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.useProgram(program);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(gl.getUniformLocation(program,'atlas'),0);
const ya=yaw*Math.PI/180,pa=pitch*Math.PI/180,cy=Math.cos(ya),sy=Math.sin(ya),cp=Math.cos(pa),sp=Math.sin(pa);const transform=(v,position)=>{let [x,y,z]=v;if(position){x-=8;y-=8;z-=8.16;}const xx=x*cy+z*sy,zz=z*cy-x*sy;return [xx,-y*cp+zz*sp,y*sp+zz*cp];};
const faces=makeFaces(geo,energy).map(f=>({...f,normal:transform(f.normal,false),points:f.vertices.map(v=>transform(v,true))})).filter(f=>f.normal[2]>.001),data=[];
for(const face of faces){const [u0,v0,u1,v1]=face.uv.map(v=>v/16),uvs=[[u0,1-v0],[u1,1-v0],[u1,1-v1],[u0,1-v1]],light=Math.max(.48,Math.min(1,.58+face.normal[0]*.15-face.normal[1]*.22+face.normal[2]*.25));for(const idx of [0,1,2,0,2,3]){const p=face.points[idx];data.push(p[0]*42/320,-p[1]*42/225,-p[2]/16,...uvs[idx],light);}}
gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.DYNAMIC_DRAW);for(let i=0;i<3;i++){gl.enableVertexAttribArray(locations[i]);gl.vertexAttribPointer(locations[i],[3,2,1][i],gl.FLOAT,false,24,[0,12,20][i]);}gl.drawArrays(gl.TRIANGLES,0,data.length/6);
return {energy,fractions:fractions(energy),visibleFaces:faces.length,yaw,pitch,modelCuboids:geo.parts.length,depthTest:true};
}
root.WildcraftBatteryPreview={capacity,fractions,drawIcon,drawModel,makeFaces};if(typeof module!=='undefined')module.exports=root.WildcraftBatteryPreview;
})(typeof globalThis!=='undefined'?globalThis:this);
