from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1];old=(R.parents[1]/'F05-01/v01/source/machine-preview.js').read_text();draw=old[old.index('function drawModel'):old.index('root.WildcraftMachinePreview=')]
draw=draw.replace('energy,yaw=-25,pitch=18,node=-1','angle=0,yaw=-25,pitch=18,node=-1').replace('makeFaces(geo,energy,node)','makeFaces(geo,angle,node)').replace('y-=5.2;','').replace('Math.min(21,','Math.min(48,')
start=draw.index('for(const face of faces){');end=draw.index('gl.bindBuffer(gl.ARRAY_BUFFER',start)
draw=draw[:start]+'''for(const face of faces){const light=Math.max(.48,Math.min(1,.58+face.normal[0]*.15-face.normal[1]*.22+face.normal[2]*.25));for(let i=1;i<face.points.length-1;i++)for(const idx of [0,i,i+1]){const p=face.points[idx],[u,v]=face.uvs[idx];data.push(-(p[0]-fit.cx)*fit.scale/320,-(p[1]-fit.cy)*fit.scale/225,-p[2]/64,u/16,1-v/16,light);}}
'''+draw[end:]
start=draw.index('return {energy');end=draw.index(';',start);draw=draw[:start]+"return {angle,node,visibleFaces:faces.length,fanParts:geo.parts.length,movingParts:geo.parts.filter(p=>p.group==='rotor').length,fixedParts:geo.parts.filter(p=>p.group==='housing').length,referenceBody:node>=0,depthTest:true,fit}"+draw[end:]
make=r'''function rotate(v,n){const [x,y,z]=v;return [[x,z,-y],[x,-z,y],[-x,y,-z],[x,y,z],[-z,y,x],[z,y,-x]][n];}
function rotorPoint(v,angle,pivot){const [x,y,z]=v,c=Math.cos(angle),s=Math.sin(angle);return [x*c-y*s,x*s+y*c,z];}
function mount(v,node,g){return node<0?v:rotate(v,node).map((a,i)=>a+g.body.nodes[node].point[i]);}
function rawBox(p,g){const [x0,y0,z0]=p.from,[x1,y1,z1]=p.to,vs=[[x0,y0,z0],[x1,y0,z0],[x1,y1,z0],[x0,y1,z0],[x0,y0,z1],[x1,y0,z1],[x1,y1,z1],[x0,y1,z1]],fm={north:[0,1,2,3],south:[5,4,7,6],east:[1,5,6,2],west:[4,0,3,7],up:[3,2,6,7],down:[4,5,1,0]};return {name:p.name,vertices:p.node===undefined?vs:vs.map(v=>mount(v,p.node,g)),faces:Object.entries(fm).map(([key,indices])=>{const [u0,v0,u1,v1]=p.faces[key].uv;return {indices,uvs:[[u0,v1],[u1,v1],[u1,v0],[u0,v0]]}})};}
function makeFaces(g,angle=0,node=-1){const parts=g.parts.map(p=>({...p,vertices:p.vertices.map(v=>mount(p.group==='rotor'?rotorPoint(v,angle,g.rotorPivot):v,node,g))}));if(node>=0)parts.push(...g.body.parts.map(p=>rawBox(p,g)));const out=[];for(const p of parts){const center=[0,1,2].map(i=>p.vertices.reduce((s,v)=>s+v[i],0)/p.vertices.length);for(const f of p.faces){const points=f.indices.map(i=>p.vertices[i]),a=points[1].map((v,i)=>v-points[0][i]),b=points[2].map((v,i)=>v-points[0][i]);let normal=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],len=Math.hypot(...normal);normal=normal.map(v=>v/len);const fc=[0,1,2].map(i=>points.reduce((s,v)=>s+v[i],0)/points.length);if(normal.reduce((s,v,i)=>s+v*(fc[i]-center[i]),0)<0)normal=normal.map(v=>-v);out.push({name:p.name,vertices:points,normal,uvs:f.uvs});}}return out;}
function angleFor(age,active,ghost=false){return active&&!ghost?age*.7:0;}
'''
js='(function(root){\n'+make+draw+'root.WildcraftFanPreview={rotate,mount,rotorPoint,makeFaces,angleFor,drawModel};})(globalThis);\n';(R/'source/fan-preview.js').write_text(js)
images={name:'data:image/png;base64,'+base64.b64encode((R/'review'/name).read_bytes()).decode()for name in ['fan-idle-three-quarter.png','fan-front.png','fan-back.png','fan-side.png','fan-running-phase.png','fan-mounted-front.png','fan-mounted-top.png']}
for key,name in [('atlas','shared-machine-atlas-64.png'),('icon32','fan-item-32.png'),('icon16','fan-item-16.png')]:images[key]='data:image/png;base64,'+base64.b64encode((R/'exports'/name).read_bytes()).decode()
g=json.loads((R/'source/geometry-and-uv.json').read_text());g['body']=json.loads((R/'references/approved-machine-geometry.json').read_text())
html=r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · 风扇 v01</title><style>
*{box-sizing:border-box}body{margin:0;background:#14231b;color:#e2e9dc;font:15px/1.75 system-ui,"PingFang SC",sans-serif}main{max-width:1240px;padding:28px 24px;margin:auto}h1{font-size:29px;margin:10px 0}h2{font-size:18px}p{color:#b2c1ae}.tag{color:#ddb675}.controls{display:flex;flex-wrap:wrap;gap:16px;background:#253729;border:1px solid #465c44;padding:16px;border-radius:6px}label{display:flex;align-items:center;gap:8px}select,input{accent-color:#bc6542;background:#19281f;color:#e2e9dc;padding:6px;border:1px solid #657760;border-radius:3px}input[type=range]{width:145px}button{cursor:pointer;background:#304732;color:#e2e9dc;border:1px solid #657760;border-radius:4px;padding:8px 12px}:focus-visible{outline:3px solid #dfb778;outline-offset:3px}.row{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:18px 0}.panel{background:#253729;border:1px solid #465c44;border-radius:6px;padding:16px;min-width:0}.panel h2{margin:0 0 12px}.model{width:100%;height:auto;display:block}.panel img{width:100%;height:auto;display:block}.small{font-size:13px;color:#a6b99e}.poses{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}.board{width:100%;height:auto}.icons{display:flex;gap:24px;flex-wrap:wrap;align-items:center}.icons img{image-rendering:pixelated;width:128px;height:128px}.icons span{display:block;color:#c8d6bd;font-size:14px}.note{color:#dfb778}@media(max-width:980px){.row{grid-template-columns:1fr}main{padding:20px 14px}}
</style><main><span class="tag">F05-03 · v01 · 草稿待审 · 未接入游戏</span><h1>风扇 · 开放护框、四叶与铜轮毂</h1><p>固定护框与四片同向叶片分组；保留现轴心与安装尺度。复用采用主体64px材质，停转、运转和安装参考共用同一模型。</p>
<div class="controls"><label>装配<select id="node"><option value="-1">单独风扇</option><option value="0">顶节点</option><option value="1">底节点</option><option value="2">后节点</option><option value="3">前节点</option><option value="4">左节点</option><option value="5">右节点</option></select></label><label>表现<select id="motion"><option value="idle">停转</option><option value="running">实际供电 · 运转</option><option value="preview">安装参考 · 静止</option></select></label><label>动作查看<select id="play"><option value="step">手动定格</option><option value="play">播放</option></select></label><label>动作时间<input id="age" type="range" min="0" max="100" step="0.01" value="0"><output id="value"></output></label><label>朝向<input id="yaw" type="range" min="-180" max="180" value="-25"></label><label>俯仰<input id="pitch" type="range" min="-85" max="85" value="18"></label></div>
<div class="poses"><button data-yaw="-25" data-pitch="18">斜侧面</button><button data-yaw="0" data-pitch="0">正面</button><button data-yaw="180" data-pitch="18">背面</button><button data-yaw="90" data-pitch="0">侧面</button><button data-yaw="0" data-pitch="85">顶面</button><button data-yaw="-25" data-pitch="-65">底面</button></div>
<div class="row"><section class="panel"><h2>实际模型 · 旋转与六节点参考</h2><canvas id="model" class="model" width="640" height="450" role="img" aria-label="风扇实际模型"></canvas><p id="reading" aria-live="polite"></p><p class="small">运转仅旋转叶轮；护框不转。安装参考保持静止，本页不提供正式吸附提示。无闪烁、运动模糊或旋风贴图。</p></section><section class="panel"><h2>实际模型与共用纹理渲染</h2><img id="render" alt="风扇实际模型渲染"><p class="small" id="render-note"></p></section></div>
<section class="panel"><h2>原生物品图 · 两种尺寸独立设计</h2><div class="icons"><div><img id="icon32" alt="32像素风扇"><span>32×32 · 薄框、四叶与后侧厚度</span></div><div><img id="icon16" alt="16像素风扇"><span>16×16 · 合并细节，保留铜轴心与四叶</span></div></div></section>
<p class="note">排风沿接口外向轴，推力方向相反；六向节点与现推进规则保持。停转可能是关机或没有实际供电，不能仅凭电池存在判断运转。</p><canvas id="board" class="board" width="1200" height="1540"></canvas></main><script>__JS__</script><script>
const G=__G__,sources=__IMAGES__,assets={},F=WildcraftFanPreview;function get(id){return document.getElementById(id)}let age=0,lastTime=null;
function update(){age=+get('age').value;const node=+get('node').value,state=get('motion').value,active=state==='running',ghost=state==='preview',angle=F.angleFor(age,active,ghost),yaw=+get('yaw').value,pitch=+get('pitch').value;const info=F.drawModel(get('model'),assets.atlas,G,angle,yaw,pitch,node);get('value').textContent=Math.round((angle%(2*Math.PI))*180/Math.PI)+'°';const exhaust=node<0?[0,0,1]:F.rotate([0,0,1],node),thrust=exhaust.map(v=>v===0?0:-v);get('reading').textContent=(node<0?'单独风扇':G.body.nodes[node].name+'节点')+' · '+(active?'四叶运转':ghost?'安装参考静止':'停转')+(node>=0?' · 排风 ['+exhaust+']，推力 ['+thrust+']':'');const im=node===3?'fan-mounted-front.png':node===0?'fan-mounted-top.png':yaw>120||yaw<-120?'fan-back.png':Math.abs(yaw)>70&&Math.abs(yaw)<110?'fan-side.png':active?'fan-running-phase.png':'fan-idle-three-quarter.png';get('render').src=sources[im];get('render-note').textContent=im.includes('mounted')?'采用主体上的尺寸参考，未接入游戏。':'静态真实渲染；左侧模型跟随动作输入。';window.currentState={node,state,age,angle,active,ghost,yaw,pitch,exhaust,thrust,info};}
function loop(t){if(get('play').value==='play'&&get('motion').value==='running'&&!document.hidden&&!matchMedia('(prefers-reduced-motion: reduce)').matches){if(lastTime!==null){get('age').value=(+get('age').value+Math.min(100,t-lastTime)/1000*20)%100;update();}}lastTime=t;requestAnimationFrame(loop);}
function drawBoard(){const c=get('board').getContext('2d');c.fillStyle='#14251b';c.fillRect(0,0,1200,1540);const text=(s,x,y,size=18,color='#dde6d4')=>{c.fillStyle=color;c.font=size+'px system-ui,"PingFang SC",sans-serif';c.textBaseline='top';c.fillText(s,x,y)};const panel=(x,y,w,h)=>{c.fillStyle='#263a2b';c.fillRect(x,y,w,h);c.strokeStyle='#445f43';c.strokeRect(x+.5,y+.5,w-1,h-1)};text('WILDCRAFT / FAN MODULE',30,25,16,'#a7bb99');text('风扇 · 开放护框与四叶轮毂',30,60,32);text('F05-03 v01 · 实际模型 / 共用原生材质 · 草稿待审，未接入',30,108,17,'#ddb675');panel(30,146,565,570);text('停转 · 完整四叶与铜轴心',46,162,20);c.drawImage(assets['fan-idle-three-quarter.png'],46,203,533,490);panel(615,146,555,570);text('轴心、背部接口与固定壳体',631,162,20);c.drawImage(assets['fan-front.png'],631,203,245,245);c.drawImage(assets['fan-back.png'],908,203,245,245);c.drawImage(assets['fan-side.png'],631,463,245,230);text('固定护框 + 独立叶轮',903,475,18);text('铜轮毂与四角紧固点',903,519,18);text('排风向外，推力反向',903,563,18);text('叶片与护框保留间隙',903,607,18);text('缺电与预览时静止',903,651,17,'#ddb675');text('原生物品图 · 32×32与16×16分别设计',30,750,24);panel(30,792,565,264);panel(615,792,555,264);c.imageSmoothingEnabled=false;c.drawImage(assets.icon32,55,815,192,192);c.drawImage(assets.icon16,296,847,128,128);c.drawImage(assets.atlas,646,815,192,192);c.imageSmoothingEnabled=true;text('32px',99,1024,16);text('16px',337,1024,16);text('采用主体64px图集',862,818,20);text('图集像素原样复用',862,862,18);text('不新增风扇专用纹理',862,906,18);text('叶轮旋转，无新Shader',862,950,18);text('安装到采用主体 · 同一模型、同一接口',30,1090,24);for(const [im,caption,i]of [['fan-mounted-front.png','前节点尺寸参照',0],['fan-mounted-top.png','顶节点 · 控制板仍独立',1]]){const x=30+i*585;panel(x,1132,555,330);text(caption,x+16,1148,20);c.drawImage(assets[im],x+121,1189,312,256);}text('现有轴心、外框宽度、六向节点与供电/推进规则保持；本页仅供美术审稿。',30,1492,17,'#ddb675');}
window.ready=(async()=>{await Promise.all(Object.entries(sources).map(async([key,src])=>{const im=new Image();im.src=src;await im.decode();assets[key]=im;}));get('node').onchange=get('motion').onchange=get('age').oninput=get('yaw').oninput=get('pitch').oninput=update;get('play').onchange=()=>{lastTime=null;update()};document.querySelectorAll('[data-yaw]').forEach(b=>b.onclick=()=>{get('yaw').value=b.dataset.yaw;get('pitch').value=b.dataset.pitch;update()});get('icon32').src=sources.icon32;get('icon16').src=sources.icon16;update();drawBoard();requestAnimationFrame(loop);window.appReady=true;return true})();
</script></html>'''
html=html.replace('__JS__',js).replace('__G__',json.dumps(g)).replace('__IMAGES__',json.dumps(images));(R/'review/preview.html').write_text(html);print('风扇真实几何查看器、停转/旋转与六向审稿页已生成。')
