from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1]
def image(p):return 'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
G=json.loads((R/'source/geometry-and-uv.json').read_text());G['body']=json.loads((R/'references/approved-machine-geometry.json').read_text())
images={p.name:image(p)for folder in ['review','exports']for p in (R/folder).glob('*.png')if 'review'not in p.name}
snapshots=[dict(id='inactive',label='未工作 · 暗灯',active=False,ghost=False),dict(id='active',label='工作 · 薄荷绿灯',active=True,ghost=False),dict(id='enabled-inactive',label='已开启 · 节点未工作',active=False,ghost=False,enabled=True),dict(id='zero-energy',label='余量0 · 不推断未工作原因',active=False,ghost=False,energy=0),dict(id='last-payment',label='支付后余量0 · 本刻仍工作',active=True,ghost=False,energy=0),dict(id='power-reference',label='供能失败灯 · 仅设计参考',active=False,ghost=False,mode='design_reference',failureReason='payment_rejected'),dict(id='ghost',label='安装预览 · 统一绿色',active=True,ghost=True)]
(R/'source/review-snapshots.json').write_text(json.dumps(snapshots,ensure_ascii=False,indent=2)+'\n')
css='\n:root{color-scheme:dark;background:#14221c;color:#e7dec3;font:16px system-ui,sans-serif}*{box-sizing:border-box}body{margin:auto;padding:32px 24px;max-width:1240px}header small{color:#93b39e;letter-spacing:2px}h1{font-size:32px;margin:12px 0}p{line-height:1.7;color:#bbc7b5}h2{font-size:21px;margin-top:30px}main{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:20px}.panel,figure{background:#1c2d24;border:1px solid #354b3c;border-radius:14px;padding:18px;margin:0}canvas{display:block;width:100%;height:auto;border-radius:8px}button,select{background:#2c4235;color:#eee4ca;border:1px solid #59755e;border-radius:6px;padding:10px;min-height:40px;font:inherit;max-width:100%}button:hover{background:#405b47}label{display:block;margin:16px 0;font-size:14px;color:#c5cbb4}input[type=range]{width:100%;accent-color:#d6b078}strong{color:#f3e5bd}.note{font-size:13px}.chips{display:flex;gap:10px;flex-wrap:wrap}.chip{background:#304738;border-radius:6px;padding:8px 12px;font-size:13px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.grid img{width:100%;border-radius:8px}figcaption{font-size:13px;line-height:1.6;margin-top:8px}.icons{display:flex;gap:26px;flex-wrap:wrap}.pixel{image-rendering:pixelated}.icons img{width:128px;height:128px;background:#14221c;border:8px solid #24372b}.compare{display:grid;grid-template-columns:1fr 1fr;gap:18px}.compare img{width:100%}.atlas img{width:256px;max-width:100%;image-rendering:pixelated}a{color:#a3ddbb}@media(max-width:800px){main{grid-template-columns:1fr}.grid{grid-template-columns:repeat(2,1fr)}body{padding:24px 14px}h1{font-size:27px}.compare{gap:8px}}\n'
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · F05-08 稳定器 v01</title><style>__CSS__</style><header><small>WILDCRAFT / B3 · F05-08</small><h1>稳定器 · 钢端盖、铜腰带与水平标记</h1><p>倒角壳体与中央状态灯。部件保持固定，通过灯色表达工作状态；水平标记与电池电量窗口区分。</p><div class="chips"><span class="chip">v01 草稿待审</span><span class="chip">复用机械64×64图集</span><span class="chip">未接入游戏</span></div></header>
<h2>实际模型与状态灯</h2><main><section class="panel"><canvas id="live" aria-label="稳定器实际模型"></canvas><p id="render-info" class="note"></p></section><aside class="panel"><label>状态快照<select id="snapshot"></select></label><label>安装视图<select id="node"><option value="-1">独立部件</option><option value="0">顶节点</option><option value="1">底节点</option><option value="2">后节点</option><option value="3">前节点</option><option value="4">左节点</option><option value="5">右节点</option></select></label><label>整机倾侧参考 <span id="roll-label">0°</span><input id="roll" type="range" min="-6" max="6" value="0"></label><label>水平视角<input id="yaw" type="range" min="-180" max="180" value="-25"></label><label>俯仰视角<input id="pitch" type="range" min="-85" max="85" value="18"></label><button id="reset">恢复默认视图</button><p id="readout"></p><p class="note">工作灯读取当前节点active；未工作统一暗灯。整机开启或电池余量不能独立决定灯色。</p><p class="note">琥珀色仅为供能失败设计参考，尚未接入当前状态。安装视图中的倾侧参数用于展示现有工作稳定器将整机roll归零的规则。</p></aside></main>
<h2>三种灯色参考 · 同一模型</h2><section class="grid"><figure><img id="inactive-render"><figcaption>未工作 · 暗灯，不表示缺电</figcaption></figure><figure><img id="active-render"><figcaption>工作 · 薄荷绿，读取真实active</figcaption></figure><figure><img id="reference-render"><figcaption>供能失败 · 琥珀色，设计参考未接入</figcaption></figure></section>
<h2>原生物品图标</h2><section class="panel"><div id="icons" class="icons"></div><p class="note">32与16分别绘制，保留钢端盖、铜腰带与水平标记。物品图使用固定识别色，不表示实际工作或剩余电量。</p></section>
<h2>六向安装参考</h2><section id="mounts" class="grid"></section><p class="note">复用现有六节点和体积。模型本身不转动、不摆动；稳定器仍按现有规则抑制横向速度与整机倾侧，不承诺防坠落。</p>
<h2>灯面近看</h2><section class="grid"><figure><img id="inactive-lamp"><figcaption>暗灯 · 当前可用状态</figcaption></figure><figure><img id="active-lamp"><figcaption>工作灯 · 当前可用状态</figcaption></figure><figure><img id="reference-lamp"><figcaption>供能失败参考 · 需要明确原因</figcaption></figure></section>
<h2>统一纹理图集</h2><section class="panel atlas"><img id="atlas"><p class="note">完整复用采用机械64×64图集，新增生产贴图像素0。灯面由固定网格的状态颜色驱动，无需三套模型或逐帧贴图；不增加光晕或闪烁。</p></section>
<h2>综合审稿板</h2><section class="panel"><canvas id="board"></canvas><p><a href="stabilizer-review.png">打开审稿板 PNG</a></p></section><p class="note">本轮只制作美术，实际游戏安装、供能、状态同步与组合还需接入验证。</p>
<script>const G=__G__,SOURCES=__IMAGES__,SNAPSHOTS=__SNAPSHOTS__;</script><script>__RENDER__</script><script>
const loaded={},names=['顶','底','后','前','左','右'];window.reviewReady=false;
function current(){const s=SNAPSHOTS.find(s=>s.id===document.querySelector('#snapshot').value)||SNAPSHOTS[0];return {...s,requestedRoll:+document.querySelector('#roll').value}}
function redraw(){const s=current(),p=WildcraftStabilizerPreview.presentation(s),n=+document.querySelector('#node').value;window.lastPresentation=p;window.lastRender=WildcraftStabilizerPreview.drawModel(document.querySelector('#live'),loaded['shared-machine-atlas-64.png'],{...G,...p},+document.querySelector('#yaw').value,+document.querySelector('#pitch').value,n);document.querySelector('#roll-label').textContent=`${p.requestedRoll}° → ${p.bodyRoll}°`;document.querySelector('#render-info').textContent=`${p.ghost?'统一透明预览':p.designReferenceOnly?'供能失败灯 · 仅设计参考':p.working?'工作灯':'未工作暗灯'} · ${n<0?'独立部件':names[n]+'节点'}`;document.querySelector('#readout').innerHTML=`<strong>${p.ghost?'安装预览':p.designReferenceOnly?'琥珀灯 · 仅设计参考':p.working?'工作 · 薄荷绿灯':'未工作 · 暗灯'}</strong><br>${p.working?'当前节点实际工作，整机倾侧归零':p.designReferenceOnly?'须有明确供能失败原因才能启用':'不从灯灭推断停机、缺电或其他原因'}<br><span class="note">工作时每个稳定器2能量／世界刻。</span>`;}
for(const id of ['snapshot','node','roll','yaw','pitch'])document.querySelector('#'+id).addEventListener('input',redraw);document.querySelector('#reset').onclick=()=>{document.querySelector('#node').value=-1;document.querySelector('#snapshot').value='inactive';document.querySelector('#roll').value=0;document.querySelector('#yaw').value=-25;document.querySelector('#pitch').value=18;redraw()};
function board(){const c=document.querySelector('#board');c.width=1200;c.height=1700;const x=c.getContext('2d');x.fillStyle='#14221c';x.fillRect(0,0,c.width,c.height);const text=(s,a,b,size=22,col='#e7dec3')=>{x.fillStyle=col;x.font=`${size}px system-ui`;x.fillText(s,a,b)},image=(n,a,b,w,h,pixel=false)=>{x.imageSmoothingEnabled=!pixel;x.drawImage(loaded[n],a,b,w,h)};
text('WILDCRAFT · F05-08 / v01',40,50,22,'#93b39e');text('稳定器 · 钢端盖、铜腰带与水平标记',40,101,36);text('草稿待审 / 原生32与16分别绘制 / 未接入游戏',40,139,19,'#b1bca8');image('stabilizer-inactive-three-quarter.png',40,173,350,350);image('stabilizer-active-three-quarter.png',425,173,350,350);image('stabilizer-power-reference.png',810,173,350,350);text('未工作 · 暗灯',70,562,22);text('工作 · 薄荷绿灯',455,562,22);text('供能失败灯 · 仅设计参考',812,562,22);
image('stabilizer-item-32.png',100,620,160,160,true);image('stabilizer-item-16.png',390,620,160,160,true);text('32×32 独立像素稿',80,815,20);text('16×16 独立像素稿',355,815,20);text('固定壳体 · 水平标记',620,652,25);text('状态颜色驱动，不做转动或光晕',620,700,22);text('64×64统一图集，新增贴图像素0',620,745,21);
text('六向安装 · 原体积 · 当前工作灯',40,884,24);for(let i=0;i<6;i++){const a=40+i%3*383,b=910+Math.floor(i/3)*330;image('stabilizer-mounted-'+i+'.png',a+18,b,300,300);text(names[i]+'节点',a+20,b+319,20)}
text('当前工作/未工作两态；供能失败灯需明确原因才可接入。',40,1600,22);text('每个稳定器2能量／世界刻；部件固定，保留现有稳定规则。',40,1642,21);text('实际网格、可编辑源稿、原生图标与状态规范已存档。',40,1680,20,'#b1bca8');}
(async()=>{for(const[n,src]of Object.entries(SOURCES)){const im=new Image();im.src=src;await im.decode();loaded[n]=im;}document.querySelector('#snapshot').innerHTML=SNAPSHOTS.map(s=>`<option value="${s.id}">${s.label}</option>`).join('');for(const [id,name]of [['inactive','inactive-three-quarter'],['active','active-three-quarter'],['reference','power-reference']])document.querySelector('#'+id+'-render').src=SOURCES['stabilizer-'+name+'.png'];for(const [id,name]of [['inactive','inactive'],['active','active'],['reference','power-reference']])document.querySelector('#'+id+'-lamp').src=SOURCES['stabilizer-'+name+'-indicator.png'];document.querySelector('#atlas').src=SOURCES['shared-machine-atlas-64.png'];document.querySelector('#icons').innerHTML=[32,16].map(n=>`<figure><img class="pixel" alt="稳定器${n}像素" src="${SOURCES['stabilizer-item-'+n+'.png']}"><figcaption>${n}×${n} · 固定识别色</figcaption></figure>`).join('');document.querySelector('#mounts').innerHTML=names.map((n,i)=>`<figure><img alt="${n}节点安装" src="${SOURCES['stabilizer-mounted-'+i+'.png']}"><figcaption>${n}节点 · 固定部件与工作灯</figcaption></figure>`).join('');redraw();board();window.reviewReady=true;})().catch(e=>{window.reviewError=e.message;document.querySelector('#render-info').textContent=e.message});
</script></html>'''
html=html.replace('__CSS__',css).replace('__G__',json.dumps(G,separators=(',',':'),ensure_ascii=False)).replace('__IMAGES__',json.dumps(images,separators=(',',':'))).replace('__SNAPSHOTS__',json.dumps(snapshots,separators=(',',':'),ensure_ascii=False)).replace('__RENDER__',(R/'source/stabilizer-preview.js').read_text());(R/'review/preview.html').write_text(html);print('Stabilizer actual mesh and colour reference review ready')
