const fs=await import('node:fs/promises'),assert=(await import('node:assert/strict')).default,crypto=await import('node:crypto');const R='/Volumes/仕事/Wildcraft/开发环境/project/art/production-v2/F05-10/v02';const t=await taskSpace(4),p=t.page('p1');const sceneIds=await p.evaluate(()=>scenes.map(s=>s.id)),ui=[];
for(const id of sceneIds){await p.selectOption('#scenario',id);for(let n=0;n<6;n++){await p.selectOption('#node',String(n));const r=await p.evaluate(()=>({presentation:currentState.presentation,world:currentState.world,hud:currentState.hud,s:currentState.snapshot}));assert.equal(r.world.missingModelKinds.length,0);assert.equal(r.world.modelScale,1);assert.equal(r.world.ghostDepthWrite,false);assert.equal(r.world.depthTest,true);assert.equal(r.world.ghostPartKind,r.presentation.ghost);if(r.presentation.ghost)assert(r.world.ghostMeshParts>0);else assert.equal(r.world.ghostMeshParts,0);assert.equal(r.presentation.nodeActive,!!(r.s.active&(1<<n)));ui.push({scene:id,node:n,ghost:r.presentation.ghost,allPassed:true});}
 // Archive one actually rendered readable screen per scene.
 await p.selectOption('#node','3');const b64=await p.evaluate(()=>document.querySelector('#screen').toDataURL().split(',')[1]);await fs.writeFile(R+'/review/'+id+'.png',Buffer.from(b64,'base64'));
}
const layouts=[];for(const lang of ['zh','en'])for(const size of ['320,240','640,360','960,540']){await p.selectOption('#lang',lang);await p.selectOption('#size',size);for(const id of sceneIds){await p.selectOption('#scenario',id);const r=await p.evaluate(()=>currentState.hud);if(r.visible){assert(r.rect.x>=0&&r.rect.width<=+size.split(',')[0]);for(const k of ['primary','detail','hint'])assert(r.measuredTextWidths[k].every(w=>w<=r.availableTextWidths[k]+.001));assert(r.bottom<=+size.split(',')[1]-78+1,{id,lang,size,r});}layouts.push({id,lang,size,allPassed:true});}}
await p.selectOption('#lang','zh');await p.selectOption('#size','640,360');await p.selectOption('#key','J');await p.selectOption('#scenario','low-working');const key=await p.evaluate(()=>currentState.presentation.hint);assert(key.includes('[J]')&&!key.includes('[R]'));await p.selectOption('#key','R');await p.click('#gray');const gray=await p.evaluate(()=>currentState.gray);assert.equal(gray,true);await p.click('#gray');
const depth=await p.evaluate(()=>{const result=[],M=WildcraftMachinePresentation;for(let k=1;k<=8;k++)for(let n=0;n<6;n++){const s=M.withNode(scenes.find(s=>s.id==='part-'+k+'-ready'),n),canvas=document.createElement('canvas'),[yaw,pitch]=[[180,-75],[180,75],[0,0],[180,0],[-90,0],[90,0]][n],atlases={machine:assets.machine,fabric:assets.fabric,rocket:assets.rocket};M.drawWorld(canvas,atlases,G,F,s,0,yaw,pitch);const gl=canvas._gl.gl,read=()=>{const arr=new Uint8Array(640*450*4);gl.readPixels(0,0,640,450,gl.RGBA,gl.UNSIGNED_BYTE,arr);return arr},a=read(),original=gl.enable;try{gl.enable=function(cap){if(cap===gl.DEPTH_TEST)gl.disable(cap);else original.call(gl,cap)};M.drawWorld(canvas,atlases,G,F,s,0,yaw,pitch);}finally{gl.enable=original;}const b=read();let changed=0;for(let i=0;i<a.length;i+=4)if(a[i]!==b[i]||a[i+1]!==b[i+1]||a[i+2]!==b[i+2])changed++;result.push({part:k,node:n,depthVsDisabledChangedPixels:changed});gl.getExtension('WEBGL_lose_context')?.loseContext();}return result;});assert(depth.every(x=>x.depthVsDisabledChangedPixels>0));
const widths=[];for(const width of [320,768,1280]){await p.cdp('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});const r=await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(r.scroll<=r.width);widths.push(r);}await p.cdp('Emulation.clearDeviceMetricsOverride',{});
const embedded=await p.evaluate(()=>Object.entries(sources).map(([name,src])=>({name,data:src.split(',')[1]}))),images=[];for(const a of embedded){const name={machine:'machine-atlas-64.png',fabric:'fabric-atlas-128x64.png',rocket:'rocket-atlas-128x64.png',empty16:'F04-02-battery-empty-16.png',full16:'F04-02-battery-full-16.png',empty32:'F04-02-battery-empty-32.png',full32:'F04-02-battery-full-32.png'}[a.name],hash=x=>crypto.createHash('sha256').update(x).digest('hex');assert.equal(hash(Buffer.from(a.data,'base64')),hash(await fs.readFile(R+'/references/'+name)));images.push(name);}
await p.selectOption('#scenario','part-3-ready');await p.selectOption('#node','3');await p.click('#iso');const capture=await p.evaluate(()=>({board:document.querySelector('#board').toDataURL().split(',')[1],live:document.querySelector('#screen').toDataURL().split(',')[1]}));await fs.writeFile(R+'/review/all-parts-review.png',Buffer.from(capture.board,'base64'));await fs.writeFile(R+'/review/all-parts-live.png',Buffer.from(capture.live,'base64'));await fs.writeFile(R+'/review/browser-checks.json',JSON.stringify({asset:'F05-10',version:'v02',allPassed:true,uiCases:ui,layoutCases:layouts,uiCaseCount:ui.length,layoutCaseCount:layouts.length,depthFramebufferPairs:depth,viewportWidths:widths,embeddedImageBytesMatch:images,remappedKeyChecked:true,grayscaleChecked:true,sceneScreenshots:sceneIds,productionGameTested:false},null,2)+'\n');console.log({allPassed:true,ui:ui.length,layouts:layouts.length,depth:depth.length});
