from pathlib import Path
import json,base64
R=Path(__file__).resolve().parents[1]
def uri(p):return 'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
assets={'panel':uri(R/'exports/fabricator-ui-176x192.png')}
for name,file in [('fabricator','fabricator-atlas-64.png'),('charger','charger-atlas-64.png'),('wing','wing-item-16.png'),('battery','battery-item-16.png'),('model','fabricator-state-0.png')]:assets[name]=uri(R/'references'/file)
html=r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wildcraft · 制造机界面 v01</title><style>
*{box-sizing:border-box}body{margin:0;background:#13211a;color:#e1e8d9;font:15px/1.7 system-ui,"PingFang SC",sans-serif}main{max-width:1240px;margin:auto;padding:28px}h1{font-size:29px;margin:6px 0 10px}h2{font-size:19px}.tag{color:#dbb573;font-size:13px}.muted{color:#a9bca1}.controls{display:flex;flex-wrap:wrap;gap:16px;padding:18px;background:#253729;border:1px solid #465a43;border-radius:6px;margin:20px 0}label{display:flex;align-items:center;gap:8px;flex-wrap:wrap}select,input{accent-color:#c58b54;background:#17271c;color:inherit;border:1px solid #65765b;border-radius:3px;padding:6px;max-width:100%}input[type=range]{width:150px}input[type=number]{width:75px}button{background:#304631;color:inherit;border:1px solid #65765b;border-radius:4px;padding:6px 12px;cursor:pointer}:focus-visible{outline:3px solid #e5bd78;outline-offset:3px}.samples{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.stage{background:#0b130e;border:1px solid #3d513b;padding:18px;overflow:auto}canvas{image-rendering:pixelated;display:block}.board{max-width:100%;height:auto;image-rendering:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px}.card{background:#253729;border:1px solid #465a43;padding:16px;overflow:auto;min-width:0}.card h3{font-size:17px;margin:0 0 12px}.card p{font-size:13px;color:#b5c6aa}.small{font-size:13px;color:#a3b69b}.description{padding:12px 0;min-height:44px}a{color:#d1ddb9}@media(max-width:650px){main{padding:20px 14px}}
</style><main><span class="tag">F06-02 · v01 · 草稿待审 · 未接入游戏</span><h1>制造机界面 · 材料、进度与领取</h1><p class="muted">原生176×192底图，保留2材料槽、1产物槽、36格物品栏及现有制造按钮位置。成本、等概率说明、数量和进度使用程序文字，五态符号复用已采用图集。</p>
<div class="controls"><label>审稿场景<select id="scenario"></select></label><label>语言<select id="language"><option value="zh">中文</option><option value="en">English</option></select></label><label>显示倍数<select id="scale"><option>1</option><option>2</option><option selected>3</option><option>4</option></select></label><label>工作进度<input id="progress" type="range" min="0" max="100" value="50"></label><label>准确刻数<input id="number" type="number" min="0" max="100" value="50"></label><label>悬停说明<select id="hover"><option value="auto">随鼠标</option><option value="none">关闭</option><option value="status">状态说明</option><option value="pool">产物范围</option><option value="cost">材料成本</option><option value="output">产出格</option></select></label><label><input id="bounds" type="checkbox">实际槽位</label></div>
<div class="samples" id="samples"></div><div class="stage"><canvas id="live" role="img" aria-label="制造机界面审稿"></canvas></div><div class="description" id="description" aria-live="polite"></div><div class="samples"><button id="collect">审稿演示：取出产出格物品</button><span class="small">可在「材料就绪」场景点击画布里的制造按钮，再拖动进度观察完成；不连接游戏，不抽取随机结果。</span></div>
<p class="small">工作进度按100个已加载世界刻显示；“成品待取”的满条表示已完成，服务器progress此时已经重置为0。状态3格中显示的是先前已有物品，本批结果仍隐藏。槽内材料仅用已采用的8px标记作占位，实机接入复用原版物品图与字体。</p>
<h2>五种状态对照</h2><div class="grid" id="gallery"></div><h2>审稿总览</h2><canvas id="board" class="board" width="1200" height="1460"></canvas><p class="small">八类产物等概率，各12.5%。网页外侧控件仅用于审稿；数量及材料使用固定场景。正式客户端只请求制造，随机、扣料、进度与转移仍由服务器管理；本次不改Java、语言文件或JAR。</p></main>
<script>__UI__</script><script>
const U=WildcraftFabricatorUi,sources=__ASSETS__,imgs={};let state={...U.fixtures.working,language:'zh',bounds:false},hoverTarget=null,buttonHovered=false,demoStarts=0;
function get(id){return document.getElementById(id)}
function text(c,str,x,y,color='#354438',font='9px monospace,"PingFang SC",sans-serif'){c.font=font;c.textBaseline='top';c.fillStyle=color;c.fillText(str,x,y);return {text:str,x,y,width:c.measureText(str).width,height:9};}
function itemCount(c,n,x,y){if(n<=1)return null;c.font='8px monospace';c.textBaseline='top';const t=String(n),w=c.measureText(t).width;c.fillStyle='#293632';c.fillText(t,x+16-w+1,y+9);c.fillStyle='#fff7df';c.fillText(t,x+16-w,y+8);return {text:t,x:x+16-w,y:y+8,width:w,height:8};}
function button(c,s){const active=U.startEnabled(s),hover=active&&buttonHovered;const b=U.layout.button;c.fillStyle='#293632';c.fillRect(b.x,b.y,b.w,b.h);c.fillStyle=active?(hover?'#b4c5b4':'#83949a'):'#7b8980';c.fillRect(b.x+1,b.y+1,b.w-2,b.h-2);c.fillStyle=active?'#d7ddce':'#b4c2b5';c.fillRect(b.x+1,b.y+1,b.w-2,1);c.fillStyle='#47545b';c.fillRect(b.x+1,b.y+b.h-2,b.w-2,1);const t=U.labels[s.language].start;c.font='9px monospace,"PingFang SC",sans-serif';return {active,hovered:hover,label:text(c,t,b.x+(b.w-c.measureText(t).width)/2,b.y+6,active?'#20372a':'#4d5b52'),bounds:b};}
function drawUi(c,s){c.save();c.imageSmoothingEnabled=false;c.drawImage(imgs.panel,0,0);const st=U.states[s.status],L=U.labels[s.language],labels=[];labels.push(text(c,L.title,8,7));labels.push(text(c,L.cost,8,19));labels.push(text(c,L.pool,8,76));labels.push(text(c,L.inventory,8,100));
const counts=[];for(const [n,x,gx] of [[s.copper,26,16],[s.redstone,54,24]]){if(n>0){c.drawImage(imgs.fabricator,gx,48,8,8,x+4,39,8,8);const q=itemCount(c,n,x,35);if(q)counts.push(q);}else{c.save();c.globalAlpha=.28;c.drawImage(imgs.fabricator,gx,48,8,8,x+4,39,8,8);c.restore();}}
if(s.output)c.drawImage(imgs[s.output],134,54,16,16);
const b=button(c,s),bar=U.barWidth(s);c.fillStyle=s.status===3?'#ad7c37':'#608865';if(bar)c.fillRect(81,60,bar,5);const progressText=s.status===4?L.done:U.ticks(s.progress)+'/100';c.font='9px monospace,"PingFang SC",sans-serif';const progressLabel=text(c,progressText,101.5-c.measureText(progressText).width/2,50);labels.push(progressLabel);
const glyph=st.glyph;c.drawImage(imgs[glyph.atlas],glyph.x,glyph.y,8,8,10,88,8,8);const statusText=text(c,st[s.language],22,88,st.color);labels.push(statusText);
if(s.bounds){c.strokeStyle='#da722b';c.lineWidth=1;for(const q of U.slots)c.strokeRect(q.x-.5,q.y-.5,17,17);}c.restore();return {status:s.status,sourceProgress:U.ticks(s.progress),barWidth:bar,completedOutcome:s.status===4,buttonEnabled:b.active,button:b,statusText,labels,counts,slots:U.slots,outputVisible:!!s.output,outputKind:s.output,uncommittedResultShown:false,size:[176,192]};}
function wrap(c,str,max){c.font='9px monospace,"PingFang SC",sans-serif';const tokens=/[\u3400-\u9fff]/.test(str)?[...str]:str.split(/\s+/).map((t,i)=>(i?' ':'')+t);const lines=[];let line='';for(const token of tokens){if(c.measureText(line+token).width<=max||!line)line+=token;else{lines.push(line.trim());line=token.trimStart();}}if(line)lines.push(line.trim());return lines;}
function help(s,kind){const zh=s.language==='zh',st=U.states[s.status];if(kind==='pool')return {title:zh?'八类部件，各12.5%':'8 types, 12.5% each',body:zh?'翼、风扇、火箭、电池、弹簧、轮子、稳定器、浮力装置。主体与燃尽空壳不在制造池中；本批结果仅完成转移后显示。':'Wing, fan, rocket, battery, spring, wheel, stabilizer and float. Body and spent casing are excluded. The new result is shown only after transfer.'};if(kind==='cost')return {title:U.labels[s.language].cost,body:zh?'每批消耗4铜锭与2红石。材料或任务状态不允许时制造按钮不可用；红石信号与外接电源不是本机的制造条件。':'Consumes 4 copper ingots and 2 redstone per batch. The button is disabled when materials or job status prevent starting. Redstone signals and external power are not crafting conditions.'};if(kind==='output'){if(!s.output)return {title:zh?'产出格为空':'Output is empty',body:zh?'完成转移前不预览本批随机结果。':'The new random result is not previewed before completed transfer.'};return {title:s.output==='battery'?(zh?'先前已有的电池（示例）':'Existing battery (example)'):(zh?'已转移的机械翼（示例）':'Transferred wing (example)'),body:s.status===3?st[zh?'helpZh':'helpEn']:(zh?'本页仅用已采用物品图说明实际产出槽的显示，不代表随机结果固定为机械翼。':'This review uses an adopted icon to show the real output slot. It does not make the random result always a wing.')};}return {title:st[s.language],body:st[zh?'helpZh':'helpEn']};}
function drawTooltip(c,s,kind){const content=help(s,kind),lines=[...wrap(c,content.title,164),...wrap(c,content.body,164)],x=180,w=176,h=lines.length*11+12,y=Math.max(4,Math.min(75,192-h-4));c.fillStyle='#201d2b';c.fillRect(x,y,w,h);c.strokeStyle='#6f587a';c.strokeRect(x+.5,y+.5,w-1,h-1);const measured=lines.map((v,i)=>text(c,v,x+6,y+6+i*11,i===0?'#e9d9ad':'#c8d2bf'));return {kind,x,y,width:w,height:h,lines:measured};}
function currentTooltip(){const v=get('hover').value;return v==='none'?null:v==='auto'?hoverTarget:v;}
function drawLive(){const cv=get('live'),scale=+get('scale').value,tip=currentTooltip();cv.width=tip?360:176;cv.height=192;cv.style.width=cv.width*scale+'px';cv.style.height=192*scale+'px';const c=cv.getContext('2d');c.clearRect(0,0,cv.width,cv.height);const out=drawUi(c,state);out.tooltip=tip?drawTooltip(c,state,tip):null;window.lastLayout=out;get('description').textContent=U.states[state.status][state.language]+' · '+(state.status===4?U.labels[state.language].done:U.ticks(state.progress)+' / 100 加载世界刻')+' · '+(state.status===0?'可开始':'制造按钮不可用');cv.setAttribute('aria-label',U.states[state.status][state.language]+', 2 material slots, 1 output slot, 36 inventory slots');}
function update(){state.language=get('language').value;state.bounds=get('bounds').checked;get('progress').value=get('number').value=U.ticks(state.progress);get('progress').disabled=get('number').disabled=!state.hasJob;get('collect').disabled=!state.output;get('scenario').value=U.states[state.status].key;drawLive();}
function apply(key){state={...U.fixtures[key],language:get('language').value,bounds:get('bounds').checked};hoverTarget=null;buttonHovered=false;update();}
function setProgress(n){state=U.demoProgress(state,n);update();}
function startDemo(){const r=U.demoStart(state);if(r.started){state=r.snapshot;demoStarts++;update();}return r.started;}
function drawGallery(){get('gallery').replaceChildren();for(const st of U.states){const card=document.createElement('article');card.className='card';const h=document.createElement('h3');h.textContent=st[get('language').value];card.append(h);const cv=document.createElement('canvas');cv.id='sample-'+st.key;cv.width=176;cv.height=192;cv.style.width='176px';cv.style.height='192px';drawUi(cv.getContext('2d'),{...U.fixtures[st.key],language:get('language').value,bounds:false});card.append(cv);const p=document.createElement('p');p.textContent=st[get('language').value==='zh'?'helpZh':'helpEn'];card.append(p);get('gallery').append(card);}}
function drawBoard(){const c=get('board').getContext('2d');c.imageSmoothingEnabled=false;const label=(s,x,y,size=18,color='#dce6d4')=>{c.font=size+'px system-ui,"PingFang SC",sans-serif';c.textBaseline='top';c.fillStyle=color;c.fillText(s,x,y)},panel=(x,y,w,h)=>{c.fillStyle='#24392a';c.fillRect(x,y,w,h);c.strokeStyle='#415b40';c.strokeRect(x+.5,y+.5,w-1,h-1)},full=(key,lang='zh')=>{const cv=document.createElement('canvas');cv.width=176;cv.height=192;drawUi(cv.getContext('2d'),{...U.fixtures[key],language:lang,bounds:false});return cv;};c.fillStyle='#13251b';c.fillRect(0,0,1200,1460);label('WILDCRAFT / FABRICATOR UI',30,30,16,'#a7bb9a');label('制造机界面 · 材料、进度与领取',30,64,32);label('F06-02 v01 · 原生176×192 / 39槽与按钮保持 · 草稿待审，未接入',30,111,17,'#ddb777');panel(30,150,557,635);label('工作中 · 50 / 100 加载世界刻',48,164,20);c.drawImage(full('working'),45,198,528,576);panel(609,150,561,635);label('与已采用制造机外观统一',630,164,20);c.drawImage(imgs.model,655,201,445,445);label('2材料 + 1产物 + 36格物品栏',630,665,19,'#dcb575');label('每批4铜锭、2红石；八类各12.5%',630,704,18);label('工作结果隐藏；完成占位与待取分开',630,744,18);
label('五种状态 · 上半区 ×2；下方物品栏共享',30,813,22);U.states.forEach((st,i)=>{const x=30+(i%3)*390,y=857+Math.floor(i/3)*258;panel(x,y,371,245);label(st.zh,x+10,y+9,18);c.drawImage(full(st.key),0,0,176,99,x+9,y+35,352,198);});const x=822,y=1125;label('同一原生底图',x,y,22,'#dcb575');label('状态符号复用现有图集',x,y+44,18);label('数量、文字、进度程序绘制',x,y+80,18);label('完成条表达完成，不是伪造刻数',x,y+116,17);label('未完成不预览新产物',x,y+152,18);label('固定示例图只在实际产出格显示',x,y+188,17);
label('中英文短文案与完整悬停说明；不新增输入输出操作或外接电源。',30,1395,18);label('材料标记为占位，游戏复用原版物品；浏览器字体与按钮为近似，实机待验证。',30,1430,15,'#a3b69a');}
for(const st of U.states)get('scenario').add(new Option(st.zh,st.key));get('scenario').value='working';get('scenario').onchange=e=>apply(e.target.value);get('language').onchange=()=>{update();drawGallery();};get('scale').onchange=drawLive;get('bounds').onchange=update;get('hover').onchange=drawLive;get('progress').oninput=e=>setProgress(+e.target.value);get('number').oninput=e=>setProgress(+e.target.value);get('collect').onclick=()=>{state=U.demoCollect(state);update();};
function point(e){const cv=get('live'),r=cv.getBoundingClientRect(),scale=+get('scale').value;return {x:(e.clientX-r.left)/scale,y:(e.clientY-r.top)/scale};}
function within(p,q){return p.x>=q.x&&p.x<q.x+q.w&&p.y>=q.y&&p.y<q.y+q.h;}
get('live').onmousemove=e=>{const p=point(e),nextButton=within(p,U.layout.button);let next=null;if(within(p,U.layout.status.hover))next='status';else if(within(p,U.layout.pool.hover))next='pool';else if(within(p,U.layout.outputSlot))next='output';else if(within(p,{x:8,y:19,w:160,h:10})||U.layout.inputSlots.some(q=>within(p,q)))next='cost';if(nextButton!==buttonHovered||next!==hoverTarget){buttonHovered=nextButton;hoverTarget=next;drawLive();}};get('live').onmouseleave=()=>{hoverTarget=null;buttonHovered=false;drawLive();};get('live').onclick=e=>{if(within(point(e),U.layout.button))startDemo();};
for(const st of U.states){const b=document.createElement('button');b.textContent=st.zh;b.dataset.scenario=st.key;b.onclick=()=>apply(st.key);get('samples').append(b);}
window.ready=(async()=>{await Promise.all(Object.entries(sources).map(async([key,src])=>{const im=new Image();im.src=src;await im.decode();imgs[key]=im;}));update();drawGallery();drawBoard();window.appReady=true;return true})();
</script></html>'''
html=html.replace('__UI__',(R/'source/fabricator-ui.js').read_text()).replace('__ASSETS__',json.dumps(assets));(R/'review/preview.html').write_text(html);print('Self-contained five-state UI review created',len(html))
